<div class="pulse-rpt">
{if $pending}<div class="panel"><h3><i class="icon-warning"></i> Awaiting approval ({$pending|count})</h3><table class="table table-condensed"><thead><tr><th>No</th><th>Date</th><th>Category</th><th>Description</th><th>Payee</th><th class="text-right">Amount</th><th>By</th><th></th></tr></thead><tbody>
{foreach $pending as $x}<tr><td>{$x.expense_no}</td><td>{$x.business_date}</td><td>{$x.category}</td><td>{$x.description}</td><td>{$x.payee}</td><td class="text-right">{$cur}{$x.amount|number_format:0}</td><td>{$x.who}</td><td><form method="post" class="inline"><input type="hidden" name="id_expense" value="{$x.id_pulse_expense}"><button name="setExpStatus" class="btn btn-xs btn-success" formaction="{$self_url}&status=approved">Approve</button> <button name="setExpStatus" class="btn btn-xs btn-danger" formaction="{$self_url}&status=rejected">Reject</button></form></td></tr>{/foreach}</tbody></table></div>{/if}
<div class="row"><div class="col-md-7"><div class="panel"><h3><i class="icon-money"></i> Record an expense</h3>
<form method="post" class="form-horizontal">
<div class="form-group"><label class="col-sm-3">Category / dept</label><div class="col-sm-5"><select name="id_category" class="form-control">{foreach $categories as $c}<option value="{$c.id_pulse_expense_category}">{$c.name} ({$c.group_name|replace:'_':' '})</option>{/foreach}</select></div><div class="col-sm-4"><select name="department" class="form-control">{foreach ['general','rooms','fnb','housekeeping','laundry','maintenance','admin','sales','security'] as $dp}<option>{$dp}</option>{/foreach}</select></div></div>
<div class="form-group"><label class="col-sm-3">Description / payee</label><div class="col-sm-5"><input name="description" class="form-control" required></div><div class="col-sm-4"><input name="payee" class="form-control" placeholder="Payee / supplier"></div></div>
<div class="form-group"><label class="col-sm-3">Amount / tax</label><div class="col-sm-4"><input name="amount" type="number" step="0.01" class="form-control" required></div><div class="col-sm-3"><input name="tax_amount" type="number" step="0.01" class="form-control" placeholder="VAT incl."></div><div class="col-sm-2"><select name="payment_method" class="form-control"><option>cash</option><option>transfer</option><option>card</option><option>petty_cash</option><option>credit</option></select></div></div>
<div class="form-group"><label class="col-sm-3">Reference / date</label><div class="col-sm-5"><input name="reference" class="form-control" placeholder="Invoice / receipt no."></div><div class="col-sm-4"><input type="date" name="business_date" class="form-control"></div></div>
<button name="addExpense" class="btn btn-primary pull-right">Record expense</button></form>
<p class="help-block">Expenses above the approval limit go to "Awaiting approval" and are excluded from reports until approved.</p></div></div>
<div class="col-md-5"><div class="panel"><h3>Automatic cost feeds</h3><p>Maintenance parts/contractor costs, laundry chemicals and vendor orders, meter purchases (diesel, power, water, gas) and front-desk paid-outs are pulled in automatically each night. Pull a date now:</p>
<form method="post" class="form-inline"><input type="date" name="sync_date" class="form-control" value="{$to}"> <button name="syncFeeds" class="btn btn-default">Pull feeds</button></form>
<h3>Budget for {$year}-{$month|string_format:"%02d"}</h3><form method="post" class="form-inline"><input type="hidden" name="year" value="{$year}"><input type="hidden" name="month" value="{$month}">
<table class="table table-condensed">{foreach $budget_lines as $k=>$v}<tr><td>{$v}</td><td><input name="b[{$k}]" class="form-control input-sm" value="{$budget[$k]|default:''}"></td></tr>{/foreach}</table><button name="saveBudget" class="btn btn-default btn-sm">Save budget</button></form>
<form method="get" class="form-inline" style="margin-top:6px"><input type="hidden" name="controller" value="AdminPulseExpenses"><input type="hidden" name="token" value="{$smarty.get.token|escape}"><input name="year" class="form-control input-sm" value="{$year}" style="width:70px"> <input name="month" class="form-control input-sm" value="{$month}" style="width:50px"> <button class="btn btn-sm btn-default">Change month</button></form>
<h4>Add category</h4><form method="post" class="form-inline"><input name="ccode" class="form-control input-sm" placeholder="CODE" style="width:80px"> <input name="cname" class="form-control input-sm" placeholder="Name"> <select name="cgroup" class="form-control input-sm">{foreach ['cost_of_sales','payroll','utilities','repairs','admin','marketing','property','other'] as $g}<option>{$g}</option>{/foreach}</select> <button name="addCategory" class="btn btn-sm btn-default">Add</button></form></div></div></div>
<div class="panel"><h3>Expense ledger {$from} → {$to} — total {$cur}{$total|number_format:0}</h3>
<form method="get" class="form-inline"><input type="hidden" name="controller" value="AdminPulseExpenses"><input type="hidden" name="token" value="{$smarty.get.token|escape}"><input type="date" name="from" value="{$from}" class="form-control input-sm"> <input type="date" name="to" value="{$to}" class="form-control input-sm"> <button class="btn btn-sm btn-default">Filter</button></form>
<div class="row"><div class="col-md-4"><table class="table table-condensed"><thead><tr><th>Category</th><th>#</th><th class="text-right">Total</th></tr></thead><tbody>{foreach $by_category as $c}<tr><td>{$c.name} <small class="text-muted">{$c.group_name|replace:'_':' '}</small></td><td>{$c.n}</td><td class="text-right">{$cur}{$c.total|number_format:0}</td></tr>{/foreach}</tbody></table></div>
<div class="col-md-8"><table class="table table-condensed"><thead><tr><th>No</th><th>Date</th><th>Category</th><th>Description</th><th>Payee</th><th>Method</th><th class="text-right">Amount</th><th>Status</th><th>Source</th></tr></thead><tbody>{foreach $expenses as $x}<tr class="{if $x.status=='rejected'}text-muted{elseif $x.status=='submitted'}warning{/if}"><td>{$x.expense_no}</td><td>{$x.business_date}</td><td>{$x.code}</td><td>{$x.description}</td><td>{$x.payee}</td><td>{$x.payment_method}</td><td class="text-right">{$cur}{$x.amount|number_format:0}</td><td>{$x.status}{if $x.status=='approved'} <form method="post" class="inline"><input type="hidden" name="id_expense" value="{$x.id_pulse_expense}"><button name="setExpStatus" class="btn btn-xs btn-link" formaction="{$self_url}&status=paid">mark paid</button></form>{/if}</td><td>{$x.source}</td></tr>{/foreach}</tbody></table></div></div></div></div>
