/* Pulse POS — touch application. Vanilla JS, no build step. */
var POS = (function () {
  var S = { sess: null, staff: null, outlet: null, menu: null, check: null, seat: 1, cat: null, selLine: null, tables: [], section: null, cashSession: null, idle: 0, view: 'login' };
  var $ = function (id) { return document.getElementById(id); };
  var esc = function (s) { return String(s == null ? '' : s).replace(/[&<>"]/g, function (c) { return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]; }); };
  var money = function (v) { return POS_CUR + Number(v || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 }); };
  /* ---- offline queue: line/send/update/delivered are queued when the server is unreachable and replayed (idempotent by client_id) on reconnect ---- */
  var OFF = { queue: JSON.parse(localStorage.getItem('pulse_pos_queue') || '[]'), online: true };
  function saveQ() { localStorage.setItem('pulse_pos_queue', JSON.stringify(OFF.queue)); var b = document.getElementById('offline-badge'); if (b) { b.textContent = OFF.online ? (OFF.queue.length ? OFF.queue.length + ' queued' : '') : 'OFFLINE ' + OFF.queue.length + ' queued'; } }
  var QUEUEABLE = { line: 1, send: 1, update: 1, delivered: 1, void_line: 1 };
  function api(res, id, body, method) {
    var url = POS_API + (POS_API.indexOf('?') > -1 ? '&' : '?') + 'resource=' + res + (id ? '&id=' + id : '');
    return fetch(url, { method: body || method === 'POST' ? 'POST' : 'GET', headers: { 'Content-Type': 'application/json', 'X-Pos-Session': S.sess || '' }, body: body ? JSON.stringify(body) : undefined }).then(function (r) { return r.json(); }).then(function (r) { if (!OFF.online) { OFF.online = true; toast('Back online'); replay(); } if (!r.ok) { if (r.error === 'Session expired') { logout(true); } throw new Error(r.error || 'Error'); } return r.data; })
      .catch(function (e) { if (e instanceof TypeError && QUEUEABLE[res] && body) { OFF.online = false; OFF.queue.push({ client_id: 'c' + Date.now() + Math.random().toString(36).slice(2, 8), resource: res, id: id, body: body }); saveQ(); toast('Offline — action queued', true); return offlineApply(res, id, body); } if (e instanceof TypeError) { OFF.online = false; saveQ(); } throw e; });
  }
  function offlineApply(res, id, body) { if (res === 'line' && S.check) { var i = S.menu.items.filter(function (x) { return x.id == body.id_item; })[0]; S.check.lines.push({ id_pulse_pos_check_line: 'tmp' + Date.now(), name: i ? i.name : 'item', qty: body.qty, seat: body.seat, modifiers: [], line_total: i ? i.price * body.qty : 0, kot_status: 'pending', voided: 0, note: body.note, line_discount: 0, comp: 0 }); S.check.subtotal = (parseFloat(S.check.subtotal) || 0) + (i ? i.price * body.qty : 0); S.check.total = S.check.subtotal; } return S.check; }
  function replay() { if (!OFF.queue.length) { return; } var q = OFF.queue.slice(); fetch(POS_API + (POS_API.indexOf('?') > -1 ? '&' : '?') + 'resource=replay', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Pos-Session': S.sess || '' }, body: JSON.stringify({ actions: q }) }).then(function (r) { return r.json(); }).then(function (r) { if (r.ok) { OFF.queue = []; saveQ(); toast('Offline actions synced (' + q.length + ')'); if (S.check) { load(S.check.id_pulse_pos_check); } } }).catch(function () {}); }
  window.addEventListener('online', function () { OFF.online = true; replay(); }); window.addEventListener('offline', function () { OFF.online = false; saveQ(); });
  if ('serviceWorker' in navigator) { navigator.serviceWorker.register(POS_SW || 'sw.js').catch(function () {}); }
  function toast(msg, err) { var t = $('toast'); t.textContent = msg; t.className = 'toast' + (err ? ' err' : ''); clearTimeout(t._t); t._t = setTimeout(function () { t.className = 'toast hidden'; }, err ? 3500 : 1800); }
  function fail(e) { toast(e.message || e, true); }
  function modal(title, html, after) { $('modal-title').textContent = title; $('modal-body').innerHTML = html; $('modal').classList.remove('hidden'); if (after) { after(); } }
  function closeModal() { $('modal').classList.add('hidden'); }
  function render(html) { $('app').innerHTML = html; }

  /* ---------- login ---------- */
  var pin = '';
  function login() {
    S.view = 'login'; S.check = null;
    render('<div class="screen center"><div class="login"><h1>' + esc(POS_HOTEL) + '</h1><div style="color:#9aa4b1">Pulse POS</div><select id="outlet">' + POS_OUTLETS.map(function (o) { return '<option value="' + o.id + '"' + (S.outlet && S.outlet.id == o.id ? ' selected' : '') + '>' + esc(o.name) + '</option>'; }).join('') + '</select><div class="pin" id="pin">&nbsp;</div><div class="pad">' + [1, 2, 3, 4, 5, 6, 7, 8, 9, 'C', 0, '⏎'].map(function (k) { return '<button class="btn' + (k === '⏎' ? ' ok' : '') + '" data-k="' + k + '">' + k + '</button>'; }).join('') + '</div></div></div>');
    pin = ''; document.querySelectorAll('.pad .btn').forEach(function (b) { b.onclick = function () { var k = b.dataset.k; if (k === 'C') { pin = ''; } else if (k === '⏎') { doLogin(); return; } else if (pin.length < 6) { pin += k; } $('pin').textContent = pin.replace(/./g, '●') || ' '; if (pin.length >= 4 && POS_CFG.autoEnter) { doLogin(); } }; });
    document.addEventListener('keydown', keyPin);
  }
  function keyPin(e) { if (S.view !== 'login') { return; } if (/^[0-9]$/.test(e.key) && pin.length < 6) { pin += e.key; $('pin').textContent = pin.replace(/./g, '●'); } if (e.key === 'Enter') { doLogin(); } if (e.key === 'Backspace') { pin = pin.slice(0, -1); $('pin').textContent = pin.replace(/./g, '●') || ' '; } }
  function doLogin() { var id = $('outlet').value; S.outlet = POS_OUTLETS.filter(function (o) { return o.id == id; })[0]; api('login', 0, { pin: pin, id_outlet: id }).then(function (d) { S.sess = d.session; S.staff = d.staff; S.cashSession = d.cash_session; document.removeEventListener('keydown', keyPin); return api('menu', S.outlet.id); }).then(function (m) { S.menu = m; floor(); }).catch(function (e) { pin = ''; $('pin').textContent = ' '; fail(e); }); }
  function logout(expired) { if (S.sess && !expired) { api('logout', 0, { clock_out: 0 }).catch(function () {}); } S.sess = null; S.staff = null; login(); }
  setInterval(function () { if (S.sess && POS_CFG.autoLogout > 0 && ++S.idle >= POS_CFG.autoLogout * 60) { S.idle = 0; logout(); } }, 1000);
  document.addEventListener('click', function () { S.idle = 0; });

  /* ---------- floor / open checks ---------- */
  function topbar(title, back) { return '<div class="topbar">' + (back ? '<button class="btn ghost" onclick="POS.' + back + '()">‹ Back</button>' : '') + '<strong>' + esc(title) + '</strong><span class="who">' + esc(S.outlet.name) + ' · ' + esc(S.staff.firstname + ' ' + S.staff.lastname) + ' (' + esc(S.staff.role) + ')' + (S.menu && S.menu.price_level.period ? ' · ' + esc(S.menu.price_level.period) : '') + '</span><span class="grow"></span><span id="offline-badge" class="badge"></span><button class="btn" onclick="POS.cashier()">Cashier</button><button class="btn" onclick="POS.closedChecks()">Closed</button><button class="btn ghost" onclick="POS.logout()">Lock</button></div>'; }
  function floor() {
    S.view = 'floor'; S.check = null;
    Promise.all([api('tables', S.outlet.id), api('checks', S.outlet.id)]).then(function (r) {
      S.tables = r[0]; var checks = r[1]; var sections = []; S.tables.forEach(function (t) { if (sections.indexOf(t.section) < 0) { sections.push(t.section); } }); if (!S.section || sections.indexOf(S.section) < 0) { S.section = sections[0]; }
      var h = topbar('Tables & Checks') + '<div class="floor"><div class="floor-map"><div class="section-tabs">' + sections.map(function (s) { return '<button class="btn' + (s === S.section ? ' primary' : '') + '" onclick="POS.section(\'' + esc(s) + '\')">' + esc(s || 'Tables') + '</button>'; }).join('') + '</div><div style="position:relative;height:420px">';
      S.tables.filter(function (t) { return t.section === S.section; }).forEach(function (t) { h += '<div class="tbl ' + t.shape + ' ' + t.status + '" style="left:' + t.pos_x + 'px;top:' + t.pos_y + 'px" onclick="POS.tapTable(' + t.id_pulse_pos_table + ')"><div class="code">' + esc(t.code) + '</div><div class="meta">' + (t.id_pulse_pos_check ? esc(t.server) + ' · ' + money(t.total) + '<br>' + t.covers + ' cov · ' + t.minutes + 'm' : t.seats + ' seats · ' + t.status) + '</div></div>'; });
      h += '</div></div><div class="floor-side"><div class="quick"><button class="btn primary" onclick="POS.newCheck(\'takeaway\')">Takeaway</button>' + (S.outlet.allow_tabs == 1 ? '<button class="btn primary" onclick="POS.newCheck(\'bar_tab\')">Bar tab</button>' : '') + (S.outlet.allow_room_charge == 1 ? '<button class="btn primary" onclick="POS.newCheck(\'room_service\')">Room service</button>' : '') + '<button class="btn primary" onclick="POS.newCheck(\'delivery\')">Delivery</button></div><div style="padding:6px 12px;font-size:12px;color:#9aa4b1">OPEN CHECKS (' + checks.length + ')</div><div class="list">' + checks.map(function (c) { return '<div class="row" onclick="POS.load(' + c.id + ')"><div class="grow"><b>' + esc(c.table_code || (c.room_num ? 'Rm ' + c.room_num : c.order_type.replace('_', ' '))) + '</b> ' + esc(c.guest_name || '') + '<br><small>' + esc(c.check_no) + ' · ' + esc(c.server) + ' · ' + c.covers + ' cov</small></div><div>' + money(c.total) + (c.unsent > 0 ? '<br><span class="badge">' + c.unsent + ' unsent</span>' : '') + (c.status === 'printed' ? '<br><small>billed</small>' : '') + '</div></div>'; }).join('') + '</div></div></div>';
      render(h);
    }).catch(fail);
  }
  function tapTable(id) { var t = S.tables.filter(function (x) { return x.id_pulse_pos_table == id; })[0]; if (t.id_pulse_pos_check) { return load(t.id_pulse_pos_check); } if (t.status === 'blocked') { return toast('Table blocked', true); } if (t.status === 'dirty') { return modal('Table ' + t.code, '<p>Table is marked dirty. Seat guests here anyway?</p><div class="grid2"><button class="btn ok" onclick="POS.seatTable(' + id + ')">Seat</button><button class="btn" onclick="POS.closeModal()">Cancel</button></div>'); } seatTable(id); }
  function seatTable(id) { closeModal(); var t = S.tables.filter(function (x) { return x.id_pulse_pos_table == id; })[0]; if (S.outlet.require_covers == 1) { modal('Covers — Table ' + t.code, '<div class="grid4">' + [1, 2, 3, 4, 5, 6, 8, 10].map(function (n) { return '<button class="btn big" onclick="POS.openCheck({id_table:' + id + ',covers:' + n + '})">' + n + '</button>'; }).join('') + '</div><input id="cov" type="number" placeholder="Other"><button class="btn primary" onclick="POS.openCheck({id_table:' + id + ',covers:document.getElementById(\'cov\').value})">OK</button>'); } else { openCheck({ id_table: id, covers: t.seats }); } }
  function newCheck(type) { if (type === 'room_service') { return modal('Room service', '<label>Room number</label><input id="rn" autofocus><button class="btn primary" onclick="POS.openCheck({order_type:\'room_service\',id_room:0,room_num:document.getElementById(\'rn\').value})">Open</button>'); } if (type === 'delivery' || type === 'takeaway' || type === 'bar_tab') { return modal(type.replace('_', ' '), '<label>Name</label><input id="gn"><label>Phone</label><input id="ph">' + (type === 'delivery' ? '<label>Address</label><input id="ad">' : '') + '<button class="btn primary" onclick="POS.openCheck({order_type:\'' + type + '\',guest_name:document.getElementById(\'gn\').value,phone:document.getElementById(\'ph\').value,address:(document.getElementById(\'ad\')||{}).value})">Open</button>'); } openCheck({ order_type: type }); }
  function openCheck(d) { closeModal(); d.id_outlet = S.outlet.id; var p = d.room_num ? api('room', 0, { room_num: d.room_num }).then(function (r) { d.id_room = r.id_room; return api('open', 0, d); }) : api('open', 0, d); p.then(function (c) { S.check = c; order(); }).catch(fail); }
  function load(id) { api('check', id).then(function (c) { S.check = c; S.seat = 1; S.selLine = null; order(); }).catch(fail); }

  /* ---------- order screen ---------- */
  function order() {
    S.view = 'order'; var c = S.check; if (!S.cat && S.menu.categories.length) { S.cat = S.menu.categories[0].id_pulse_pos_category; }
    var where = c.table_code ? 'Table ' + c.table_code : (c.room_num ? 'Room ' + c.room_num + ' ' + (c.guest_name || '') : c.order_type.replace('_', ' ') + (c.guest_name ? ' — ' + c.guest_name : ''));
    var speed = S.menu.speed == 1 || S.outlet.type === 'bar';
    var h = topbar(where, 'floor') + '<div class="order"><div class="check"><div class="check-head"><span>' + esc(c.check_no) + ' · ' + c.covers + ' cov · ' + esc(c.server) + '</span><span>' + esc(c.status) + '</span></div><div class="seatbar">Seat ' + [1, 2, 3, 4, 5, 6].map(function (s) { return '<button class="btn' + (s === S.seat ? ' on' : '') + '" onclick="POS.setSeat(' + s + ')">' + s + '</button>'; }).join('') + '</div><div class="check-lines">';
    c.lines.forEach(function (l) { h += '<div class="line ' + (l.voided == 1 ? 'void' : l.kot_status) + (S.selLine == l.id_pulse_pos_check_line ? ' sel' : '') + '" onclick="POS.selLine(' + l.id_pulse_pos_check_line + ')"><div class="q">' + (l.qty * 1) + '</div><div class="n">' + esc(l.name) + (l.seat > 1 ? ' <small>seat ' + l.seat + '</small>' : '') + (l.modifiers.length ? '<small>' + l.modifiers.map(function (m) { return '+ ' + esc(m.name) + (m.price > 0 ? ' ' + money(m.price * m.qty) : ''); }).join(', ') + '</small>' : '') + (l.note ? '<small>! ' + esc(l.note) + '</small>' : '') + (l.line_discount > 0 ? '<small>disc -' + money(l.line_discount) + '</small>' : '') + (l.comp == 1 ? '<small>COMP</small>' : '') + '</div><div class="p">' + money(l.line_total) + '</div></div>'; });
    h += '</div><div class="totals"><div><span>Subtotal</span><span>' + money(c.subtotal) + '</span></div>' + (c.discount_total > 0 ? '<div><span>Discount</span><span>-' + money(c.discount_total) + '</span></div>' : '') + (c.service_charge > 0 ? '<div><span>Service ' + c.service_charge_pct * 1 + '%</span><span>' + money(c.service_charge) + '</span></div>' : '') + '<div class="big"><span>TOTAL</span><span>' + money(c.total) + '</span></div>' + (c.paid > 0 ? '<div><span>Paid</span><span>' + money(c.paid) + '</span></div>' : '') + '<div><span style="color:#9aa4b1">incl. tax ' + money(c.tax_total) + '</span></div></div>';
    var unsent = c.lines.filter(function (l) { return l.voided == 0 && l.kot_status === 'pending'; }).length;
    h += '<div class="actions"><button class="btn ok" onclick="POS.send()"' + (unsent ? '' : ' disabled') + '>Send' + (unsent ? ' (' + unsent + ')' : '') + '</button><button class="btn" onclick="POS.printCheck()">Print</button><button class="btn primary" onclick="POS.payScreen()">Pay</button>' + (speed ? '<button class="btn ok" onclick="POS.quickCash()">Quick cash</button>' : '') + '<button class="btn" onclick="POS.more()">More ▾</button><button class="btn" onclick="POS.voidLine()">Void item</button><button class="btn" onclick="POS.lineNote()">Note</button><button class="btn" onclick="POS.discountMenu()">Discount</button><button class="btn" onclick="POS.fireMenu()">Fire course</button>' + (c.order_type === 'room_service' && c.status !== 'settled' ? '<button class="btn ok" onclick="POS.delivered()">Delivered</button>' : '') + '</div></div>';
    h += '<div class="menu"><div class="cats">' + (speed ? '<button class="btn' + (S.cat === 'top' ? ' on' : '') + '" style="background:#1e8449" onclick="POS.setCat(\'top\')">⚡ Quick</button>' : '') + S.menu.categories.map(function (k) { return '<button class="btn' + (k.id_pulse_pos_category == S.cat ? ' on' : '') + '" style="background:' + esc(k.colour) + '" onclick="POS.setCat(' + k.id_pulse_pos_category + ')">' + esc(k.name) + '</button>'; }).join('') + '<input id="search" placeholder="Search / PLU / scan" style="flex:1 0 160px;margin:0" oninput="POS.search(this.value)"></div><div class="items" id="items"></div></div></div>';
    render(h); renderItems();
  }
  function renderItems(filter) { var cat = S.menu.categories.filter(function (k) { return k.id_pulse_pos_category == S.cat; })[0]; var list = S.menu.items.filter(function (i) { return filter ? (i.name.toLowerCase().indexOf(filter) > -1 || i.plu === filter) : (S.cat === 'top' ? S.menu.top.indexOf(i.id) > -1 : i.cat == S.cat); }); $('items').innerHTML = list.map(function (i) { return '<div class="item' + (i.avail ? '' : ' na') + '" style="border-left-color:' + esc(cat ? cat.colour : '#2e86c1') + '" onclick="POS.addItem(' + i.id + ')"><div class="nm">' + esc(i.name) + '</div><div class="pr">' + (i.open ? 'open price' : money(i.price)) + (i.left !== null && i.left !== undefined ? ' <span class="left">' + i.left + ' left</span>' : '') + (i.avail ? '' : ' <span class="left">86</span>') + '</div></div>'; }).join('') || '<p style="padding:10px;color:#9aa4b1">No items</p>'; }
  function search(v) { v = v.trim().toLowerCase(); if (!v) { return renderItems(); } var exact = S.menu.items.filter(function (i) { return i.plu === v || i.barcode === v; }); if (exact.length === 1 && v.length >= 4) { $('search').value = ''; return addItem(exact[0].id); } renderItems(v); }
  function addItem(id) {
    var i = S.menu.items.filter(function (x) { return x.id == id; })[0]; if (!i.avail) { return toast(i.name + ' is 86\'d', true); }
    var need = i.mods.length > 0 || i.open;
    if (!need) { return post(id, [], null); }
    var h = ''; if (i.open) { h += '<label>Price</label><input id="op" type="number" inputmode="decimal">'; }
    i.mods.forEach(function (g) { h += '<div style="margin:8px 0"><label>' + esc(g.name) + (g.required == 1 || g.min > 0 ? ' (required)' : '') + (g.max > 1 ? ' · up to ' + g.max : '') + '</label><div>' + (S.menu.modifiers[g.id] || []).map(function (m) { return '<span class="chip" data-g="' + g.id + '" data-max="' + g.max + '" data-id="' + m.id + '" onclick="POS.chip(this)">' + esc(m.name) + (m.price > 0 ? ' +' + money(m.price) : '') + '</span>'; }).join('') + '</div></div>'; });
    h += '<label>Note to kitchen</label><input id="mn"><div class="grid2"><button class="btn primary big" onclick="POS.confirmItem(' + id + ')">Add</button><button class="btn" onclick="POS.closeModal()">Cancel</button></div>';
    modal(i.name, h);
  }
  function chip(el) { var g = el.dataset.g, max = parseInt(el.dataset.max, 10); if (el.classList.contains('on')) { el.classList.remove('on'); return; } var on = document.querySelectorAll('.chip.on[data-g="' + g + '"]'); if (max === 1) { on.forEach(function (x) { x.classList.remove('on'); }); } else if (on.length >= max) { return toast('Max ' + max, true); } el.classList.add('on'); }
  function confirmItem(id) { var mods = Array.prototype.map.call(document.querySelectorAll('.chip.on'), function (x) { return { id: x.dataset.id, qty: 1 }; }); var op = $('op') ? $('op').value : null; post(id, mods, $('mn').value, op); }
  function post(id, mods, note, op) { closeModal(); api('line', S.check.id_pulse_pos_check, { id_item: id, qty: 1, mods: mods, seat: S.seat, note: note || '', open_price: op }).then(function (c) { S.check = c; order(); }).catch(fail); }
  function selLine(id) { S.selLine = S.selLine == id ? null : id; order(); }
  function needLine() { if (!S.selLine) { toast('Select an item on the check first', true); return null; } return S.check.lines.filter(function (l) { return l.id_pulse_pos_check_line == S.selLine; })[0]; }
  function reasons(type) { return S.menu.reasons.filter(function (r) { return r.type === type; }); }
  function reasonPicker(type, cb, needAuth) { modal('Reason', '<div class="grid2">' + reasons(type).map(function (r) { return '<button class="btn" onclick="POS._r(\'' + esc(r.name) + '\')">' + esc(r.name) + '</button>'; }).join('') + '</div><input id="rs" placeholder="Other reason">' + (needAuth ? '<label>Manager PIN (if required)</label><input id="ap" type="password" inputmode="numeric">' : '') + '<button class="btn primary" onclick="POS._r(document.getElementById(\'rs\').value)">OK</button>'); POS._r = function (r) { var ap = $('ap') ? $('ap').value : ''; closeModal(); cb(r, ap); }; }
  function voidLine() { var l = needLine(); if (!l) { return; } reasonPicker('void', function (r, ap) { api('void_line', l.id_pulse_pos_check_line, { reason: r, auth_pin: ap }).then(function (c) { S.check = c; S.selLine = null; order(); toast('Voided'); }).catch(fail); }, l.kot_status !== 'pending'); }
  function lineNote() { var l = needLine(); if (!l) { return; } modal('Note', '<input id="nt" value="' + esc(l.note || '') + '"><button class="btn primary" onclick="POS._n()">Save</button>'); POS._n = function () { var v = $('nt').value; closeModal(); api('update', S.check.id_pulse_pos_check, { note_line: l.id_pulse_pos_check_line, note: v }).then(function () { l.note = v; order(); }).catch(fail); }; }
  function send() { api('send', S.check.id_pulse_pos_check, {}).then(function (c) { S.check = c; order(); toast('Sent to kitchen'); }).catch(fail); }
  function fireMenu() { modal('Fire course', '<div class="grid3">' + [1, 2, 3].map(function (n) { return '<button class="btn big" onclick="POS.fire(' + n + ')">' + ['', 'Starters', 'Mains', 'Desserts'][n] + '</button>'; }).join('') + '</div><p style="color:#9aa4b1">Send with course holds: items of later courses wait until you fire them.</p><button class="btn ok" onclick="POS.sendCourse(1)">Send &amp; hold later courses</button>'); }
  function fire(n) { closeModal(); api('fire', S.check.id_pulse_pos_check, { course: n }).then(function (c) { S.check = c; order(); toast('Course ' + n + ' fired'); }).catch(fail); }
  function sendCourse(n) { closeModal(); api('send', S.check.id_pulse_pos_check, { course: n }).then(function (c) { S.check = c; order(); toast('Sent — later courses held'); }).catch(fail); }
  function printCheck() { api('print', S.check.id_pulse_pos_check).then(function (r) { S.check = r.check; modal('Check ' + S.check.check_no, '<pre class="receipt">' + esc(r.text) + '</pre><div class="grid2"><button class="btn primary" onclick="window.print()">Print</button><button class="btn" onclick="POS.closeModal();POS.order()">Close</button></div>'); }).catch(fail); }
  function discountMenu() { var l = S.selLine ? needLine() : null; modal('Discount' + (l ? ' — ' + l.name : ' — whole check'), '<div class="grid2">' + S.menu.discounts.filter(function (d) { return l ? d.scope === 'item' || true : true; }).map(function (d) { return '<button class="btn" onclick="POS.applyDisc(' + d.id_pulse_pos_discount + ',' + (d.value == 0 ? 1 : 0) + ')">' + esc(d.name) + (d.requires_manager == 1 ? ' 🔒' : '') + '</button>'; }).join('') + '</div><hr><button class="btn warn" onclick="POS.compMenu()">Complimentary (100%)</button>'); }
  function applyDisc(id, custom) { var l = S.selLine; reasonPicker('discount', function (r, ap) { var b = { id_discount: id, reason: r, auth_pin: ap, id_line: l }; if (custom) { b.value = prompt('Discount amount'); } api('discount', S.check.id_pulse_pos_check, b).then(function (c) { S.check = c; order(); toast('Discount applied'); }).catch(fail); }, true); }
  function compMenu() { var l = S.selLine; reasonPicker('comp', function (r, ap) { api('comp', S.check.id_pulse_pos_check, { reason: r, auth_pin: ap, id_line: l }).then(function (c) { S.check = c; order(); toast('Comped'); }).catch(fail); }, true); }
  function more() { modal('More', '<div class="grid2"><button class="btn" onclick="POS.covers()">Covers / name</button><button class="btn" onclick="POS.roomAttach()">Attach room</button><button class="btn" onclick="POS.transferTable()">Transfer table</button><button class="btn" onclick="POS.transferServer()">Transfer server</button><button class="btn" onclick="POS.splitMenu()">Split check</button><button class="btn" onclick="POS.mergeMenu()">Merge check</button><button class="btn" onclick="POS.seatLine()">Move item to seat</button><button class="btn" onclick="POS.eightysix()">86 / availability</button><button class="btn" onclick="POS.allergy()">Allergy / dietary</button><button class="btn" onclick="POS.taxExempt()">Tax exempt</button><button class="btn" onclick="POS.guestSearch()">Find guest by name</button><button class="btn" onclick="POS.preauth()">Card pre-auth (tab)</button><button class="btn danger" onclick="POS.voidCheck()">Void check</button><button class="btn" onclick="POS.reprintKot()">Reprint / resend KOT</button></div>'); }
  function allergy() { modal('Allergy / dietary note (prints on every KOT)', '<input id="al" value="' + esc(S.check.allergy_note || '') + '" placeholder="e.g. NUT ALLERGY seat 2"><button class="btn primary" onclick="POS.upd({allergy_note:document.getElementById(\'al\').value})">Save</button>'); }
  function taxExempt() { modal('Tax exempt', '<p>Current: ' + (S.check.tax_exempt == 1 ? 'EXEMPT' : 'taxable') + '</p><label>Exemption reference (diplomatic / NGO / gov)</label><input id="txr" value="' + esc(S.check.tax_exempt_ref || '') + '"><div class="grid2"><button class="btn warn" onclick="POS.upd({tax_exempt:1,tax_exempt_ref:document.getElementById(\'txr\').value})">Set exempt 🔒</button><button class="btn" onclick="POS.upd({tax_exempt:0})">Make taxable</button></div>'); }
  function guestSearch() { modal('Find in-house guest', '<input id="gq" placeholder="Surname" oninput="POS.guestList(this.value)"><div id="gl"></div>'); }
  function guestList(v) { if (v.length < 2) { return; } api('guests', 0, { name: v }).then(function (gs) { $('gl').innerHTML = gs.map(function (g) { return '<div class="row" onclick="POS.upd({room_num:\'' + esc(g.room_num) + '\'})"><div class="grow">' + esc(g.guest) + (g.vip_level > 0 ? ' ★' : '') + '</div><div>Rm ' + esc(g.room_num) + '</div></div>'; }).join('') || '<p>No match</p>'; }).catch(fail); }
  function preauth() { modal('Card pre-authorisation for tab', '<p>Take a pre-auth on the card terminal, then record it here. The amount is released or captured at settlement.</p><label>Auth reference</label><input id="par"><label>Amount held</label><input id="paa" type="number"><button class="btn primary" onclick="POS.upd({preauth_ref:document.getElementById(\'par\').value,preauth_amount:document.getElementById(\'paa\').value})">Save</button>'); }
  function covers() { modal('Covers & name', '<label>Covers</label><input id="cv" type="number" value="' + S.check.covers + '"><label>Guest name</label><input id="gn" value="' + esc(S.check.guest_name || '') + '"><button class="btn primary" onclick="POS.upd({covers:document.getElementById(\'cv\').value,guest_name:document.getElementById(\'gn\').value})">Save</button>'); }
  function roomAttach() { modal('Attach to room', '<label>Room number</label><input id="rn"><div id="rg"></div><button class="btn" onclick="POS.roomLook()">Look up</button><button class="btn primary" onclick="POS.upd({room_num:document.getElementById(\'rn\').value})">Attach</button>'); }
  function roomLook() { api('room', 0, { room_num: $('rn').value }).then(function (r) { $('rg').innerHTML = '<p>Guest: <b>' + esc(r.guest_masked || r.guest) + '</b>' + (r.vip_level > 0 ? ' ★VIP' : '') + '</p>'; }).catch(fail); }
  function upd(d) { closeModal(); api('update', S.check.id_pulse_pos_check, d).then(function (c) { S.check = c; order(); }).catch(fail); }
  function transferTable() { var free = S.tables.filter(function (t) { return !t.id_pulse_pos_check && t.status !== 'blocked'; }); modal('Transfer to table', '<div class="grid4">' + free.map(function (t) { return '<button class="btn" onclick="POS.doTransfer({id_table:' + t.id_pulse_pos_table + '})">' + esc(t.code) + '</button>'; }).join('') + '</div>'); }
  function transferServer() { api('clock').then(function (staff) { modal('Transfer to server', '<div class="grid2">' + staff.map(function (s) { return '<button class="btn" onclick="POS.doTransfer({id_server:' + s.id_employee + '})">' + esc(s.name) + '</button>'; }).join('') + '</div>'); }).catch(fail); }
  function doTransfer(d) { closeModal(); api('transfer', S.check.id_pulse_pos_check, d).then(function (c) { S.check = c; order(); toast('Transferred'); }).catch(fail); }
  function splitMenu() { modal('Split check', '<div class="grid3"><button class="btn big" onclick="POS.doSplit({seat:' + S.seat + '})">By seat ' + S.seat + '</button><button class="btn big" onclick="POS.doSplit({lines:[' + (S.selLine || 0) + ']})">Selected item</button><button class="btn big" onclick="POS.doSplit({ways:parseInt(prompt(\'Split into how many?\',\'2\'),10)})">Equal ways</button><button class="btn big" onclick="POS.doSplit({amount:parseFloat(prompt(\'Amount to move to a new check\'))})">Fixed amount</button></div>'); }
  function doSplit(d) { closeModal(); api('split', S.check.id_pulse_pos_check, d).then(function (r) { S.check = r.check; order(); toast('Split — new check(s) created'); }).catch(fail); }
  function mergeMenu() { api('checks', S.outlet.id).then(function (list) { modal('Merge another check into this one', '<div class="list">' + list.filter(function (c) { return c.id != S.check.id_pulse_pos_check; }).map(function (c) { return '<div class="row" onclick="POS.doMerge(' + c.id + ')"><div class="grow">' + esc(c.table_code || c.order_type) + ' ' + esc(c.check_no) + '</div><div>' + money(c.total) + '</div></div>'; }).join('') + '</div>'); }); }
  function doMerge(id) { closeModal(); api('merge', S.check.id_pulse_pos_check, { id_from: id }).then(function (c) { S.check = c; order(); toast('Merged'); }).catch(fail); }
  function seatLine() { var l = needLine(); if (!l) { return; } closeModal(); api('update', S.check.id_pulse_pos_check, { seat_line: l.id_pulse_pos_check_line, seat: S.seat }).then(function (c) { S.check = c; order(); }).catch(fail); }
  function eightysix() { modal('86 / availability', '<input id="q86" placeholder="Search item" oninput="POS.list86(this.value)"><div id="l86"></div>'); }
  function list86(v) { v = v.toLowerCase(); $('l86').innerHTML = S.menu.items.filter(function (i) { return i.name.toLowerCase().indexOf(v) > -1; }).slice(0, 12).map(function (i) { return '<div class="row"><div class="grow">' + esc(i.name) + '</div><button class="btn ' + (i.avail ? 'danger' : 'ok') + '" onclick="POS.set86(' + i.id + ',' + (i.avail ? 0 : 1) + ')">' + (i.avail ? '86 it' : 'Available') + '</button><input style="width:80px;margin:0 6px" placeholder="count" id="c86_' + i.id + '"></div>'; }).join(''); }
  function set86(id, av) { api('eightysix', id, { available: av, count: $('c86_' + id).value }).then(function () { return api('menu', S.outlet.id); }).then(function (m) { S.menu = m; closeModal(); order(); toast('Updated'); }).catch(fail); }
  function voidCheck() { reasonPicker('void', function (r, ap) { api('void_check', S.check.id_pulse_pos_check, { reason: r, auth_pin: ap }).then(function () { toast('Check voided'); floor(); }).catch(fail); }, true); }
  function reprintKot() { closeModal(); api('send', S.check.id_pulse_pos_check, {}).then(function (c) { S.check = c; toast('Pending items sent'); order(); }).catch(fail); }
  function quickCash() { var due = Math.round((S.check.total - S.check.paid) * 100) / 100; api('pay', S.check.id_pulse_pos_check, { method: 'cash', amount: due, tendered: due }).then(function (r) { S.check = r.check; toast('Settled cash ' + money(due)); floor(); }).catch(fail); }
  function delivered() { api('delivered', S.check.id_pulse_pos_check).then(function (c) { S.check = c; order(); toast('Marked delivered'); }).catch(fail); }
  function setSeat(s) { S.seat = s; order(); } function setCat(c) { S.cat = c; renderItems(); } function section(s) { S.section = s; floor(); }

  /* ---------- payment ---------- */
  var pay = { method: null, amt: '' };
  function payScreen() {
    var c = S.check; var due = Math.round((c.total - c.paid) * 100) / 100; if (due <= 0 && c.total > 0) { return toast('Nothing due', true); }
    if (c.lines.some(function (l) { return l.voided == 0 && l.kot_status === 'pending'; })) { toast('Unsent items will be sent on settlement'); }
    pay = { method: POS_CFG.defaultTender || 'cash', amt: String(due) };
    var tenders = [['cash', 'Cash'], ['card', 'Card / POS'], ['transfer', 'Transfer'], ['mobile_money', 'Mobile money'], ['room', 'Room charge'], ['city_ledger', 'Company'], ['voucher', 'Voucher'], ['foreign', 'Foreign cash'], ['package', 'Meal plan'], ['comp', 'Comp 🔒']].filter(function (t) { return (t[0] !== 'room' && t[0] !== 'package') || S.outlet.allow_room_charge == 1; });
    modal('Pay — due ' + money(due), '<div class="grid2"><div><div class="amount" id="pamt">' + esc(pay.amt) + '</div><div class="numpad">' + [7, 8, 9, 4, 5, 6, 1, 2, 3, '.', 0, '⌫'].map(function (k) { return '<button class="btn" onclick="POS.pk(\'' + k + '\')">' + k + '</button>'; }).join('') + '</div><div class="grid3" style="margin-top:6px">' + [due, Math.ceil(due / 1000) * 1000, Math.ceil(due / 5000) * 5000].map(function (v) { return '<button class="btn" onclick="POS.pk(\'=' + v + '\')">' + money(v) + '</button>'; }).join('') + '</div></div><div><div class="tenders">' + tenders.map(function (t) { return '<button class="btn' + (t[0] === pay.method ? ' primary' : '') + '" data-m="' + t[0] + '" onclick="POS.setMethod(\'' + t[0] + '\')">' + t[1] + '</button>'; }).join('') + '</div><div id="pextra" style="margin-top:8px"></div>' + (POS_CFG.tipOnCard ? '<label>Tip</label><input id="ptip" type="number" inputmode="decimal" placeholder="0">' : '') + '<label>Reference</label><input id="pref" placeholder="Card slip / transfer ref"></div></div><div class="paylist">' + c.payments.map(function (p) { return '<div class="row"><div class="grow">' + esc(p.method) + ' ' + esc(p.reference || '') + '</div><div>' + money(p.amount) + '</div></div>'; }).join('') + '</div><div class="grid2" style="margin-top:8px"><button class="btn ok big" onclick="POS.doPay()">Take payment</button><button class="btn" onclick="POS.closeModal()">Cancel</button></div>');
    setMethod(pay.method);
  }
  function pk(k) { if (k[0] === '=') { pay.amt = k.slice(1); } else if (k === '⌫') { pay.amt = pay.amt.slice(0, -1); } else { pay.amt = (pay.amt === '0' ? '' : pay.amt) + k; } $('pamt').textContent = pay.amt || '0'; }
  function setMethod(m) { pay.method = m; document.querySelectorAll('.tenders .btn').forEach(function (b) { b.className = 'btn' + (b.dataset.m === m ? ' primary' : ''); }); var x = $('pextra'); x.innerHTML = '';
    if (m === 'room') { x.innerHTML = '<label>Room number</label><input id="prm" value="' + esc(S.check.room_num || '') + '" onchange="POS.roomVerify()"><div id="prg"></div>' + (POS_CFG.roomGuestCheck ? '<label>Guest surname (verify)</label><input id="pgc">' : '') + '<label>Guest signature</label><canvas id="sig" width="320" height="110" style="background:#fff;border-radius:6px;touch-action:none;width:100%"></canvas><button class="btn ghost" onclick="POS.sigClear()">clear</button>'; sigInit(); if (S.check.room_num) { roomVerify(); } }
    if (m === 'package') { x.innerHTML = '<label>Room number</label><input id="prm" value="' + esc(S.check.room_num || '') + '" onchange="POS.allowanceLook()"><select id="pmeal"><option value="">meal: auto</option><option value="breakfast">breakfast</option><option value="lunch">lunch</option><option value="dinner">dinner</option></select><div id="pal"></div>'; if (S.check.room_num) { allowanceLook(); } }
    if (m === 'city_ledger') { api('companies').then(function (cs) { x.innerHTML = '<label>Company</label><select id="pco">' + cs.map(function (c) { return '<option value="' + c.id + '">' + esc(c.name) + ' (bal ' + money(c.ledger_balance) + ')</option>'; }).join('') + '</select>'; }); }
    if (m === 'voucher') { x.innerHTML = '<label>Voucher code</label><input id="pvc">'; }
    if (m === 'foreign') { x.innerHTML = '<label>Currency</label><select id="pfc">' + (POS_CFG.currencies || []).map(function (c) { return '<option value="' + c.iso_code + '" data-rate="' + c.conversion_rate + '">' + c.iso_code + '</option>'; }).join('') + '</select><label>Foreign amount</label><input id="pfa" type="number"><label>Rate (1 foreign = local)</label><input id="pfr" type="number" step="0.0001">'; }
    if (m === 'comp') { x.innerHTML = '<label>Manager PIN</label><input id="pap" type="password" inputmode="numeric"><label>Reason</label><input id="prs">'; }
  }
  var sig = { d: false, used: false };
  function sigInit() { var c = $('sig'); if (!c) { return; } var ctx = c.getContext('2d'); ctx.lineWidth = 2; ctx.lineCap = 'round'; ctx.strokeStyle = '#111'; function pos(e) { var r = c.getBoundingClientRect(); var p = e.touches ? e.touches[0] : e; return [(p.clientX - r.left) * c.width / r.width, (p.clientY - r.top) * c.height / r.height]; } c.onpointerdown = function (e) { sig.d = true; sig.used = true; var p = pos(e); ctx.beginPath(); ctx.moveTo(p[0], p[1]); }; c.onpointermove = function (e) { if (!sig.d) { return; } var p = pos(e); ctx.lineTo(p[0], p[1]); ctx.stroke(); e.preventDefault(); }; c.onpointerup = c.onpointerleave = function () { sig.d = false; }; }
  function sigClear() { var c = $('sig'); if (c) { c.getContext('2d').clearRect(0, 0, c.width, c.height); sig.used = false; } }
  function allowanceLook() { api('allowance', 0, { room_num: $('prm').value, meal: $('pmeal').value, id_check: S.check.id_pulse_pos_check }).then(function (r) { var a = r.allowance; $('pal').innerHTML = '<p>' + esc(r.room.guest) + ' — ' + (a ? a.plan + ' ' + a.meal + ': ' + money(a.remaining) + ' remaining of ' + money(a.total) : '<span style="color:#e74c3c">no meal plan / allowance for this meal</span>') + '</p>'; if (a) { pay.amt = String(Math.min(a.remaining, S.check.total - S.check.paid)); $('pamt').textContent = pay.amt; } }).catch(fail); }
  function roomVerify() { api('room', 0, { room_num: $('prm').value }).then(function (r) { $('prg').innerHTML = '<p>Guest: <b>' + esc(r.guest_masked || r.guest) + '</b>' + (r.vip_level > 0 ? ' ★' : '') + '</p>'; }).catch(function (e) { $('prg').innerHTML = '<p style="color:#e74c3c">' + esc(e.message) + '</p>'; }); }
  function doPay() {
    var b = { method: pay.method, amount: parseFloat(pay.amt || '0'), tip: $('ptip') ? parseFloat($('ptip').value || '0') : 0, reference: $('pref').value };
    if (pay.method === 'cash') { b.tendered = b.amount; b.amount = Math.min(b.amount, S.check.total - S.check.paid); }
    if (pay.method === 'room') { b.room_num = $('prm').value; b.guest_check = $('pgc') ? $('pgc').value : ''; if (sig.used && $('sig')) { b.signature = $('sig').toDataURL('image/png'); } }
    if (pay.method === 'package') { b.room_num = $('prm').value; b.meal = $('pmeal').value; }
    if (pay.method === 'city_ledger') { b.id_company = $('pco').value; } if (pay.method === 'voucher') { b.code = $('pvc').value; }
    if (pay.method === 'foreign') { b.currency_iso = $('pfc').value; b.foreign_amount = parseFloat($('pfa').value); b.exchange_rate = parseFloat($('pfr').value) || 1 / parseFloat($('pfc').selectedOptions[0].dataset.rate); }
    if (pay.method === 'comp') { b.auth_pin = $('pap').value; b.reason = $('prs').value; }
    api('pay', S.check.id_pulse_pos_check, b).then(function (r) { S.check = r.check; if (r.settled) { modal('Settled' + (r.change > 0 ? ' — change ' + money(r.change) : ''), '<pre class="receipt">' + esc(r.receipt) + '</pre><div class="grid3"><button class="btn primary" onclick="window.print()">Print receipt</button><button class="btn" onclick="POS.closeModal();POS.floor()">Done</button><button class="btn ghost" onclick="POS.closeModal();POS.floor()">No receipt</button></div>'); } else { toast('Paid ' + money(b.amount) + ' — due ' + money(r.due)); payScreen(); } }).catch(fail);
  }

  /* ---------- cashier / closed checks ---------- */
  function cashier() { api('session', S.outlet.id).then(function (s) { if (s) { return api('x_report', s.id_pulse_pos_session); } return null; }).then(function (s) { if (!s) { return modal('Open cashier session', '<label>Opening float</label><input id="fl" type="number" value="0"><button class="btn primary" onclick="POS.sessOpen()">Open session</button>'); } var h = '<p>' + esc(s.outlet) + ' · ' + esc(s.cashier) + ' · open since ' + esc(s.date_open) + '</p>' + (s.blind ? '<p style="color:#f39c12">Blind close: count your drawer and enter the amount — expected cash is shown to managers only.</p>' : '') + '<table style="width:100%;font-size:14px">' + (s.payments || []).map(function (p) { return '<tr><td>' + esc(p.method) + '</td><td>' + p.n + '</td><td style="text-align:right">' + money(p.total) + '</td></tr>'; }).join('') + '<tr><td>Checks / covers</td><td>' + s.checks.n + ' / ' + s.checks.covers + '</td><td style="text-align:right">' + money(s.checks.sales) + '</td></tr><tr><td>Discounts</td><td></td><td style="text-align:right">' + money(s.checks.discounts) + '</td></tr><tr><td>Voids</td><td>' + s.voids.n + '</td><td style="text-align:right">' + money(s.voids.total) + '</td></tr>' + (s.blind ? '' : '<tr><td>Float + cash − drops − paid-outs</td><td></td><td style="text-align:right"><b>' + money(s.expected_cash_calc) + '</b></td></tr>') + '</table><div class="grid3" style="margin-top:8px"><button class="btn" onclick="POS.sessMove(' + s.id_pulse_pos_session + ',\'drop\')">Drop</button><button class="btn" onclick="POS.sessMove(' + s.id_pulse_pos_session + ',\'paid_out\')">Paid out</button><button class="btn" onclick="POS.sessMove(' + s.id_pulse_pos_session + ',\'float_add\')">Add float</button><button class="btn" onclick="POS.noSale()">No sale (open drawer)</button><button class="btn" onclick="window.print()">Print X</button><button class="btn danger" onclick="POS.sessClose(' + s.id_pulse_pos_session + ')">Close (Z)</button></div>'; modal('Cashier — X report', h); }).catch(fail); }
  function sessOpen() { api('session_open', S.outlet.id, { float: parseFloat($('fl').value || '0') }).then(function () { closeModal(); toast('Session open'); cashier(); }).catch(fail); }
  function sessMove(id, type) { var a = prompt(type.replace('_', ' ') + ' amount'); if (!a) { return; } var r = prompt('Reason / reference') || ''; api('session_move', id, { type: type, amount: parseFloat(a), reason: r }).then(function () { toast('Recorded'); cashier(); }).catch(fail); }
  function sessClose(id) { var c = prompt('Cash counted in drawer'); if (c === null) { return; } api('session_close', id, { counted: parseFloat(c), note: prompt('Note') || '' }).then(function (r) { closeModal(); toast('Session closed — Z' + r.z); S.cashSession = null; }).catch(fail); }
  function noSale() { api('drawer', 0, {}).then(function () { toast('Drawer opened'); }).catch(fail); }
  function closedChecks() { api('closed', S.outlet.id).then(function (list) { modal('Closed checks today', '<div class="list">' + list.map(function (c) { return '<div class="row"><div class="grow"><b>' + esc(c.check_no) + '</b> ' + esc(c.table_code || '') + ' · ' + esc(c.server) + '<br><small>' + esc(c.status) + ' ' + esc(c.date_settled || '') + '</small></div><div>' + money(c.total) + '</div><button class="btn" onclick="POS.reprint(' + c.id + ')">Reprint</button><button class="btn warn" onclick="POS.reopen(' + c.id + ')">Reopen 🔒</button></div>'; }).join('') + '</div>'); }).catch(fail); }
  function reprint(id) { api('check', id).then(function (c) { S.check = c; return api('print', id); }).then(function (r) { modal('Receipt', '<pre class="receipt">' + esc(r.text) + '</pre><button class="btn primary" onclick="window.print()">Print</button>'); }).catch(fail); }
  function reopen(id) { var ap = prompt('Manager PIN'); api('reopen', id, { auth_pin: ap }).then(function (c) { S.check = c; closeModal(); order(); toast('Reopened — payments reversed'); }).catch(fail); }

  login();
  return { login: login, logout: logout, floor: floor, tapTable: tapTable, seatTable: seatTable, newCheck: newCheck, openCheck: openCheck, load: load, order: order, addItem: addItem, chip: chip, confirmItem: confirmItem, selLine: selLine, voidLine: voidLine, lineNote: lineNote, send: send, fireMenu: fireMenu, fire: fire, sendCourse: sendCourse, printCheck: printCheck, discountMenu: discountMenu, applyDisc: applyDisc, compMenu: compMenu, more: more, covers: covers, roomAttach: roomAttach, roomLook: roomLook, upd: upd, transferTable: transferTable, transferServer: transferServer, doTransfer: doTransfer, splitMenu: splitMenu, doSplit: doSplit, mergeMenu: mergeMenu, doMerge: doMerge, seatLine: seatLine, eightysix: eightysix, list86: list86, set86: set86, voidCheck: voidCheck, reprintKot: reprintKot, setSeat: setSeat, setCat: setCat, section: section, search: search, payScreen: payScreen, pk: pk, setMethod: setMethod, roomVerify: roomVerify, doPay: doPay, cashier: cashier, sessOpen: sessOpen, sessMove: sessMove, sessClose: sessClose, noSale: noSale, closedChecks: closedChecks, reprint: reprint, reopen: reopen, closeModal: closeModal, quickCash: quickCash, delivered: delivered, allergy: allergy, taxExempt: taxExempt, guestSearch: guestSearch, guestList: guestList, preauth: preauth, sigClear: sigClear, allowanceLook: allowanceLook };
})();
