<div class="pulse-inv"><div class="panel"><h3>{if $item}Edit item — {$item.name}{else}New item{/if}</h3>
<form method="post" class="form-horizontal"><input type="hidden" name="id_item" value="{$item.id_pulse_inv_item|default:''}"><div class="row"><div class="col-md-6">
<div class="form-group"><label class="col-sm-3">SKU / name</label><div class="col-sm-3"><input name="sku" class="form-control" value="{$item.sku|default:''}" required></div><div class="col-sm-6"><input name="name" class="form-control" value="{$item.name|default:''}" required></div></div>
<div class="form-group"><label class="col-sm-3">Category</label><div class="col-sm-9"><select name="id_category" class="form-control">{foreach $categories as $c}<option value="{$c.id_pulse_inv_category}" {if $item && $item.id_pulse_inv_category==$c.id_pulse_inv_category}selected{/if}>{$c.name} ({$c.group_name|replace:'_':' '})</option>{/foreach}</select></div></div>
<div class="form-group"><label class="col-sm-3">Stock unit / purchase unit / factor</label><div class="col-sm-3"><select name="unit" class="form-control">{foreach $units as $u}<option value="{$u.code}" {if $item && $item.unit==$u.code}selected{/if}>{$u.code}</option>{/foreach}</select></div><div class="col-sm-3"><select name="purchase_unit" class="form-control"><option value="">same</option>{foreach $units as $u}<option value="{$u.code}" {if $item && $item.purchase_unit==$u.code}selected{/if}>{$u.code}</option>{/foreach}</select></div><div class="col-sm-3"><input name="purchase_factor" class="form-control" value="{$item.purchase_factor|default:1}" title="1 purchase unit = N stock units"></div></div>
<div class="form-group"><label class="col-sm-3">Reorder level / qty / max / lead days</label><div class="col-sm-2"><input name="reorder_level" class="form-control" value="{$item.reorder_level|default:0}"></div><div class="col-sm-2"><input name="reorder_qty" class="form-control" value="{$item.reorder_qty|default:0}"></div><div class="col-sm-2"><input name="max_level" class="form-control" value="{$item.max_level|default:''}"></div><div class="col-sm-2"><input name="lead_days" class="form-control" value="{$item.lead_days|default:3}"></div></div>
<div class="form-group"><label class="col-sm-3">Sale price (minibar) / barcode</label><div class="col-sm-4"><input name="sale_price" class="form-control" value="{$item.sale_price|default:''}"></div><div class="col-sm-5"><input name="barcode" class="form-control" value="{$item.barcode|default:''}"></div></div>
<div class="form-group"><label class="col-sm-3">Flags</label><div class="col-sm-9"><label><input type="checkbox" name="track_expiry" value="1" {if $item && $item.track_expiry}checked{/if}> track expiry</label> &nbsp; <label><input type="checkbox" name="track_batch" value="1" {if $item && $item.track_batch}checked{/if}> track batch</label> &nbsp; <label><input type="checkbox" name="active" value="1" {if !$item || $item.active}checked{/if}> active</label> &nbsp; preferred supplier <select name="id_supplier_pref" class="input-sm"><option value="">—</option>{foreach $suppliers as $s}<option value="{$s.id_pulse_inv_supplier}" {if $item && $item.id_supplier_pref==$s.id_pulse_inv_supplier}selected{/if}>{$s.name}</option>{/foreach}</select></div></div>
{if !$item}<div class="form-group"><label class="col-sm-3">Opening stock (new items)</label><div class="col-sm-3"><input name="opening_qty" class="form-control" placeholder="qty"></div><div class="col-sm-3"><input name="avg_cost" class="form-control" placeholder="unit cost"></div><div class="col-sm-3"><select name="opening_store" class="form-control">{foreach $stores as $s}<option value="{$s.id_pulse_inv_store}">{$s.code}</option>{/foreach}</select></div></div>{/if}
<div class="form-group"><label class="col-sm-3">Note</label><div class="col-sm-9"><input name="note" class="form-control" value="{$item.note|default:''}"></div></div></div>
<div class="col-md-6">{if $item}<p>Avg cost <strong>{$item.avg_cost|number_format:2}</strong> · last cost {$item.last_cost|number_format:2}{if $item.link_type} · linked to {$item.link_type|replace:'_':' '} #{$item.link_id}{/if}</p><h4>Price history</h4><table class="table table-condensed"><tbody>{foreach $price_history as $p}<tr><td>{$p.business_date}</td><td>{$p.supplier}</td><td>{$p.qty}</td><td class="text-right">{$p.unit_price}</td></tr>{foreachelse}<tr><td><em>No receipts yet</em></td></tr>{/foreach}</tbody></table>{/if}<button name="saveItem" class="btn btn-primary pull-right">Save item</button></div></div></form></div>
<div class="panel"><h3>Items</h3><table class="table table-condensed"><thead><tr><th>SKU</th><th>Item</th><th>Category</th><th>Unit</th><th>Purchase</th><th>Avg cost</th><th>Reorder</th><th>Expiry</th><th>Active</th></tr></thead><tbody>{foreach $items as $i}<tr><td>{$i.sku}</td><td><a href="{$self_url}&id_item={$i.id_pulse_inv_item}">{$i.name}</a></td><td>{$i.category}</td><td>{$i.unit}</td><td>{$i.purchase_unit} ×{$i.purchase_factor}</td><td>{$i.avg_cost|number_format:2}</td><td>{$i.reorder_level}</td><td>{$i.track_expiry}</td><td>{$i.active}</td></tr>{/foreach}</tbody></table>
<h4>Import items from CSV</h4><p>Columns: <code>sku, name, category_code, unit, purchase_unit, purchase_factor, unit_cost, reorder_level, reorder_qty</code></p><form method="post" enctype="multipart/form-data"><input type="file" name="csv" accept=".csv"> <button name="importCsv" class="btn btn-default btn-sm">Import</button></form></div>
<div class="row"><div class="col-md-4"><div class="panel"><h3>Stores</h3><table class="table table-condensed"><tbody>{foreach $stores as $s}<tr><td>{$s.code}</td><td>{$s.name}</td><td>{$s.type|replace:'_':' '}</td><td>{$s.department}</td><td>{$s.keeper}</td></tr>{/foreach}</tbody></table><form method="post"><input type="hidden" name="id_store"><input name="scode" class="form-control" placeholder="CODE" required><input name="sname" class="form-control" placeholder="Name" required><select name="stype" class="form-control">{foreach ['central','kitchen','bar','housekeeping','floor_pantry','minibar','front_office','engineering','laundry','other'] as $t}<option>{$t}</option>{/foreach}</select><select name="sdept" class="form-control">{foreach ['general','fnb','housekeeping','rooms','admin','maintenance','laundry'] as $d}<option>{$d}</option>{/foreach}</select><select name="keeper" class="form-control"><option value="">keeper —</option>{foreach $employees as $e}<option value="{$e.id_employee}">{$e.firstname} {$e.lastname}</option>{/foreach}</select><label><input type="checkbox" name="allow_negative" value="1"> allow negative</label> <button name="saveStore" class="btn btn-default btn-sm">Save store</button></form></div></div>
<div class="col-md-4"><div class="panel"><h3>Suppliers</h3><table class="table table-condensed"><tbody>{foreach $suppliers as $s}<tr><td>{$s.name}</td><td>{$s.phone}</td><td>{$s.payment_terms_days}d</td></tr>{/foreach}</tbody></table><form method="post"><input type="hidden" name="id_supplier"><input name="supname" class="form-control" placeholder="Supplier" required><input name="contact" class="form-control" placeholder="Contact"><input name="phone" class="form-control" placeholder="Phone"><input name="email" class="form-control" placeholder="Email"><input name="address" class="form-control" placeholder="Address"><input name="tin" class="form-control" placeholder="TIN"><input name="terms" class="form-control" placeholder="Payment terms (days)"><input name="supcats" class="form-control" placeholder="Supplies (e.g. food, beverage)"><button name="saveSupplier" class="btn btn-default btn-sm">Save supplier</button></form></div></div>
<div class="col-md-4"><div class="panel"><h3>Categories &amp; units</h3>{foreach $categories as $c}<span class="label label-default">{$c.code} {$c.name}{if $c.expense_code} → {$c.expense_code}{/if}</span> {/foreach}<form method="post" class="form-inline" style="margin-top:6px"><input name="ccode" class="form-control input-sm" placeholder="CODE" style="width:70px"> <input name="cname" class="form-control input-sm" placeholder="Name"> <select name="cgroup" class="form-control input-sm">{foreach ['food','beverage','liquor','guest_amenity','cleaning','linen','minibar','stationery','printing','keycard','engineering','uniform','other'] as $g}<option>{$g}</option>{/foreach}</select> <select name="cexp" class="form-control input-sm"><option value="">expense code</option>{foreach $expense_codes as $x}<option value="{$x.code}">{$x.code}</option>{/foreach}</select> <button name="saveCategory" class="btn btn-default btn-sm">Add</button></form>
<hr>{foreach $units as $u}<span class="label label-default">{$u.code} = {$u.factor} {$u.base}</span> {/foreach}<form method="post" class="form-inline" style="margin-top:6px"><input name="ucode" class="form-control input-sm" placeholder="code" style="width:70px"> <input name="uname" class="form-control input-sm" placeholder="name"> <input name="ubase" class="form-control input-sm" placeholder="base" style="width:70px"> <input name="ufactor" class="form-control input-sm" placeholder="factor" style="width:70px"> <button name="saveUnit" class="btn btn-default btn-sm">Add unit</button></form>
<p class="help-block" style="margin-top:10px">Daily cron (if Front Desk night audit is not running): <code>{$cron_url}</code></p></div></div></div></div>
