<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Kitchen Display</title><link rel="stylesheet" href="{$pos_css}"></head>
<body class="kds"><div class="kds-head"><strong>KITCHEN DISPLAY</strong> <select id="station" onchange="load()"><option value="">All stations</option>{foreach $stations as $s}<option value="{$s.id_pulse_pos_station}" {if $station==$s.code}selected{/if}>{$s.name}</option>{/foreach}</select> <span id="kds-clock"></span> <span id="kds-count"></span><input id="kds-token" placeholder="API token (scope kds)" style="float:right;width:260px"></div>
<div id="kds-grid" class="kds-grid"></div>
<script>
var API="{$pos_api nofilter}",LATE={$late_min};function tok(){ return localStorage.getItem('pulse_kds_token')||''; }
document.getElementById('kds-token').value=tok();document.getElementById('kds-token').onchange=function(){ localStorage.setItem('pulse_kds_token',this.value); load(); };
function call(res,id,body){ return fetch(API+(API.indexOf('?')>-1?'&':'?')+'resource='+res+(id?'&id='+id:''),{ method:body?'POST':'GET',headers:{'Authorization':'Bearer '+tok(),'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined }).then(function(r){ return r.json(); }); }
function esc(s){ return String(s==null?'':s).replace(/[&<>]/g,function(c){ return {'&':'&amp;','<':'&lt;','>':'&gt;'}[c]; }); }
function load(){ var st=document.getElementById('station').value; call('kds',st).then(function(r){ if(!r.ok){ document.getElementById('kds-grid').innerHTML='<p class="err">'+esc(r.error)+'</p>'; return; } var g=document.getElementById('kds-grid'); g.innerHTML=''; document.getElementById('kds-count').textContent=r.data.length+' ticket(s)'; r.data.forEach(function(t){ var d=document.createElement('div'); d.className='ticket'+(t.late||t.age>=LATE?' late':'')+(t.age>=LATE*2?' vlate':''); var h='<div class="t-head"><span>'+esc(t.where)+'</span><span>'+t.age+'m</span></div><div class="t-sub">'+esc(t.check)+' · '+esc(t.kot)+' · '+t.covers+' cov</div>'; t.lines.forEach(function(l){ h+='<div class="t-line '+l.kot_status+'" onclick="bump('+l.id_pulse_pos_check_line+',\''+(l.kot_status==='fired'?'preparing':(l.kot_status==='preparing'?'ready':'served'))+'\')"><b>'+(l.qty*1)+'</b> '+esc(l.name)+(l.seat>1?' <small>s'+l.seat+'</small>':'')+(l.station?' <small>'+esc(l.station)+'</small>':'')+'<div class="t-mods">'+(l.modifiers||[]).map(function(m){ return '&gt; '+esc(m.name); }).join('<br>')+(l.note?'<br>! '+esc(l.note):'')+'</div></div>'; }); h+='<div class="t-foot"><button onclick="bumpT(\''+t.kot+'\','+t.lines[0].id_pulse_pos_check+',\'ready\')">ALL READY</button><button onclick="bumpT(\''+t.kot+'\','+t.lines[0].id_pulse_pos_check+',\'served\')">SERVED / BUMP</button></div>'; d.innerHTML=h; g.appendChild(d); }); }); }
function bump(id,st){ call('bump',id,{ status:st }).then(load); } function bumpT(k,c,st){ call('bump_ticket',c,{ kot:k,status:st }).then(load); }
setInterval(load,10000); setInterval(function(){ document.getElementById('kds-clock').textContent=new Date().toLocaleTimeString(); },1000); load();
</script></body></html>
