<?php
class PulsePosReport
{
    protected static function r($from, $to, $outlet = null) { return 'c.status="settled" AND c.business_date BETWEEN "'.pSQL($from).'" AND "'.pSQL($to).'"'.($outlet ? ' AND c.id_pulse_pos_outlet='.(int) $outlet : ''); }
    public static function summary($from, $to, $outlet = null) { return Db::getInstance()->getRow('SELECT COUNT(*) checks, COALESCE(SUM(covers),0) covers, ROUND(COALESCE(SUM(subtotal),0),2) gross, ROUND(COALESCE(SUM(discount_total),0),2) discounts, ROUND(COALESCE(SUM(service_charge),0),2) service, ROUND(COALESCE(SUM(tax_total),0),2) tax, ROUND(COALESCE(SUM(total),0),2) net_sales, ROUND(COALESCE(SUM(tip_total),0),2) tips, ROUND(COALESCE(AVG(total),0),2) avg_check, ROUND(COALESCE(SUM(total)/NULLIF(SUM(covers),0),0),2) avg_cover FROM `'._DB_PREFIX_.'pulse_pos_check` c WHERE '.self::r($from, $to, $outlet)); }
    public static function byOutlet($from, $to) { return Db::getInstance()->executeS('SELECT o.name, COUNT(*) checks, SUM(c.covers) covers, ROUND(SUM(c.total),2) sales, ROUND(SUM(c.discount_total),2) discounts, ROUND(AVG(c.total),2) avg_check FROM `'._DB_PREFIX_.'pulse_pos_check` c INNER JOIN `'._DB_PREFIX_.'pulse_pos_outlet` o ON o.id_pulse_pos_outlet=c.id_pulse_pos_outlet WHERE '.self::r($from, $to).' GROUP BY o.id_pulse_pos_outlet ORDER BY sales DESC'); }
    public static function byItem($from, $to, $outlet = null, $limit = 50) { $rows = Db::getInstance()->executeS('SELECT l.id_pulse_pos_item, l.name, cat.name category, cat.major_group, SUM(l.qty) qty, ROUND(SUM(l.line_total-l.line_discount),2) sales, ROUND(AVG(l.unit_price),2) avg_price FROM `'._DB_PREFIX_.'pulse_pos_check_line` l INNER JOIN `'._DB_PREFIX_.'pulse_pos_check` c ON c.id_pulse_pos_check=l.id_pulse_pos_check LEFT JOIN `'._DB_PREFIX_.'pulse_pos_item` i ON i.id_pulse_pos_item=l.id_pulse_pos_item LEFT JOIN `'._DB_PREFIX_.'pulse_pos_category` cat ON cat.id_pulse_pos_category=i.id_pulse_pos_category WHERE l.voided=0 AND l.id_pulse_pos_item>0 AND '.self::r($from, $to, $outlet).' GROUP BY l.id_pulse_pos_item ORDER BY sales DESC LIMIT '.(int) $limit); foreach ($rows as &$x) { $x['cost'] = round(PulsePosInventory::itemCost($x['id_pulse_pos_item']) * $x['qty'], 2); $x['margin_pct'] = $x['sales'] > 0 ? round(($x['sales'] - $x['cost']) / $x['sales'] * 100, 1) : null; } return $rows; }
    /** Menu engineering: popularity vs contribution margin → Star / Plowhorse / Puzzle / Dog. */
    public static function menuEngineering($from, $to) { $items = self::byItem($from, $to, null, 500); if (!$items) { return array(); } $tq = 0; $tm = 0; $n = count($items); foreach ($items as $i) { $tq += $i['qty']; $tm += ($i['sales'] - $i['cost']); } $avgPop = $tq / $n * 0.7; $avgCm = $tm / max(1, $tq); foreach ($items as &$i) { $cm = $i['qty'] > 0 ? ($i['sales'] - $i['cost']) / $i['qty'] : 0; $pop = $i['qty'] >= $avgPop; $prof = $cm >= $avgCm; $i['cm_unit'] = round($cm, 2); $i['class'] = $pop && $prof ? 'Star' : ($pop && !$prof ? 'Plowhorse' : (!$pop && $prof ? 'Puzzle' : 'Dog')); } return $items; }
    public static function byCategory($from, $to, $outlet = null) { return Db::getInstance()->executeS('SELECT cat.name, cat.major_group, SUM(l.qty) qty, ROUND(SUM(l.line_total-l.line_discount),2) sales FROM `'._DB_PREFIX_.'pulse_pos_check_line` l INNER JOIN `'._DB_PREFIX_.'pulse_pos_check` c ON c.id_pulse_pos_check=l.id_pulse_pos_check INNER JOIN `'._DB_PREFIX_.'pulse_pos_item` i ON i.id_pulse_pos_item=l.id_pulse_pos_item INNER JOIN `'._DB_PREFIX_.'pulse_pos_category` cat ON cat.id_pulse_pos_category=i.id_pulse_pos_category WHERE l.voided=0 AND '.self::r($from, $to, $outlet).' GROUP BY cat.id_pulse_pos_category ORDER BY sales DESC'); }
    public static function byServer($from, $to, $outlet = null) { return Db::getInstance()->executeS('SELECT CONCAT(e.firstname," ",e.lastname) server, COUNT(*) checks, SUM(c.covers) covers, ROUND(SUM(c.total),2) sales, ROUND(AVG(c.total),2) avg_check, ROUND(SUM(c.tip_total),2) tips, ROUND(SUM(c.discount_total),2) discounts FROM `'._DB_PREFIX_.'pulse_pos_check` c INNER JOIN `'._DB_PREFIX_.'employee` e ON e.id_employee=c.id_server WHERE '.self::r($from, $to, $outlet).' GROUP BY c.id_server ORDER BY sales DESC'); }
    public static function byHour($from, $to, $outlet = null) { return Db::getInstance()->executeS('SELECT HOUR(c.date_add) hour, COUNT(*) checks, ROUND(SUM(c.total),2) sales FROM `'._DB_PREFIX_.'pulse_pos_check` c WHERE '.self::r($from, $to, $outlet).' GROUP BY HOUR(c.date_add) ORDER BY hour'); }
    public static function byDay($from, $to, $outlet = null) { return Db::getInstance()->executeS('SELECT c.business_date d, COUNT(*) checks, SUM(c.covers) covers, ROUND(SUM(c.total),2) sales FROM `'._DB_PREFIX_.'pulse_pos_check` c WHERE '.self::r($from, $to, $outlet).' GROUP BY c.business_date ORDER BY d'); }
    public static function payments($from, $to, $outlet = null) { return Db::getInstance()->executeS('SELECT p.method, COUNT(*) n, ROUND(SUM(p.amount),2) total, ROUND(SUM(p.tip),2) tips FROM `'._DB_PREFIX_.'pulse_pos_payment` p INNER JOIN `'._DB_PREFIX_.'pulse_pos_check` c ON c.id_pulse_pos_check=p.id_pulse_pos_check WHERE p.voided=0 AND '.self::r($from, $to, $outlet).' GROUP BY p.method ORDER BY total DESC'); }
    public static function voids($from, $to, $outlet = null) { return Db::getInstance()->executeS('SELECT c.check_no, l.name, l.qty, l.line_total, l.void_reason, l.void_after_send, CONCAT(e.firstname," ",e.lastname) by_who, l.date_add FROM `'._DB_PREFIX_.'pulse_pos_check_line` l INNER JOIN `'._DB_PREFIX_.'pulse_pos_check` c ON c.id_pulse_pos_check=l.id_pulse_pos_check LEFT JOIN `'._DB_PREFIX_.'employee` e ON e.id_employee=l.void_by WHERE l.voided=1 AND c.business_date BETWEEN "'.pSQL($from).'" AND "'.pSQL($to).'"'.($outlet ? ' AND c.id_pulse_pos_outlet='.(int) $outlet : '').' ORDER BY l.date_add DESC'); }
    public static function discounts($from, $to, $outlet = null) { return Db::getInstance()->executeS('SELECT c.check_no, c.discount_reason reason, c.discount_total amount, CONCAT(e.firstname," ",e.lastname) by_who, c.date_settled FROM `'._DB_PREFIX_.'pulse_pos_check` c LEFT JOIN `'._DB_PREFIX_.'employee` e ON e.id_employee=c.discount_by WHERE c.discount_total>0 AND '.self::r($from, $to, $outlet).' ORDER BY c.discount_total DESC'); }
    public static function comps($from, $to) { return Db::getInstance()->executeS('SELECT c.check_no, c.comp_reason, c.subtotal, c.date_settled FROM `'._DB_PREFIX_.'pulse_pos_check` c WHERE c.comp_reason IS NOT NULL AND '.self::r($from, $to).' ORDER BY c.date_settled DESC'); }
    public static function sessions($from, $to) { return Db::getInstance()->executeS('SELECT s.*, CONCAT(e.firstname," ",e.lastname) cashier, o.name outlet FROM `'._DB_PREFIX_.'pulse_pos_session` s INNER JOIN `'._DB_PREFIX_.'employee` e ON e.id_employee=s.id_employee INNER JOIN `'._DB_PREFIX_.'pulse_pos_outlet` o ON o.id_pulse_pos_outlet=s.id_pulse_pos_outlet WHERE s.business_date BETWEEN "'.pSQL($from).'" AND "'.pSQL($to).'" ORDER BY s.date_open DESC'); }
    public static function kitchenTimes($from, $to) { return Db::getInstance()->executeS('SELECT s.name station, COUNT(*) items, ROUND(AVG(TIMESTAMPDIFF(MINUTE,l.fired_at,l.ready_at)),1) avg_prep_min, MAX(TIMESTAMPDIFF(MINUTE,l.fired_at,l.ready_at)) max_min FROM `'._DB_PREFIX_.'pulse_pos_check_line` l INNER JOIN `'._DB_PREFIX_.'pulse_pos_check` c ON c.id_pulse_pos_check=l.id_pulse_pos_check INNER JOIN `'._DB_PREFIX_.'pulse_pos_station` s ON s.id_pulse_pos_station=l.id_pulse_pos_station WHERE l.ready_at IS NOT NULL AND c.business_date BETWEEN "'.pSQL($from).'" AND "'.pSQL($to).'" GROUP BY s.id_pulse_pos_station'); }
    public static function roomCharges($from, $to) { return Db::getInstance()->executeS('SELECT c.check_no, r.room_num, c.guest_name, p.amount, p.date_add, o.name outlet FROM `'._DB_PREFIX_.'pulse_pos_payment` p INNER JOIN `'._DB_PREFIX_.'pulse_pos_check` c ON c.id_pulse_pos_check=p.id_pulse_pos_check INNER JOIN `'._DB_PREFIX_.'pulse_pos_outlet` o ON o.id_pulse_pos_outlet=c.id_pulse_pos_outlet LEFT JOIN `'._DB_PREFIX_.'htl_room_information` r ON r.id=p.id_room WHERE p.method="room" AND p.voided=0 AND c.business_date BETWEEN "'.pSQL($from).'" AND "'.pSQL($to).'" ORDER BY p.date_add DESC'); }
    public static function toCsv(array $rows) { if (!$rows) { return ''; } $f = fopen('php://temp', 'r+'); fputcsv($f, array_keys($rows[0])); foreach ($rows as $r) { fputcsv($f, $r); } rewind($f); $s = stream_get_contents($f); fclose($f); return $s; }
}
