<?php
class PulseInvReport
{
    public static function consumptionByDept($from, $to) { return Db::getInstance()->executeS('SELECT m.department, c.group_name, ROUND(SUM(-m.value),2) cost, COUNT(*) postings FROM `'._DB_PREFIX_.'pulse_inv_movement` m INNER JOIN `'._DB_PREFIX_.'pulse_inv_item` i ON i.id_pulse_inv_item=m.id_pulse_inv_item INNER JOIN `'._DB_PREFIX_.'pulse_inv_category` c ON c.id_pulse_inv_category=i.id_pulse_inv_category WHERE m.type IN ("consume","amenity","minibar","waste","sale","issue") AND m.qty<0 AND m.business_date BETWEEN "'.pSQL($from).'" AND "'.pSQL($to).'" GROUP BY m.department, c.group_name ORDER BY m.department, cost DESC'); }
    public static function purchasesByCategory($from, $to) { return Db::getInstance()->executeS('SELECT c.name category, ROUND(SUM(m.value),2) value, SUM(m.qty) qty FROM `'._DB_PREFIX_.'pulse_inv_movement` m INNER JOIN `'._DB_PREFIX_.'pulse_inv_item` i ON i.id_pulse_inv_item=m.id_pulse_inv_item INNER JOIN `'._DB_PREFIX_.'pulse_inv_category` c ON c.id_pulse_inv_category=i.id_pulse_inv_category WHERE m.type="receive" AND m.business_date BETWEEN "'.pSQL($from).'" AND "'.pSQL($to).'" GROUP BY c.id_pulse_inv_category ORDER BY value DESC'); }
    public static function slowMoving($days = 60) { return Db::getInstance()->executeS('SELECT i.sku, i.name, c.name category, COALESCE(SUM(s.qty),0) qty, ROUND(COALESCE(SUM(s.qty),0)*i.avg_cost,2) value, (SELECT MAX(m.business_date) FROM `'._DB_PREFIX_.'pulse_inv_movement` m WHERE m.id_pulse_inv_item=i.id_pulse_inv_item AND m.qty<0) last_used FROM `'._DB_PREFIX_.'pulse_inv_item` i INNER JOIN `'._DB_PREFIX_.'pulse_inv_category` c ON c.id_pulse_inv_category=i.id_pulse_inv_category LEFT JOIN `'._DB_PREFIX_.'pulse_inv_stock` s ON s.id_pulse_inv_item=i.id_pulse_inv_item WHERE i.active=1 GROUP BY i.id_pulse_inv_item HAVING qty>0 AND (last_used IS NULL OR last_used<DATE_SUB(CURDATE(), INTERVAL '.(int) $days.' DAY)) ORDER BY value DESC'); }
    public static function waste($from, $to) { return Db::getInstance()->executeS('SELECT i.name, st.code store, SUM(-m.qty) qty, i.unit, ROUND(SUM(-m.value),2) value, GROUP_CONCAT(DISTINCT m.reason) reasons FROM `'._DB_PREFIX_.'pulse_inv_movement` m INNER JOIN `'._DB_PREFIX_.'pulse_inv_item` i ON i.id_pulse_inv_item=m.id_pulse_inv_item INNER JOIN `'._DB_PREFIX_.'pulse_inv_store` st ON st.id_pulse_inv_store=m.id_pulse_inv_store WHERE m.type="waste" AND m.business_date BETWEEN "'.pSQL($from).'" AND "'.pSQL($to).'" GROUP BY i.id_pulse_inv_item, st.id_pulse_inv_store ORDER BY value DESC'); }
    public static function countVariances($from, $to) { return Db::getInstance()->executeS('SELECT c.count_no, st.name store, c.type, c.variance_value, c.date_posted, CONCAT(e.firstname," ",e.lastname) approved FROM `'._DB_PREFIX_.'pulse_inv_count` c INNER JOIN `'._DB_PREFIX_.'pulse_inv_store` st ON st.id_pulse_inv_store=c.id_pulse_inv_store LEFT JOIN `'._DB_PREFIX_.'employee` e ON e.id_employee=c.approved_by WHERE c.status="posted" AND c.business_date BETWEEN "'.pSQL($from).'" AND "'.pSQL($to).'" ORDER BY c.date_posted DESC'); }
    public static function stockCard($idItem, $from, $to) { $rows = PulseInvService::movements($from, $to, null, $idItem); $rows = array_reverse($rows); return $rows; }
    public static function toCsv(array $rows) { if (!$rows) { return ''; } $f = fopen('php://temp', 'r+'); fputcsv($f, array_keys($rows[0])); foreach ($rows as $r) { fputcsv($f, $r); } rewind($f); $s = stream_get_contents($f); fclose($f); return $s; }
}
