<div class="pulse-fd"><div class="panel"><h3><i class="icon-group"></i> {$g->code} &mdash; {$g->name} <span class="label label-info">{$g->status}</span></h3>
<p>{$g->date_from} → {$g->date_to} &middot; cut-off <b>{$g->cutoff_date}</b> &middot; billing: {$g->billing|replace:'_':' '} &middot; rate: {if $g->rate_per_night}{displayPrice price=$g->rate_per_night}/night{else}rack{/if}
{if $master} &middot; master folio <a href="{$folio_url}&id_pulse_folio={$master->id}&viewpulse_folio">{$master->folio_no}</a> (balance {displayPrice price=$master->balance}){/if}</p>
<div class="row"><div class="col-md-5"><h4>Allotments</h4>
<form method="post"><input type="hidden" name="id_pulse_group_block" value="{$g->id}"><table class="table table-condensed"><thead><tr><th>Room type</th><th>House avail</th><th>Blocked</th><th>Picked up</th></tr></thead><tbody>
{foreach $types as $t}<tr><td>{$t.name}</td><td>{$t.avail.available}/{$t.avail.physical}</td><td><input name="blocked[{$t.id_product}]" class="form-control input-sm" type="number" min="0" value="{$t.blocked}" style="width:70px"></td><td>{$t.picked_up}</td></tr>{/foreach}</tbody></table><button name="saveAllot" class="btn btn-default">Save allotments</button></form></div>
<div class="col-md-7"><h4>Rooming list</h4>
<form method="post" enctype="multipart/form-data" class="form-inline"><input type="hidden" name="id_pulse_group_block" value="{$g->id}"><input type="file" name="rooming" accept=".csv"> <button name="importRooming" class="btn btn-primary">Import CSV</button></form>
<p class="help-block">Columns: firstname, lastname, email, phone, room_type_id, adults, children, arrival (optional), departure (optional). One reservation per row, priced at the contracted rate.</p>
<table class="table table-condensed"><thead><tr><th>Guest</th><th>Room</th><th>Type</th><th>Dates</th><th>Status</th></tr></thead><tbody>{foreach $bookings as $b}<tr><td>{$b.guest}</td><td>{$b.room_num}</td><td>{$b.room_type_name}</td><td>{$b.date_from} → {$b.date_to}</td><td>{if $b.id_status==1}Reserved{elseif $b.id_status==2}In house{else}Departed{/if}</td></tr>{foreachelse}<tr><td colspan="5"><em>No pick-ups yet</em></td></tr>{/foreach}</tbody></table></div></div></div></div>
