<div class="pulse-mnt"><div class="panel"><h3><i class="icon-cog"></i> Asset register</h3>
<table class="table table-condensed"><thead><tr><th>Code</th><th>Asset</th><th>Category</th><th>Location</th><th>Make / serial</th><th>Warranty</th><th>Crit</th><th>Status</th><th>Open WO</th><th>Last service</th></tr></thead><tbody>
{foreach $assets as $a}<tr class="{if $a.status=='out_of_service'}danger{/if}"><td>{$a.code}</td><td>{$a.name}</td><td>{$a.category}</td><td>{if $a.room_num}Rm {$a.room_num}{else}{$a.location}{/if}</td><td>{$a.make_model} {$a.serial_no}</td><td>{$a.warranty_until}</td><td>{$a.criticality}</td><td>{$a.status|replace:'_':' '}</td><td>{$a.open_wo}</td><td>{$a.last_service|date_format:"%d/%m/%Y"}</td></tr>{/foreach}</tbody></table>
<div class="row"><div class="col-md-8"><h4>Add / edit asset</h4><form method="post" class="form-inline"><input type="hidden" name="id_asset"><input name="code" class="form-control" placeholder="Code" required> <input name="name" class="form-control" placeholder="Name" required> <select name="category" class="form-control">{foreach $categories as $c}<option>{$c}</option>{/foreach}</select> <select name="location_type" class="form-control"><option value="room">room</option><option value="public_area">public area</option><option value="plant">plant</option><option value="external">external</option></select> <select name="id_room" class="form-control"><option value="">—</option>{foreach $rooms as $r}<option value="{$r.id_room}">{$r.room_num}</option>{/foreach}</select> <input name="location" class="form-control" placeholder="Location"><br>
<input name="make_model" class="form-control" placeholder="Make / model"> <input name="serial_no" class="form-control" placeholder="Serial"> <input type="date" name="installed_on" class="form-control"> <input type="date" name="warranty_until" class="form-control" title="Warranty until"> <input name="purchase_cost" class="form-control" placeholder="Cost" style="width:100px"> <input name="vendor" class="form-control" placeholder="Vendor"> <input name="vendor_phone" class="form-control" placeholder="Vendor phone"> <select name="criticality" class="form-control"><option value="1">1 critical</option><option value="2">2</option><option value="3" selected>3</option><option value="4">4</option><option value="5">5 low</option></select> <button name="saveAsset" class="btn btn-default">Save asset</button></form></div>
<div class="col-md-4"><h4>Bulk-create one asset per room</h4><form method="post" class="form-inline"><input name="prefix" class="form-control" placeholder="Code prefix e.g. AC" style="width:120px"> <input name="bname" class="form-control" placeholder="Name e.g. Split AC"> <select name="bcategory" class="form-control">{foreach $categories as $c}<option>{$c}</option>{/foreach}</select> <button name="bulkRoomAssets" class="btn btn-default">Create</button></form><p class="help-block">Creates e.g. AC-101 … AC-52x so PM schedules and history attach to each room's unit.</p></div></div></div>
<div class="row"><div class="col-md-7"><div class="panel"><h3><i class="icon-archive"></i> Spare parts</h3><table class="table table-condensed"><thead><tr><th>SKU</th><th>Part</th><th>On hand</th><th>Reorder</th><th>Unit cost</th><th>Supplier</th></tr></thead><tbody>{foreach $parts as $p}<tr class="{if $p.qty_on_hand<=$p.reorder_level}warning{/if}"><td>{$p.sku}</td><td>{$p.name}</td><td>{$p.qty_on_hand} {$p.unit}</td><td>{$p.reorder_level}</td><td>{$p.unit_cost}</td><td>{$p.supplier}</td></tr>{/foreach}</tbody></table>
<form method="post" class="form-inline"><input type="hidden" name="id_part"><input name="sku" class="form-control" placeholder="SKU" required> <input name="pname" class="form-control" placeholder="Part" required> <input name="pcategory" class="form-control" placeholder="Category"> <input name="unit" class="form-control" placeholder="pc" style="width:60px"> <input name="reorder_level" class="form-control" placeholder="Reorder" style="width:80px"> <input name="unit_cost" class="form-control" placeholder="Cost" style="width:90px"> <input name="supplier" class="form-control" placeholder="Supplier"> <button name="savePart" class="btn btn-default">Save part</button></form>
<form method="post" class="form-inline" style="margin-top:6px"><select name="id_part_m" class="form-control">{foreach $parts as $p}<option value="{$p.id_pulse_part}">{$p.sku} {$p.name}</option>{/foreach}</select> <select name="mtype" class="form-control"><option value="receive">Receive</option><option value="return">Return</option><option value="adjust">Count adjust</option></select> <input name="mqty" class="form-control" placeholder="qty" style="width:70px"> <input name="mcost" class="form-control" placeholder="unit cost" style="width:90px"> <input name="mnote" class="form-control" placeholder="note / invoice"> <button name="partMove" class="btn btn-default">Record</button></form>
<h4>Recent movements</h4><table class="table table-condensed"><tbody>{foreach $moves as $m}<tr><td>{$m.date_add}</td><td>{$m.sku} {$m.name}</td><td>{$m.type}</td><td>{$m.qty}</td><td>{$m.wo_no}</td><td>{$m.note}</td></tr>{/foreach}</tbody></table></div></div>
<div class="col-md-5"><div class="panel"><h3><i class="icon-dashboard"></i> Meter readings</h3><form method="post" class="form-inline"><select name="meter" class="form-control">{foreach $meters as $m}<option>{$m}</option>{/foreach}</select> <select name="id_asset_m" class="form-control"><option value="">—</option>{foreach $assets as $a}{if $a.category=='generator' || $a.category=='building'}<option value="{$a.id_pulse_asset}">{$a.code}</option>{/if}{/foreach}</select> <input name="reading" class="form-control" placeholder="reading" style="width:100px"> <input name="cost" class="form-control" placeholder="cost ₦" style="width:100px"> <button name="addReading" class="btn btn-default">Record</button></form>
<table class="table table-condensed"><tbody>{foreach $readings as $r}<tr><td>{$r.read_at}</td><td>{$r.meter}</td><td>{$r.reading}</td><td>{$r.cost}</td></tr>{/foreach}</tbody></table><p class="help-block">Generator hours drive the generator service schedule; diesel litres and kWh feed the utilities cost report.</p></div></div></div></div>
