<?php
class AdminPulsePosSettingsController extends ModuleAdminController
{
    public function __construct()
    {
        $this->bootstrap = true; parent::__construct(); $this->meta_title = $this->l('POS Settings');
        $this->fields_options = array('pos' => array('title' => $this->l('POS options'), 'fields' => array('PULSE_POS_AUTO_LOGOUT_MIN' => array('title' => $this->l('Auto-lock POS after (minutes, 0=never)'), 'type' => 'text'), 'PULSE_POS_KDS_LATE_MIN' => array('title' => $this->l('KDS: flag ticket late after (minutes)'), 'type' => 'text'), 'PULSE_POS_TIP_ON_CARD' => array('title' => $this->l('Allow tip entry on payment'), 'type' => 'bool'), 'PULSE_POS_ROOM_GUEST_CHECK' => array('title' => $this->l('Mask guest name and require surname check for room charge'), 'type' => 'bool'), 'PULSE_POS_DEFAULT_TENDER' => array('title' => $this->l('Default tender'), 'type' => 'select', 'list' => array(array('id' => 'cash', 'name' => 'Cash'), array('id' => 'card', 'name' => 'Card'), array('id' => 'room', 'name' => 'Room')), 'identifier' => 'id'), 'PULSE_POS_RECEIPT_HOST' => array('title' => $this->l('Receipt printer IP (ESC/POS, port 9100)'), 'type' => 'text'), 'PULSE_POS_DRAWER_HOST' => array('title' => $this->l('Cash drawer printer IP'), 'type' => 'text'), 'PULSE_POS_BLIND_CLOSE' => array('title' => $this->l('Blind cashier close (hide expected cash from non-managers)'), 'type' => 'bool')), 'submit' => array('title' => $this->l('Save'))));
    }
    public function initContent()
    {
        parent::initContent();
        $this->context->smarty->assign(array('outlets' => Db::getInstance()->executeS('SELECT o.*, t.name tax_group FROM `'._DB_PREFIX_.'pulse_pos_outlet` o LEFT JOIN `'._DB_PREFIX_.'pulse_pos_tax_group` t ON t.id_pulse_pos_tax_group=o.id_tax_group'), 'sections' => Db::getInstance()->executeS('SELECT s.*, o.name outlet FROM `'._DB_PREFIX_.'pulse_pos_section` s INNER JOIN `'._DB_PREFIX_.'pulse_pos_outlet` o ON o.id_pulse_pos_outlet=s.id_pulse_pos_outlet'), 'tables' => Db::getInstance()->executeS('SELECT t.*, o.name outlet, s.name section FROM `'._DB_PREFIX_.'pulse_pos_table` t INNER JOIN `'._DB_PREFIX_.'pulse_pos_outlet` o ON o.id_pulse_pos_outlet=t.id_pulse_pos_outlet LEFT JOIN `'._DB_PREFIX_.'pulse_pos_section` s ON s.id_pulse_pos_section=t.id_pulse_pos_section ORDER BY o.name, s.sort, t.code'),
            'staff' => Db::getInstance()->executeS('SELECT s.*, CONCAT(e.firstname," ",e.lastname) name FROM `'._DB_PREFIX_.'pulse_pos_staff` s INNER JOIN `'._DB_PREFIX_.'employee` e ON e.id_employee=s.id_employee'), 'employees' => Employee::getEmployees(), 'stations' => Db::getInstance()->executeS('SELECT * FROM `'._DB_PREFIX_.'pulse_pos_station`'), 'tax_groups' => Db::getInstance()->executeS('SELECT * FROM `'._DB_PREFIX_.'pulse_pos_tax_group`'), 'vouchers' => Db::getInstance()->executeS('SELECT * FROM `'._DB_PREFIX_.'pulse_pos_voucher` ORDER BY id_pulse_pos_voucher DESC LIMIT 30'),
            'pos_url' => $this->context->link->getModuleLink('pulsepos', 'app', array(), true), 'kds_url' => $this->context->link->getModuleLink('pulsepos', 'kds', array(), true), 'self_url' => self::$currentIndex.'&token='.$this->token));
        $this->content .= $this->context->smarty->fetch($this->getTemplatePath().'pulse_pos_settings/settings.tpl');
        $this->context->smarty->assign('content', $this->content);
    }
    public function postProcess()
    {
        $D = Db::getInstance();
        try {
            if (Tools::isSubmit('saveOutlet')) { $id = (int) Tools::getValue('id_outlet'); $d = array('code' => pSQL(strtoupper(Tools::getValue('code'))), 'name' => pSQL(Tools::getValue('name')), 'type' => pSQL(Tools::getValue('type')), 'service_charge_pct' => (float) Tools::getValue('service_charge_pct'), 'service_charge_taxable' => (int) Tools::getValue('sc_taxable'), 'id_tax_group' => (int) Tools::getValue('id_tax_group'), 'default_price_level' => (int) Tools::getValue('default_price_level', 1), 'allow_room_charge' => (int) Tools::getValue('allow_room_charge'), 'allow_tabs' => (int) Tools::getValue('allow_tabs'), 'require_covers' => (int) Tools::getValue('require_covers'), 'receipt_header' => pSQL(Tools::getValue('receipt_header')), 'receipt_footer' => pSQL(Tools::getValue('receipt_footer')), 'tray_charge' => (float) Tools::getValue('tray_charge'), 'speed_screen' => (int) Tools::getValue('speed_screen'), 'store' => pSQL(Tools::getValue('store', 'main')), 'active' => (int) Tools::getValue('oactive', 1)); $id ? $D->update('pulse_pos_outlet', $d, 'id_pulse_pos_outlet='.$id) : $D->insert('pulse_pos_outlet', $d); $this->confirmations[] = $this->l('Outlet saved'); }
            if (Tools::isSubmit('saveSection')) { $D->insert('pulse_pos_section', array('id_pulse_pos_outlet' => (int) Tools::getValue('s_outlet'), 'name' => pSQL(Tools::getValue('sname')), 'sort' => (int) Tools::getValue('ssort'))); }
            if (Tools::isSubmit('saveTable')) { $id = (int) Tools::getValue('id_table'); $d = array('id_pulse_pos_outlet' => (int) Tools::getValue('t_outlet'), 'id_pulse_pos_section' => (int) Tools::getValue('t_section') ?: null, 'code' => pSQL(Tools::getValue('tcode')), 'seats' => (int) Tools::getValue('seats'), 'shape' => pSQL(Tools::getValue('shape')), 'pos_x' => (int) Tools::getValue('pos_x'), 'pos_y' => (int) Tools::getValue('pos_y'), 'active' => (int) Tools::getValue('tactive', 1)); $id ? $D->update('pulse_pos_table', $d, 'id_pulse_pos_table='.$id) : $D->insert('pulse_pos_table', $d); $this->confirmations[] = $this->l('Table saved'); }
            if (Tools::isSubmit('bulkTables')) { $o = (int) Tools::getValue('b_outlet'); $sec = (int) Tools::getValue('b_section') ?: null; $n = (int) Tools::getValue('b_count'); $pre = pSQL(Tools::getValue('b_prefix', 'T')); for ($i = 1; $i <= $n; $i++) { $D->execute('INSERT IGNORE INTO `'._DB_PREFIX_.'pulse_pos_table` (id_pulse_pos_outlet,id_pulse_pos_section,code,seats,pos_x,pos_y) VALUES ('.$o.','.($sec ?: 'NULL').',"'.$pre.$i.'",'.(int) Tools::getValue('b_seats', 4).','.(40 + (($i - 1) % 5) * 120).','.(40 + floor(($i - 1) / 5) * 110).')'); } $this->confirmations[] = $this->l('Tables created'); }
            if (Tools::isSubmit('saveStaff')) { $e = (int) Tools::getValue('id_employee'); $pin = Tools::getValue('pin'); $d = array('role' => pSQL(Tools::getValue('role')), 'can_void_sent' => (int) Tools::getValue('can_void_sent'), 'can_discount' => (int) Tools::getValue('can_discount'), 'max_discount_pct' => (float) Tools::getValue('max_discount_pct'), 'can_reopen' => (int) Tools::getValue('can_reopen'), 'can_comp' => (int) Tools::getValue('can_comp'), 'can_settle' => (int) Tools::getValue('can_settle', 1), 'outlets' => pSQL(implode(',', (array) Tools::getValue('st_outlets'))) ?: null, 'active' => (int) Tools::getValue('sactive', 1)); if ($pin !== '') { if (!preg_match('/^\d{4,6}$/', $pin)) { throw new PrestaShopException('PIN must be 4–6 digits'); } $d['pin_hash'] = pSQL(PulsePosService::setPin($e, $pin)); } if ($D->getValue('SELECT id_employee FROM `'._DB_PREFIX_.'pulse_pos_staff` WHERE id_employee='.$e)) { $D->update('pulse_pos_staff', $d, 'id_employee='.$e); } else { if (empty($d['pin_hash'])) { throw new PrestaShopException('PIN required for new POS user'); } $d['id_employee'] = $e; $D->insert('pulse_pos_staff', $d); } $this->confirmations[] = $this->l('POS user saved'); }
            if (Tools::isSubmit('saveStation')) { $id = (int) Tools::getValue('id_station'); $d = array('code' => pSQL(strtoupper(Tools::getValue('scode'))), 'name' => pSQL(Tools::getValue('stname')), 'printer_host' => pSQL(Tools::getValue('printer_host')), 'printer_port' => (int) Tools::getValue('printer_port', 9100), 'kds' => (int) Tools::getValue('kds')); $id ? $D->update('pulse_pos_station', $d, 'id_pulse_pos_station='.$id) : $D->insert('pulse_pos_station', $d); $this->confirmations[] = $this->l('Station saved'); }
            if (Tools::isSubmit('testPrint')) { $st = $D->getRow('SELECT * FROM `'._DB_PREFIX_.'pulse_pos_station` WHERE id_pulse_pos_station='.(int) Tools::getValue('id_station_t')); $ok = PulsePosPrinter::raw($st['printer_host'], $st['printer_port'], PulsePosPrinter::esc("PULSE POS TEST\n".$st['name']."\n".date('d/m/Y H:i')."\n")); $ok ? $this->confirmations[] = $this->l('Test ticket sent') : $this->errors[] = $this->l('Printer unreachable'); }
            if (Tools::isSubmit('saveTax')) { $D->insert('pulse_pos_tax_group', array('name' => pSQL(Tools::getValue('txname')), 'rate_pct' => (float) Tools::getValue('rate_pct'), 'components' => pSQL(Tools::getValue('components')), 'inclusive' => 1)); }
            if (Tools::isSubmit('saveVoucher')) { $n = (int) Tools::getValue('vcount', 1); for ($i = 0; $i < $n; $i++) { $D->insert('pulse_pos_voucher', array('code' => pSQL(strtoupper(Tools::getValue('vprefix', 'GV')).'-'.strtoupper(Tools::passwdGen(8, 'ALPHANUMERIC'))), 'type' => pSQL(Tools::getValue('vtype')), 'value' => (float) Tools::getValue('vvalue'), 'balance' => (float) Tools::getValue('vvalue'), 'issued_to' => pSQL(Tools::getValue('vto')), 'expires' => Tools::getValue('vexp') ?: null, 'date_add' => date('Y-m-d H:i:s'))); } $this->confirmations[] = sprintf($this->l('%d voucher(s) created'), $n); }
        } catch (Exception $e) { $this->errors[] = $e->getMessage(); }
        return parent::postProcess();
    }
}
