<?php
class AdminPulsePosMenuController extends ModuleAdminController
{
    public function __construct() { $this->bootstrap = true; parent::__construct(); $this->meta_title = $this->l('POS Menu'); }
    public function initContent()
    {
        parent::initContent();
        $items = Db::getInstance()->executeS('SELECT i.*, c.name category, s.code station, t.name tax_group, (SELECT GROUP_CONCAT(g.name SEPARATOR ", ") FROM `'._DB_PREFIX_.'pulse_pos_item_modifier_group` img INNER JOIN `'._DB_PREFIX_.'pulse_pos_modifier_group` g ON g.id_pulse_pos_modifier_group=img.id_pulse_pos_modifier_group WHERE img.id_pulse_pos_item=i.id_pulse_pos_item) mod_groups, (SELECT COUNT(*) FROM `'._DB_PREFIX_.'pulse_pos_recipe` r WHERE r.id_pulse_pos_item=i.id_pulse_pos_item) recipe_lines FROM `'._DB_PREFIX_.'pulse_pos_item` i LEFT JOIN `'._DB_PREFIX_.'pulse_pos_category` c ON c.id_pulse_pos_category=i.id_pulse_pos_category LEFT JOIN `'._DB_PREFIX_.'pulse_pos_station` s ON s.id_pulse_pos_station=i.id_pulse_pos_station LEFT JOIN `'._DB_PREFIX_.'pulse_pos_tax_group` t ON t.id_pulse_pos_tax_group=i.id_pulse_pos_tax_group ORDER BY c.sort, i.sort, i.name');
        foreach ($items as &$i) { $i['cost'] = PulsePosInventory::itemCost($i['id_pulse_pos_item']); $i['margin'] = $i['price1'] > 0 ? round(($i['price1'] - $i['cost']) / $i['price1'] * 100, 1) : null; }
        $edit = (int) Tools::getValue('id_item'); $item = $edit ? Db::getInstance()->getRow('SELECT * FROM `'._DB_PREFIX_.'pulse_pos_item` WHERE id_pulse_pos_item='.$edit) : null;
        $this->context->smarty->assign(array('items' => $items, 'item' => $item, 'item_groups' => $edit ? Db::getInstance()->executeS('SELECT * FROM `'._DB_PREFIX_.'pulse_pos_item_modifier_group` WHERE id_pulse_pos_item='.$edit) : array(), 'item_recipe' => $edit ? Db::getInstance()->executeS('SELECT r.*, g.name, g.unit, g.unit_cost FROM `'._DB_PREFIX_.'pulse_pos_recipe` r INNER JOIN `'._DB_PREFIX_.'pulse_pos_ingredient` g ON g.id_pulse_pos_ingredient=r.id_pulse_pos_ingredient WHERE r.id_pulse_pos_item='.$edit) : array(), 'item_combo' => $edit ? Db::getInstance()->executeS('SELECT cc.*, i.name FROM `'._DB_PREFIX_.'pulse_pos_combo_component` cc INNER JOIN `'._DB_PREFIX_.'pulse_pos_item` i ON i.id_pulse_pos_item=cc.id_component_item WHERE cc.id_pulse_pos_item='.$edit) : array(),
            'categories' => Db::getInstance()->executeS('SELECT * FROM `'._DB_PREFIX_.'pulse_pos_category` ORDER BY sort'), 'stations' => Db::getInstance()->executeS('SELECT * FROM `'._DB_PREFIX_.'pulse_pos_station` WHERE active=1'), 'tax_groups' => Db::getInstance()->executeS('SELECT * FROM `'._DB_PREFIX_.'pulse_pos_tax_group`'), 'outlets' => Db::getInstance()->executeS('SELECT id_pulse_pos_outlet, name FROM `'._DB_PREFIX_.'pulse_pos_outlet` WHERE active=1'),
            'mod_groups' => Db::getInstance()->executeS('SELECT g.*, (SELECT GROUP_CONCAT(CONCAT(m.name,IF(m.price>0,CONCAT(" +",m.price),"")) SEPARATOR ", ") FROM `'._DB_PREFIX_.'pulse_pos_modifier` m WHERE m.id_pulse_pos_modifier_group=g.id_pulse_pos_modifier_group AND m.active=1) mods FROM `'._DB_PREFIX_.'pulse_pos_modifier_group` g ORDER BY g.sort'), 'ingredients' => Db::getInstance()->executeS('SELECT id_pulse_pos_ingredient, name, unit, unit_cost FROM `'._DB_PREFIX_.'pulse_pos_ingredient` WHERE active=1 ORDER BY name'),
            'periods' => Db::getInstance()->executeS('SELECT p.*, o.name outlet FROM `'._DB_PREFIX_.'pulse_pos_service_period` p LEFT JOIN `'._DB_PREFIX_.'pulse_pos_outlet` o ON o.id_pulse_pos_outlet=p.id_pulse_pos_outlet ORDER BY start_time'), 'discounts' => Db::getInstance()->executeS('SELECT * FROM `'._DB_PREFIX_.'pulse_pos_discount`'), 'reasons' => Db::getInstance()->executeS('SELECT * FROM `'._DB_PREFIX_.'pulse_pos_reason` ORDER BY type, name'),
            'self_url' => self::$currentIndex.'&token='.$this->token));
        $this->setTemplate('menu.tpl');
    }
    public function postProcess()
    {
        $D = Db::getInstance();
        try {
            if (Tools::isSubmit('saveItem')) { $id = (int) Tools::getValue('id_item'); $d = array('plu' => pSQL(Tools::getValue('plu')), 'name' => pSQL(Tools::getValue('name')), 'short_name' => pSQL(Tools::getValue('short_name')), 'id_pulse_pos_category' => (int) Tools::getValue('id_category'), 'id_pulse_pos_station' => (int) Tools::getValue('id_station'), 'price1' => (float) Tools::getValue('price1'), 'price2' => Tools::getValue('price2') !== '' ? (float) Tools::getValue('price2') : null, 'price3' => Tools::getValue('price3') !== '' ? (float) Tools::getValue('price3') : null, 'open_price' => (int) Tools::getValue('open_price'), 'id_pulse_pos_tax_group' => (int) Tools::getValue('id_tax_group'), 'is_combo' => (int) Tools::getValue('is_combo'), 'course' => (int) Tools::getValue('course'), 'prep_minutes' => (int) Tools::getValue('prep_minutes', 15), 'available' => (int) Tools::getValue('available', 1), 'count_down' => Tools::getValue('count_down') !== '' ? (int) Tools::getValue('count_down') : null, 'outlets' => pSQL(implode(',', (array) Tools::getValue('outlets'))) ?: null, 'barcode' => pSQL(Tools::getValue('barcode')), 'sort' => (int) Tools::getValue('sort'), 'active' => (int) Tools::getValue('active', 1)); if ($id) { $D->update('pulse_pos_item', $d, 'id_pulse_pos_item='.$id); } else { $D->insert('pulse_pos_item', $d); $id = (int) $D->Insert_ID(); } $D->delete('pulse_pos_item_modifier_group', 'id_pulse_pos_item='.$id); foreach ((array) Tools::getValue('mod_groups') as $g) { $D->insert('pulse_pos_item_modifier_group', array('id_pulse_pos_item' => $id, 'id_pulse_pos_modifier_group' => (int) $g, 'required' => in_array($g, (array) Tools::getValue('mod_required')) ? 1 : 0)); } $this->confirmations[] = $this->l('Item saved'); }
            if (Tools::isSubmit('saveRecipe')) { $id = (int) Tools::getValue('id_item'); $D->delete('pulse_pos_recipe', 'id_pulse_pos_item='.$id); foreach ((array) Tools::getValue('r_ing') as $k => $ing) { $q = (float) Tools::getValue('r_qty')[$k]; if ($ing && $q > 0) { $D->execute('INSERT INTO `'._DB_PREFIX_.'pulse_pos_recipe` (id_pulse_pos_item,id_pulse_pos_ingredient,qty) VALUES ('.$id.','.(int) $ing.','.$q.') ON DUPLICATE KEY UPDATE qty=VALUES(qty)'); } } $this->confirmations[] = $this->l('Recipe saved'); }
            if (Tools::isSubmit('saveCombo')) { $id = (int) Tools::getValue('id_item'); $D->delete('pulse_pos_combo_component', 'id_pulse_pos_item='.$id); foreach ((array) Tools::getValue('c_item') as $k => $ci) { if ($ci) { $D->execute('INSERT INTO `'._DB_PREFIX_.'pulse_pos_combo_component` (id_pulse_pos_item,id_component_item,qty,choice_group) VALUES ('.$id.','.(int) $ci.','.(float) (Tools::getValue('c_qty')[$k] ?: 1).',"'.pSQL(Tools::getValue('c_grp')[$k]).'") ON DUPLICATE KEY UPDATE qty=VALUES(qty)'); } } $D->update('pulse_pos_item', array('is_combo' => 1), 'id_pulse_pos_item='.$id); $this->confirmations[] = $this->l('Combo saved'); }
            if (Tools::isSubmit('saveCategory')) { $id = (int) Tools::getValue('id_category'); $d = array('name' => pSQL(Tools::getValue('cname')), 'major_group' => pSQL(Tools::getValue('major_group')), 'course' => (int) Tools::getValue('ccourse'), 'colour' => pSQL(Tools::getValue('colour')), 'sort' => (int) Tools::getValue('csort')); $id ? $D->update('pulse_pos_category', $d, 'id_pulse_pos_category='.$id) : $D->insert('pulse_pos_category', $d); $this->confirmations[] = $this->l('Category saved'); }
            if (Tools::isSubmit('saveGroup')) { $id = (int) Tools::getValue('id_group'); $d = array('name' => pSQL(Tools::getValue('gname')), 'min_select' => (int) Tools::getValue('min_select'), 'max_select' => (int) Tools::getValue('max_select')); if ($id) { $D->update('pulse_pos_modifier_group', $d, 'id_pulse_pos_modifier_group='.$id); } else { $D->insert('pulse_pos_modifier_group', $d); $id = (int) $D->Insert_ID(); } foreach (array_filter(array_map('trim', explode("\n", Tools::getValue('mods')))) as $line) { $parts = array_map('trim', explode('|', $line)); $ing = isset($parts[2]) ? (int) $parts[2] : 0; $D->execute('INSERT INTO `'._DB_PREFIX_.'pulse_pos_modifier` (id_pulse_pos_modifier_group,name,price,id_ingredient,ingredient_qty) VALUES ('.$id.',"'.pSQL($parts[0]).'",'.(float) (isset($parts[1]) ? $parts[1] : 0).','.($ing ?: 'NULL').','.(isset($parts[3]) ? (float) $parts[3] : 'NULL').')'); } $this->confirmations[] = $this->l('Modifier group saved (modifiers appended)'); }
            if (Tools::isSubmit('savePeriod')) { $id = (int) Tools::getValue('id_period'); $d = array('name' => pSQL(Tools::getValue('pname')), 'id_pulse_pos_outlet' => (int) Tools::getValue('p_outlet') ?: null, 'start_time' => pSQL(Tools::getValue('start_time')), 'end_time' => pSQL(Tools::getValue('end_time')), 'days' => pSQL(implode('', (array) Tools::getValue('days')) ?: '1234567'), 'price_level' => (int) Tools::getValue('price_level'), 'categories' => pSQL(implode(',', (array) Tools::getValue('p_cats'))) ?: null, 'active' => (int) Tools::getValue('pactive', 1)); $id ? $D->update('pulse_pos_service_period', $d, 'id_pulse_pos_service_period='.$id) : $D->insert('pulse_pos_service_period', $d); $this->confirmations[] = $this->l('Service period saved'); }
            if (Tools::isSubmit('saveDiscount')) { $D->insert('pulse_pos_discount', array('name' => pSQL(Tools::getValue('dname')), 'type' => pSQL(Tools::getValue('dtype')), 'value' => (float) Tools::getValue('dvalue'), 'scope' => pSQL(Tools::getValue('dscope')), 'requires_manager' => (int) Tools::getValue('dmgr'))); $this->confirmations[] = $this->l('Discount saved'); }
            if (Tools::isSubmit('saveReason')) { $D->insert('pulse_pos_reason', array('type' => pSQL(Tools::getValue('rtype')), 'name' => pSQL(Tools::getValue('rname')))); }
            if (Tools::isSubmit('toggleItem')) { $D->execute('UPDATE `'._DB_PREFIX_.'pulse_pos_item` SET available=1-available WHERE id_pulse_pos_item='.(int) Tools::getValue('id_item_t')); }
            if (Tools::isSubmit('importCsv') && isset($_FILES['csv']['tmp_name']) && $_FILES['csv']['tmp_name']) { $n = 0; $h = fopen($_FILES['csv']['tmp_name'], 'r'); fgetcsv($h); while (($r = fgetcsv($h)) !== false) { if (count($r) < 4) { continue; } $cat = (int) $D->getValue('SELECT id_pulse_pos_category FROM `'._DB_PREFIX_.'pulse_pos_category` WHERE name="'.pSQL($r[2]).'"'); if (!$cat) { $D->insert('pulse_pos_category', array('name' => pSQL($r[2]))); $cat = (int) $D->Insert_ID(); } $st = (int) $D->getValue('SELECT id_pulse_pos_station FROM `'._DB_PREFIX_.'pulse_pos_station` WHERE code="'.pSQL(isset($r[5]) ? $r[5] : 'KITCHEN').'"'); $D->execute('INSERT INTO `'._DB_PREFIX_.'pulse_pos_item` (plu,name,id_pulse_pos_category,price1,price2,id_pulse_pos_station,id_pulse_pos_tax_group) VALUES ("'.pSQL($r[0]).'","'.pSQL($r[1]).'",'.$cat.','.(float) $r[3].','.(isset($r[4]) && $r[4] !== '' ? (float) $r[4] : 'NULL').','.($st ?: 'NULL').',1) ON DUPLICATE KEY UPDATE name=VALUES(name), price1=VALUES(price1), price2=VALUES(price2), id_pulse_pos_category=VALUES(id_pulse_pos_category)'); $n++; } $this->confirmations[] = sprintf($this->l('%d items imported'), $n); }
        } catch (Exception $e) { $this->errors[] = $e->getMessage(); }
        return parent::postProcess();
    }
}
