<div class="pulse-pos"><ul class="nav nav-tabs"><li class="active"><a data-toggle="tab" href="#m-items">Items ({$items|count})</a></li><li><a data-toggle="tab" href="#m-cats">Categories</a></li><li><a data-toggle="tab" href="#m-mods">Modifier groups</a></li><li><a data-toggle="tab" href="#m-per">Service periods &amp; pricing</a></li><li><a data-toggle="tab" href="#m-disc">Discounts &amp; reasons</a></li><li><a data-toggle="tab" href="#m-imp">Import</a></li></ul>
<div class="tab-content">
<div class="tab-pane active" id="m-items"><div class="panel">
{if $item}<h3>Edit item — {$item.name}</h3>{else}<h3>New item</h3>{/if}
<form method="post" class="form-horizontal"><input type="hidden" name="id_item" value="{$item.id_pulse_pos_item|default:''}">
<div class="row"><div class="col-md-6">
<div class="form-group"><label class="col-sm-3">PLU / name</label><div class="col-sm-3"><input name="plu" class="form-control" value="{$item.plu|default:''}" required></div><div class="col-sm-6"><input name="name" class="form-control" value="{$item.name|default:''}" required></div></div>
<div class="form-group"><label class="col-sm-3">Short name / barcode</label><div class="col-sm-4"><input name="short_name" class="form-control" value="{$item.short_name|default:''}" maxlength="24"></div><div class="col-sm-5"><input name="barcode" class="form-control" value="{$item.barcode|default:''}"></div></div>
<div class="form-group"><label class="col-sm-3">Category / station</label><div class="col-sm-5"><select name="id_category" class="form-control">{foreach $categories as $c}<option value="{$c.id_pulse_pos_category}" {if $item && $item.id_pulse_pos_category==$c.id_pulse_pos_category}selected{/if}>{$c.name}</option>{/foreach}</select></div><div class="col-sm-4"><select name="id_station" class="form-control">{foreach $stations as $s}<option value="{$s.id_pulse_pos_station}" {if $item && $item.id_pulse_pos_station==$s.id_pulse_pos_station}selected{/if}>{$s.name}</option>{/foreach}</select></div></div>
<div class="form-group"><label class="col-sm-3">Price L1 / L2 (happy hr) / L3</label><div class="col-sm-3"><input name="price1" class="form-control" value="{$item.price1|default:''}"></div><div class="col-sm-3"><input name="price2" class="form-control" value="{$item.price2|default:''}"></div><div class="col-sm-3"><input name="price3" class="form-control" value="{$item.price3|default:''}"></div></div>
<div class="form-group"><label class="col-sm-3">Tax / course / prep</label><div class="col-sm-4"><select name="id_tax_group" class="form-control">{foreach $tax_groups as $t}<option value="{$t.id_pulse_pos_tax_group}" {if $item && $item.id_pulse_pos_tax_group==$t.id_pulse_pos_tax_group}selected{/if}>{$t.name}</option>{/foreach}</select></div><div class="col-sm-3"><select name="course" class="form-control">{foreach [0=>'No course',1=>'Starter',2=>'Main',3=>'Dessert'] as $k=>$v}<option value="{$k}" {if $item && $item.course==$k}selected{/if}>{$v}</option>{/foreach}</select></div><div class="col-sm-2"><input name="prep_minutes" class="form-control" value="{$item.prep_minutes|default:15}" title="prep minutes"></div></div>
<div class="form-group"><label class="col-sm-3">Flags</label><div class="col-sm-9"><label><input type="checkbox" name="open_price" value="1" {if $item && $item.open_price}checked{/if}> open price</label> &nbsp; <label><input type="checkbox" name="is_combo" value="1" {if $item && $item.is_combo}checked{/if}> combo</label> &nbsp; <label><input type="checkbox" name="available" value="1" {if !$item || $item.available}checked{/if}> available</label> &nbsp; count-down <input name="count_down" class="input-sm" style="width:70px" value="{$item.count_down|default:''}" placeholder="∞"> &nbsp; sort <input name="sort" class="input-sm" style="width:50px" value="{$item.sort|default:0}"></div></div>
<div class="form-group"><label class="col-sm-3">Outlets (none = all)</label><div class="col-sm-9">{foreach $outlets as $o}<label class="checkbox-inline"><input type="checkbox" name="outlets[]" value="{$o.id_pulse_pos_outlet}" {if $item && $item.outlets && in_array($o.id_pulse_pos_outlet, explode(',', $item.outlets))}checked{/if}> {$o.name}</label>{/foreach}</div></div></div>
<div class="col-md-6"><label>Modifier groups</label><table class="table table-condensed">{foreach $mod_groups as $g}<tr><td><label><input type="checkbox" name="mod_groups[]" value="{$g.id_pulse_pos_modifier_group}" {foreach $item_groups as $ig}{if $ig.id_pulse_pos_modifier_group==$g.id_pulse_pos_modifier_group}checked{/if}{/foreach}> {$g.name}</label> <small class="text-muted">{$g.mods|truncate:60}</small></td><td><label><input type="checkbox" name="mod_required[]" value="{$g.id_pulse_pos_modifier_group}" {foreach $item_groups as $ig}{if $ig.id_pulse_pos_modifier_group==$g.id_pulse_pos_modifier_group && $ig.required}checked{/if}{/foreach}> required</label></td></tr>{/foreach}</table>
<button name="saveItem" class="btn btn-primary pull-right">Save item</button></div></div></form>
{if $item}<hr><div class="row"><div class="col-md-6"><h4>Recipe (per portion)</h4><form method="post"><input type="hidden" name="id_item" value="{$item.id_pulse_pos_item}"><table class="table table-condensed">{foreach $item_recipe as $r}<tr><td><select name="r_ing[]" class="form-control input-sm">{foreach $ingredients as $g}<option value="{$g.id_pulse_pos_ingredient}" {if $g.id_pulse_pos_ingredient==$r.id_pulse_pos_ingredient}selected{/if}>{$g.name} ({$g.unit})</option>{/foreach}</select></td><td><input name="r_qty[]" class="form-control input-sm" value="{$r.qty}"></td><td>{($r.unit_cost*$r.qty)|number_format:2}</td></tr>{/foreach}{section name=n loop=3}<tr><td><select name="r_ing[]" class="form-control input-sm"><option value="">— add ingredient —</option>{foreach $ingredients as $g}<option value="{$g.id_pulse_pos_ingredient}">{$g.name} ({$g.unit})</option>{/foreach}</select></td><td><input name="r_qty[]" class="form-control input-sm" placeholder="qty"></td><td></td></tr>{/section}</table><button name="saveRecipe" class="btn btn-default btn-sm">Save recipe</button></form></div>
<div class="col-md-6"><h4>Combo components {if !$item.is_combo}<small>(tick "combo" above)</small>{/if}</h4><form method="post"><input type="hidden" name="id_item" value="{$item.id_pulse_pos_item}"><table class="table table-condensed">{foreach $item_combo as $cc}<tr><td><select name="c_item[]" class="form-control input-sm">{foreach $items as $i}<option value="{$i.id_pulse_pos_item}" {if $i.id_pulse_pos_item==$cc.id_component_item}selected{/if}>{$i.name}</option>{/foreach}</select></td><td><input name="c_qty[]" class="form-control input-sm" value="{$cc.qty}" style="width:60px"></td><td><input name="c_grp[]" class="form-control input-sm" value="{$cc.choice_group}" placeholder="choice group"></td></tr>{/foreach}{section name=n loop=3}<tr><td><select name="c_item[]" class="form-control input-sm"><option value="">— add component —</option>{foreach $items as $i}<option value="{$i.id_pulse_pos_item}">{$i.name}</option>{/foreach}</select></td><td><input name="c_qty[]" class="form-control input-sm" value="1" style="width:60px"></td><td><input name="c_grp[]" class="form-control input-sm" placeholder="e.g. DRINK"></td></tr>{/section}</table><button name="saveCombo" class="btn btn-default btn-sm">Save combo</button></form></div></div>{/if}
</div>
<div class="panel"><h3>Items</h3><table class="table table-condensed"><thead><tr><th>PLU</th><th>Item</th><th>Category</th><th>Station</th><th>L1</th><th>L2</th><th>Cost</th><th>Margin</th><th>Mods</th><th>Recipe</th><th>Avail</th><th></th></tr></thead><tbody>{foreach $items as $i}<tr class="{if !$i.available}text-muted{/if}"><td>{$i.plu}</td><td><a href="{$self_url}&id_item={$i.id_pulse_pos_item}">{$i.name}</a></td><td>{$i.category}</td><td>{$i.station}</td><td>{$i.price1}</td><td>{$i.price2}</td><td>{$i.cost|number_format:0}</td><td>{if $i.margin!==null}{$i.margin}%{/if}</td><td><small>{$i.mod_groups}</small></td><td>{$i.recipe_lines}</td><td>{if $i.available}yes{else}86{/if}{if $i.count_down!==null} ({$i.count_down}){/if}</td><td><form method="post" class="inline"><input type="hidden" name="id_item_t" value="{$i.id_pulse_pos_item}"><button name="toggleItem" class="btn btn-xs btn-default">{if $i.available}86{else}restore{/if}</button></form></td></tr>{/foreach}</tbody></table></div></div>
<div class="tab-pane" id="m-cats"><div class="panel"><table class="table table-condensed"><thead><tr><th>Category</th><th>Major group</th><th>Course</th><th>Colour</th><th>Sort</th></tr></thead><tbody>{foreach $categories as $c}<tr><td>{$c.name}</td><td>{$c.major_group}</td><td>{$c.course}</td><td><span style="display:inline-block;width:16px;height:16px;background:{$c.colour}"></span> {$c.colour}</td><td>{$c.sort}</td></tr>{/foreach}</tbody></table>
<form method="post" class="form-inline"><input type="hidden" name="id_category"><input name="cname" class="form-control" placeholder="Name" required> <select name="major_group" class="form-control"><option>food</option><option>beverage</option><option>liquor</option><option>tobacco</option><option>other</option></select> <select name="ccourse" class="form-control"><option value="0">no course</option><option value="1">starter</option><option value="2">main</option><option value="3">dessert</option></select> <input name="colour" type="color" value="#2e86c1"> <input name="csort" class="form-control" placeholder="sort" style="width:70px"> <button name="saveCategory" class="btn btn-default">Save</button></form></div></div>
<div class="tab-pane" id="m-mods"><div class="panel"><table class="table table-condensed"><thead><tr><th>Group</th><th>Min</th><th>Max</th><th>Modifiers</th></tr></thead><tbody>{foreach $mod_groups as $g}<tr><td>{$g.name}</td><td>{$g.min_select}</td><td>{$g.max_select}</td><td>{$g.mods}</td></tr>{/foreach}</tbody></table>
<form method="post"><div class="form-inline"><input type="hidden" name="id_group"><input name="gname" class="form-control" placeholder="Group name" required> min <input name="min_select" class="form-control" value="0" style="width:60px"> max <input name="max_select" class="form-control" value="1" style="width:60px"></div><label>Modifiers, one per line: <code>Name | price | ingredient id | ingredient qty</code></label><textarea name="mods" class="form-control" rows="4"></textarea><button name="saveGroup" class="btn btn-default">Save group</button></form></div></div>
<div class="tab-pane" id="m-per"><div class="panel"><p class="help-block">Service periods switch the price level (L1 normal, L2 happy hour, L3 special) and can restrict the visible categories (e.g. breakfast menu only). The most specific match (outlet-level over global) wins.</p><table class="table table-condensed"><thead><tr><th>Period</th><th>Outlet</th><th>From</th><th>To</th><th>Days</th><th>Price level</th><th>Categories</th><th>Active</th></tr></thead><tbody>{foreach $periods as $p}<tr><td>{$p.name}</td><td>{$p.outlet|default:'all'}</td><td>{$p.start_time}</td><td>{$p.end_time}</td><td>{$p.days}</td><td>L{$p.price_level}</td><td>{$p.categories|default:'all'}</td><td>{$p.active}</td></tr>{/foreach}</tbody></table>
<form method="post" class="form-inline"><input type="hidden" name="id_period"><input name="pname" class="form-control" placeholder="Name" required> <select name="p_outlet" class="form-control"><option value="">all outlets</option>{foreach $outlets as $o}<option value="{$o.id_pulse_pos_outlet}">{$o.name}</option>{/foreach}</select> <input type="time" name="start_time" class="form-control"> <input type="time" name="end_time" class="form-control"> {foreach [1=>'M',2=>'T',3=>'W',4=>'T',5=>'F',6=>'S',7=>'S'] as $k=>$v}<label class="checkbox-inline"><input type="checkbox" name="days[]" value="{$k}" checked>{$v}</label>{/foreach} level <select name="price_level" class="form-control"><option value="1">L1</option><option value="2">L2</option><option value="3">L3</option></select><br>categories: {foreach $categories as $c}<label class="checkbox-inline"><input type="checkbox" name="p_cats[]" value="{$c.id_pulse_pos_category}"> {$c.name}</label>{/foreach} <button name="savePeriod" class="btn btn-default">Save</button></form></div></div>
<div class="tab-pane" id="m-disc"><div class="row"><div class="col-md-6"><div class="panel"><h3>Discounts</h3><table class="table table-condensed"><tbody>{foreach $discounts as $d}<tr><td>{$d.name}</td><td>{$d.value}{if $d.type=='pct'}%{/if}</td><td>{$d.scope}</td><td>{if $d.requires_manager}manager{/if}</td></tr>{/foreach}</tbody></table><form method="post" class="form-inline"><input name="dname" class="form-control" placeholder="Name"> <select name="dtype" class="form-control"><option value="pct">%</option><option value="amount">amount</option></select> <input name="dvalue" class="form-control" placeholder="value (0 = ask)" style="width:110px"> <select name="dscope" class="form-control"><option value="check">check</option><option value="item">item</option></select> <label><input type="checkbox" name="dmgr" value="1"> manager</label> <button name="saveDiscount" class="btn btn-default">Add</button></form></div></div>
<div class="col-md-6"><div class="panel"><h3>Reason codes</h3><table class="table table-condensed"><tbody>{foreach $reasons as $r}<tr><td>{$r.type}</td><td>{$r.name}</td></tr>{/foreach}</tbody></table><form method="post" class="form-inline"><select name="rtype" class="form-control"><option>void</option><option>discount</option><option>comp</option><option>refund</option><option>waste</option><option>no_sale</option></select> <input name="rname" class="form-control" placeholder="Reason"> <button name="saveReason" class="btn btn-default">Add</button></form></div></div></div></div>
<div class="tab-pane" id="m-imp"><div class="panel"><h3>Import menu from CSV</h3><p>Columns: <code>plu, name, category, price1, price2, station</code> (header row required). Existing PLUs are updated.</p><form method="post" enctype="multipart/form-data"><input type="file" name="csv" accept=".csv"> <button name="importCsv" class="btn btn-default">Import</button></form></div></div>
</div></div>
