<div class="pulse-pos"><div class="panel"><h3><i class="icon-cutlery"></i> F&amp;B POS — {$business_date}
<span class="pull-right"><a class="btn btn-primary btn-sm" href="{$pos_url}" target="_blank"><i class="icon-tablet"></i> Open POS terminal</a> <a class="btn btn-default btn-sm" href="{$kds_url}" target="_blank"><i class="icon-desktop"></i> Kitchen display</a> <a class="btn btn-default btn-sm" href="{$links.menu}">Menu</a> <a class="btn btn-default btn-sm" href="{$links.inv}">Inventory</a> <a class="btn btn-default btn-sm" href="{$links.rep}">Reports</a> <a class="btn btn-default btn-sm" href="{$links.set}">Settings</a></span></h3>
<div class="row kpis"><div class="col-md-2"><span>{$cur}{$summary.net_sales|number_format:0}</span>Sales today</div><div class="col-md-2"><span>{$summary.checks}</span>Checks</div><div class="col-md-2"><span>{$summary.covers}</span>Covers</div><div class="col-md-2"><span>{$cur}{$summary.avg_check|number_format:0}</span>Avg check</div><div class="col-md-2"><span>{$cur}{$summary.discounts|number_format:0}</span>Discounts</div><div class="col-md-2"><span>{$open|count}</span>Open checks</div></div>
<table class="table table-condensed"><thead><tr><th>Outlet</th><th>Type</th><th>Sales today</th><th>Open checks</th><th>Open sessions</th><th>Service charge</th></tr></thead><tbody>{foreach $outlets as $o}<tr><td><strong>{$o.name}</strong> <small>{$o.code}</small></td><td>{$o.type|replace:'_':' '}</td><td>{$cur}{$o.sales_today|number_format:0}</td><td>{$o.open_checks}</td><td>{$o.open_sessions}</td><td>{$o.service_charge_pct}%</td></tr>{/foreach}</tbody></table></div>
<div class="row"><div class="col-md-7"><div class="panel"><h3>Open checks</h3><table class="table table-condensed"><thead><tr><th>Check</th><th>Outlet</th><th>Where</th><th>Server</th><th>Cov</th><th class="text-right">Total</th><th>Age</th><th>Status</th><th></th></tr></thead><tbody>{foreach $open as $c}<tr class="{if $c.minutes>120}warning{/if}"><td>{$c.check_no}</td><td>{$c.outlet}</td><td>{$c.table_code|default:$c.order_type}{if $c.room_num} Rm {$c.room_num}{/if}</td><td>{$c.server}</td><td>{$c.covers}</td><td class="text-right">{$cur}{$c.total|number_format:0}</td><td>{$c.minutes}m</td><td>{$c.status}</td><td><form method="post" class="inline"><input type="hidden" name="id_check" value="{$c.id_pulse_pos_check}"><button name="forceClose" class="btn btn-xs btn-danger" onclick="return confirm('Void this check?')">Void</button></form></td></tr>{foreachelse}<tr><td colspan="9"><em>No open checks</em></td></tr>{/foreach}</tbody></table></div>
<div class="panel"><h3>Cashier sessions today</h3><table class="table table-condensed"><thead><tr><th>Outlet</th><th>Cashier</th><th>Opened</th><th>Float</th><th>Expected</th><th>Counted</th><th>Variance</th><th>Z</th><th>Status</th><th></th></tr></thead><tbody>{foreach $sessions as $s}<tr class="{if $s.variance && $s.variance|abs>0}warning{/if}"><td>{$s.outlet}</td><td>{$s.cashier}</td><td>{$s.date_open|date_format:"%H:%M"}</td><td>{$s.opening_float}</td><td>{$s.expected_cash}</td><td>{$s.counted_cash}</td><td>{$s.variance}</td><td>{$s.z_number}</td><td>{$s.status}</td><td>{if $s.status=='open'}<form method="post" class="form-inline"><input type="hidden" name="id_session" value="{$s.id_pulse_pos_session}"><input name="counted" class="input-xs" placeholder="counted" style="width:80px"> <button name="forceSession" class="btn btn-xs btn-default">Close</button></form>{/if}</td></tr>{/foreach}</tbody></table></div></div>
<div class="col-md-5"><div class="panel"><h3>Kitchen now ({$kds|count} tickets)</h3><ul>{foreach $kds as $t}<li class="{if $t.late}text-danger{/if}"><strong>{$t.where}</strong> {$t.kot} · {$t.age}m · {$t.lines|count} item(s)</li>{foreachelse}<li><em>Kitchen clear</em></li>{/foreach}</ul></div>
<div class="panel"><h3>Clocked in</h3><ul>{foreach $clocked as $c}<li>{$c.name} — {$c.outlet} since {$c.clock_in|date_format:"%H:%M"}</li>{foreachelse}<li><em>Nobody clocked in</em></li>{/foreach}</ul></div>
{if $fd}<div class="panel"><h3>Guest meal plans (in house)</h3><table class="table table-condensed"><tbody>{foreach $meal_plans as $m}<tr><td>Rm {$m.room_num}</td><td>{$m.guest}</td><td>{$m.plan} × {$m.persons}</td><td>B {$m.breakfast|number_format:0} / L {$m.lunch|number_format:0} / D {$m.dinner|number_format:0}</td><td>{$m.date_to}</td></tr>{foreachelse}<tr><td><em>None</em></td></tr>{/foreach}</tbody></table><form method="post" class="form-inline"><input name="mp_room" class="form-control" placeholder="Room" style="width:70px"> <select name="mp_plan" class="form-control"><option>BB</option><option>HB</option><option>FB</option><option>AI</option><option>CUSTOM</option></select> <input name="mp_persons" class="form-control" value="1" style="width:50px"> <input name="mp_b" class="form-control" placeholder="B ₦" style="width:80px"> <input name="mp_l" class="form-control" placeholder="L ₦" style="width:80px"> <input name="mp_d" class="form-control" placeholder="D ₦" style="width:80px"> <button name="saveMealPlan" class="btn btn-default btn-sm">Save</button></form><p class="help-block">Allowance per person per meal per day; settled at the POS with the Package tender. Leave amounts blank for the plan defaults.</p></div>{/if}
{if $low}<div class="panel"><h3 class="text-danger">Ingredients below reorder level</h3><ul>{foreach $low as $l}<li>{$l.name}: {$l.qty_on_hand} {$l.unit} (reorder {$l.reorder_level})</li>{/foreach}</ul></div>{/if}</div></div></div>
