<?php
/** /pulse/api/pos/{resource}/{id}. Auth: staff session token (from `login`) in X-Pos-Session header, or a Pulse API token (scopes pos|portal|kds). */
require_once _PS_MODULE_DIR_.'pulsecore/classes/PulseApiController.php';
require_once _PS_MODULE_DIR_.'pulsepos/classes/autoload.php';
class PulsePosApiModuleFrontController extends PulseApiController
{
    protected $emp = 0; protected $staff = null; protected $body = array();
    protected $resources = array('ping' => 'ping', 'login' => 'login', 'logout' => 'logout', 'clock' => 'clock', 'menu' => 'menu', 'tables' => 'tables', 'checks' => 'checks', 'check' => 'check', 'open' => 'open', 'line' => 'line', 'void_line' => 'voidLine', 'send' => 'send', 'fire' => 'fire', 'update' => 'update', 'discount' => 'discount', 'comp' => 'comp', 'transfer' => 'transfer', 'merge' => 'merge', 'split' => 'split', 'print' => 'printCheck', 'pay' => 'pay', 'refund' => 'refund', 'void_check' => 'voidCheck', 'reopen' => 'reopen', 'session' => 'session', 'session_open' => 'sessionOpen', 'session_move' => 'sessionMove', 'session_close' => 'sessionClose', 'x_report' => 'xReport', 'room' => 'room', 'companies' => 'companies', 'eightysix' => 'eightysix', 'kds' => 'kds', 'bump' => 'bump', 'bump_ticket' => 'bumpTicket', 'closed' => 'closed', 'portal_menu' => 'portalMenu', 'portal_order' => 'portalOrder', 'portal_status' => 'portalStatus', 'drawer' => 'drawer', 'guests' => 'guests', 'allowance' => 'allowance', 'delivered' => 'delivered', 'replay' => 'replay', 'requisitions' => 'requisitions', 'requisition' => 'requisition');
    protected function authenticate()
    {
        $res = Tools::getValue('resource', 'ping'); $this->body = json_decode(Tools::file_get_contents('php://input'), true) ?: array();
        if (file_exists(_PS_MODULE_DIR_.'pulselicense/classes/PulseLicenseService.php') && Module::isEnabled('pulselicense')) { require_once _PS_MODULE_DIR_.'pulselicense/classes/PulseLicenseService.php'; PulseLicenseService::assertApi(); if (!PulseLicenseService::entitled('pulsepos')) { throw new PrestaShopException('POS not licensed', 402); } }
        if (in_array($res, array('ping', 'login'))) { return; }
        $sess = isset($_SERVER['HTTP_X_POS_SESSION']) ? $_SERVER['HTTP_X_POS_SESSION'] : Tools::getValue('pos_session');
        if ($sess) { $emp = (int) PulseCoreService::setting('pulsepos', 'sess_'.substr(preg_replace('/[^a-f0-9]/', '', $sess), 0, 40)); if ($emp) { $this->emp = $emp; $this->staff = PulsePosService::staff($emp); if ($this->staff) { return; } } throw new PrestaShopException('Session expired', 401); }
        parent::authenticate(); // API token path (portal / kds / integrations)
        $this->emp = (int) Configuration::get('PS_CRON_EMPLOYEE_ID') ?: 1;
    }
    protected function need($flag) { if (!$this->staff || empty($this->staff[$flag])) { throw new PrestaShopException('Not permitted: '.$flag, 403); } }
    protected function ping() { return array('module' => 'pulsepos', 'business_date' => PulsePosService::bd()); }
    protected function login($id, $b) { $s = PulsePosService::login($b['pin'], (int) $b['id_outlet']); if (!$s) { throw new PrestaShopException('Wrong PIN', 401); } $tok = bin2hex(Tools::passwdGen(20)); PulseCoreService::setting('pulsepos', 'sess_'.substr($tok, 0, 40), (string) $s['id_employee']); $sess = PulsePosService::currentSession((int) $b['id_outlet'], $s['id_employee']); if (!Db::getInstance()->getValue('SELECT id_pulse_pos_clock FROM `'._DB_PREFIX_.'pulse_pos_clock` WHERE id_employee='.(int) $s['id_employee'].' AND clock_out IS NULL')) { Db::getInstance()->insert('pulse_pos_clock', array('id_employee' => (int) $s['id_employee'], 'id_pulse_pos_outlet' => (int) $b['id_outlet'], 'clock_in' => date('Y-m-d H:i:s'), 'business_date' => PulsePosService::bd())); } return array('session' => $tok, 'staff' => $s, 'cash_session' => $sess, 'business_date' => PulsePosService::bd()); }
    protected function logout($id, $b) { if (!empty($b['clock_out'])) { Db::getInstance()->update('pulse_pos_clock', array('clock_out' => date('Y-m-d H:i:s')), 'id_employee='.(int) $this->emp.' AND clock_out IS NULL'); } return array('ok' => 1); }
    protected function clock() { return Db::getInstance()->executeS('SELECT c.*, CONCAT(e.firstname," ",e.lastname) name FROM `'._DB_PREFIX_.'pulse_pos_clock` c INNER JOIN `'._DB_PREFIX_.'employee` e ON e.id_employee=c.id_employee WHERE c.clock_out IS NULL'); }
    protected function menu($id) { return PulsePosService::menu($id); }
    protected function tables($id) { return PulsePosService::tables($id); }
    protected function checks($id) { return PulsePosService::openChecks($id, Tools::getValue('mine') ? $this->emp : null); }
    protected function check($id) { $c = PulsePosService::get($id); if (!$c) { throw new PrestaShopException('Not found', 404); } return $c; }
    protected function open($id, $b) { $b['id_employee'] = $this->emp; $id = PulsePosService::open($b); return PulsePosService::get($id); }
    protected function line($id, $b) { PulsePosService::addLine($id, (int) $b['id_item'], (float) (isset($b['qty']) ? $b['qty'] : 1), isset($b['mods']) ? $b['mods'] : array(), isset($b['seat']) ? $b['seat'] : 1, isset($b['note']) ? $b['note'] : '', $this->emp, isset($b['open_price']) ? $b['open_price'] : null); return PulsePosService::get($id); }
    protected function voidLine($id, $b) { PulsePosService::voidLine($id, $b['reason'], $this->emp, $this->auth($b)); $l = Db::getInstance()->getValue('SELECT id_pulse_pos_check FROM `'._DB_PREFIX_.'pulse_pos_check_line` WHERE id_pulse_pos_check_line='.(int) $id); return PulsePosService::get($l); }
    protected function send($id, $b) { PulsePosService::send($id, $this->emp, isset($b['course']) ? $b['course'] : null); return PulsePosService::get($id); }
    protected function fire($id, $b) { PulsePosService::fireCourse($id, (int) $b['course'], $this->emp); return PulsePosService::get($id); }
    protected function update($id, $b) { PulsePosService::update($id, $b, $this->emp); return PulsePosService::get($id); }
    protected function discount($id, $b) { PulsePosService::discount($id, (int) $b['id_discount'], isset($b['reason']) ? $b['reason'] : '', $this->emp, $this->auth($b), isset($b['value']) ? $b['value'] : null, isset($b['id_line']) ? $b['id_line'] : null); return PulsePosService::get($id); }
    protected function comp($id, $b) { PulsePosService::comp($id, $b['reason'], $this->emp, $this->auth($b), isset($b['id_line']) ? $b['id_line'] : null); return PulsePosService::get($id); }
    protected function transfer($id, $b) { if (!empty($b['id_table'])) { PulsePosService::transferTable($id, (int) $b['id_table'], $this->emp); } if (!empty($b['id_server'])) { PulsePosService::transferServer($id, (int) $b['id_server'], $this->emp); } return PulsePosService::get($id); }
    protected function merge($id, $b) { PulsePosService::merge((int) $b['id_from'], $id, $this->emp); return PulsePosService::get($id); }
    protected function split($id, $b) { $ids = PulsePosService::split($id, $this->emp, isset($b['lines']) ? $b['lines'] : array(), isset($b['seat']) ? $b['seat'] : null, isset($b['ways']) ? (int) $b['ways'] : null, isset($b['amount']) ? $b['amount'] : null); return array('new' => $ids, 'check' => PulsePosService::get($id)); }
    protected function printCheck($id) { return array('text' => PulsePosService::printCheck($id, $this->emp), 'check' => PulsePosService::get($id)); }
    protected function pay($id, $b) { $r = PulsePosPayment::pay($id, $b['method'], (float) $b['amount'], $this->emp, $b + array('auth' => $this->auth($b))); $r['check'] = PulsePosService::get($id); if ($r['settled']) { $r['receipt'] = PulsePosPrinter::receipt($r['check'], true); if ($b['method'] === 'cash' && Configuration::get('PULSE_POS_DRAWER_HOST')) { PulsePosPrinter::cashDrawer(Configuration::get('PULSE_POS_DRAWER_HOST'), 9100); } if (Configuration::get('PULSE_POS_RECEIPT_HOST')) { PulsePosPrinter::raw(Configuration::get('PULSE_POS_RECEIPT_HOST'), 9100, PulsePosPrinter::esc($r['receipt'])); } } return $r; }
    protected function refund($id, $b) { PulsePosPayment::refund($id, (float) $b['amount'], $b['method'], $b['reason'], $this->emp, $this->auth($b)); return PulsePosService::get($id); }
    protected function voidCheck($id, $b) { PulsePosService::voidCheck($id, $b['reason'], $this->emp, $this->auth($b)); return array('ok' => 1); }
    protected function reopen($id, $b) { PulsePosService::reopen($id, $this->emp, $this->auth($b)); return PulsePosService::get($id); }
    protected function session($id) { $s = PulsePosService::currentSession($id, $this->emp); return $s ? PulsePosService::sessionReport($s) : null; }
    protected function sessionOpen($id, $b) { return array('id' => PulsePosService::openSession($id, $this->emp, (float) $b['float'])); }
    protected function sessionMove($id, $b) { PulsePosService::sessionMove($id, $b['type'], (float) $b['amount'], isset($b['reason']) ? $b['reason'] : '', $this->emp); return PulsePosService::sessionReport($id); }
    protected function sessionClose($id, $b) { return array('z' => PulsePosService::closeSession($id, (float) $b['counted'], isset($b['note']) ? $b['note'] : '', $this->emp)); }
    protected function xReport($id) { $r = PulsePosService::sessionReport($id); if ($this->staff && !in_array($this->staff['role'], array('manager', 'supervisor')) && Configuration::get('PULSE_POS_BLIND_CLOSE')) { unset($r['expected_cash_calc'], $r['payments'], $r['expected_cash']); $r['blind'] = 1; } return $r; }
    protected function guests($id, $b) { return PulsePosService::findGuests(isset($b['name']) ? $b['name'] : Tools::getValue('name')); }
    protected function allowance($id, $b) { $r = isset($b['room_num']) ? PulsePosService::findRoom($b['room_num']) : PulsePosService::roomGuest($id); if (!$r) { throw new PrestaShopException('No in-house guest', 404); } $c = isset($b['id_check']) ? PulsePosService::get((int) $b['id_check'], false) : null; return array('room' => $r, 'meal' => PulsePosMealPlan::mealNow(), 'allowance' => PulsePosMealPlan::allowance($r['id_htl_booking'], isset($b['meal']) && $b['meal'] ? $b['meal'] : PulsePosMealPlan::mealNow(), PulsePosService::bd(), $c ? $c['id_pulse_pos_outlet'] : null)); }
    protected function delivered($id) { PulsePosService::update($id, array('delivered' => 1), $this->emp); return PulsePosService::get($id); }
    /** Offline replay: each queued action carries a client_id; duplicates are ignored so a retried queue never double-posts. */
    protected function replay($id, $b) { $out = array(); foreach ((array) $b['actions'] as $a) { if (Db::getInstance()->getValue('SELECT id_pulse_pos_offline_log FROM `'._DB_PREFIX_.'pulse_pos_offline_log` WHERE client_id="'.pSQL($a['client_id']).'"')) { $out[] = array('client_id' => $a['client_id'], 'status' => 'duplicate'); continue; } $res = 'ok'; try { $m = $this->resources[$a['resource']]; $this->$m((int) $a['id'], $a['body']); } catch (Exception $e) { $res = 'error: '.$e->getMessage(); } Db::getInstance()->insert('pulse_pos_offline_log', array('client_id' => pSQL($a['client_id']), 'action' => pSQL($a['resource']), 'payload' => pSQL(json_encode($a['body']), true), 'result' => pSQL($res), 'replayed_at' => date('Y-m-d H:i:s'))); $out[] = array('client_id' => $a['client_id'], 'status' => $res); } return $out; }
    protected function requisitions() { return Db::getInstance()->executeS('SELECT * FROM `'._DB_PREFIX_.'pulse_pos_requisition` WHERE status<>"issued" ORDER BY id_pulse_pos_requisition DESC'); }
    protected function requisition($id, $b) { return array('req_no' => PulsePosInventory::requisition(isset($b['from']) ? $b['from'] : 'main', $b['to'], $b['lines'], isset($b['note']) ? $b['note'] : '', $this->emp)); }
    protected function room($id, $b) { $r = PulsePosService::findRoom(isset($b['room_num']) ? $b['room_num'] : Tools::getValue('room_num')); if (!$r) { throw new PrestaShopException('No in-house guest in that room', 404); } if (Configuration::get('PULSE_POS_ROOM_GUEST_CHECK')) { $r['guest_masked'] = preg_replace('/(?<=\S)\S(?=\S*\s)/u', '*', $r['guest']); } return $r; }
    protected function companies() { return class_exists('PulseCompany') ? Db::getInstance()->executeS('SELECT id_pulse_company id, name, credit_limit, ledger_balance FROM `'._DB_PREFIX_.'pulse_company` WHERE active=1 ORDER BY name') : array(); }
    protected function eightysix($id, $b) { if (!$this->staff || !in_array($this->staff['role'], array('supervisor', 'manager', 'kitchen', 'bartender'))) { throw new PrestaShopException('Not permitted', 403); } Db::getInstance()->update('pulse_pos_item', array('available' => (int) !empty($b['available']), 'count_down' => isset($b['count']) && $b['count'] !== '' ? (int) $b['count'] : null), 'id_pulse_pos_item='.(int) $id); return array('ok' => 1); }
    protected function kds($id) { if (!$this->staff) { $this->requireScope('kds'); } return PulsePosKitchen::queue($id ?: null); }
    protected function bump($id, $b) { PulsePosKitchen::bump($id, $b['status']); return array('ok' => 1); }
    protected function bumpTicket($id, $b) { PulsePosKitchen::bumpTicket($b['kot'], $id, $b['status']); return array('ok' => 1); }
    protected function closed($id) { return Db::getInstance()->executeS('SELECT c.id_pulse_pos_check id, c.check_no, c.table_code, c.total, c.paid, c.status, c.date_settled, CONCAT(e.firstname," ",LEFT(e.lastname,1)) server FROM `'._DB_PREFIX_.'pulse_pos_check` c LEFT JOIN `'._DB_PREFIX_.'employee` e ON e.id_employee=c.id_server WHERE c.id_pulse_pos_outlet='.(int) $id.' AND c.status IN ("settled","void") AND c.business_date="'.pSQL(PulsePosService::bd()).'" ORDER BY c.date_upd DESC LIMIT 50'); }
    protected function drawer() { if (Configuration::get('PULSE_POS_DRAWER_HOST')) { PulsePosPrinter::cashDrawer(Configuration::get('PULSE_POS_DRAWER_HOST'), 9100); } PulsePosService::audit(null, 'no_sale', '', null, $this->emp); return array('ok' => 1); }
    /* TV / mobile portal (scope portal): in-room dining */
    protected function portalMenu() { $this->requireScope('portal'); $o = (int) Db::getInstance()->getValue('SELECT id_pulse_pos_outlet FROM `'._DB_PREFIX_.'pulse_pos_outlet` WHERE type="room_service" AND active=1'); $m = PulsePosService::menu($o); return array('categories' => $m['categories'], 'items' => array_values(array_filter($m['items'], function ($i) { return $i['avail']; })), 'modifiers' => $m['modifiers']); }
    protected function portalOrder($idRoom, $b) { $this->requireScope('portal'); $o = (int) Db::getInstance()->getValue('SELECT id_pulse_pos_outlet FROM `'._DB_PREFIX_.'pulse_pos_outlet` WHERE type="room_service" AND active=1'); $emp = (int) Db::getInstance()->getValue('SELECT id_employee FROM `'._DB_PREFIX_.'pulse_pos_staff` WHERE role="manager" AND active=1 LIMIT 1') ?: 1; $id = PulsePosService::open(array('id_outlet' => $o, 'order_type' => 'room_service', 'id_room' => $idRoom, 'id_employee' => $emp, 'guest_name' => '')); foreach ((array) $b['lines'] as $l) { PulsePosService::addLine($id, (int) $l['id_item'], (float) (isset($l['qty']) ? $l['qty'] : 1), isset($l['mods']) ? $l['mods'] : array(), 1, isset($l['note']) ? 'TV order: '.$l['note'] : 'TV order', $emp); } PulsePosService::send($id, $emp); return array('id_check' => $id, 'check_no' => PulsePosService::get($id, false)['check_no']); }
    protected function portalStatus($idRoom) { $this->requireScope('portal'); return Db::getInstance()->executeS('SELECT c.check_no, c.total, c.status, c.date_add, (SELECT GROUP_CONCAT(DISTINCT l.kot_status) FROM `'._DB_PREFIX_.'pulse_pos_check_line` l WHERE l.id_pulse_pos_check=c.id_pulse_pos_check AND l.voided=0) kitchen FROM `'._DB_PREFIX_.'pulse_pos_check` c WHERE c.id_room='.(int) $idRoom.' AND c.date_add>=DATE_SUB(NOW(), INTERVAL 1 DAY) ORDER BY c.date_add DESC'); }
    protected function auth(array $b) { if (empty($b['auth_pin'])) { return null; } $c = Db::getInstance()->getRow('SELECT id_pulse_pos_outlet FROM `'._DB_PREFIX_.'pulse_pos_check` WHERE id_pulse_pos_check='.(int) Tools::getValue('id')); $s = PulsePosService::login($b['auth_pin'], $c ? (int) $c['id_pulse_pos_outlet'] : 0); if (!$s) { throw new PrestaShopException('Authorising PIN not recognised', 403); } return (int) $s['id_employee']; }
}
