<div class="pulse-mnt"><div class="panel"><h3><i class="icon-wrench"></i> Maintenance — work orders <span class="pull-right"><a class="btn btn-sm {if $mine}btn-primary{else}btn-default{/if}" href="{$self_url}&mine=1">My work orders</a> <a class="btn btn-sm {if !$mine}btn-primary{else}btn-default{/if}" href="{$self_url}">All</a></span></h3>
<div class="row kpis"><div class="col-md-2"><span>{$kpi.open_now|default:0}</span>Open now</div><div class="col-md-2"><span>{$kpi.closed|default:0}/{$kpi.total|default:0}</span>Closed / raised</div><div class="col-md-2"><span>{$kpi.mttr_hours|default:'—'} h</span>Mean time to repair</div><div class="col-md-2"><span>{$kpi.sla_breached|default:0}</span>SLA breached</div><div class="col-md-2"><span>{$kpi.preventive|default:0}:{$kpi.corrective|default:0}</span>PM : corrective</div><div class="col-md-2"><span>{displayPrice price=$kpi.cost|default:0}</span>Cost</div></div>
<ul class="nav nav-tabs"><li class="active"><a data-toggle="tab" href="#m-q">Queue ({$queue|count})</a></li><li><a data-toggle="tab" href="#m-new">New work order</a></li><li><a data-toggle="tab" href="#m-done">Recently closed</a></li><li><a data-toggle="tab" href="#m-rep">Reports</a></li></ul>
<div class="tab-content">
<div class="tab-pane active" id="m-q"><form method="post"><table class="table"><thead><tr><th><input type="checkbox" onclick="$('input[name=\'wo_ids[]\']').prop('checked',this.checked)"></th><th>WO</th><th>Pri</th><th>Type</th><th>Where</th><th>Subject</th><th>Technician</th><th>Due</th><th>Status</th><th></th></tr></thead><tbody>
{foreach $queue as $w}<tr class="{if $w.priority=='emergency'}danger{elseif $w.overdue}warning{/if}"><td><input type="checkbox" name="wo_ids[]" value="{$w.id_pulse_work_order}"></td><td><a href="{$self_url}&id_wo={$w.id_pulse_work_order}">{$w.wo_no}</a></td><td><span class="label label-{if $w.priority=='emergency'}danger{elseif $w.priority=='high'}warning{else}default{/if}">{$w.priority}</span></td><td>{$w.type}<br><small>{$w.category}</small></td><td>{if $w.room_num}Rm {$w.room_num}{/if} {$w.asset_name} {$w.location} {if $w.room_ooo}<span class="label label-default">OOO</span>{/if}</td><td>{$w.subject}</td><td>{$w.technician|default:'—'}</td><td>{$w.due_at|date_format:"%d/%m %H:%M"}{if $w.overdue} <i class="icon-warning"></i>{/if}</td><td>{$w.status|replace:'_':' '}</td>
<td>{if $w.status=='open' || $w.status=='assigned'}<button name="setStatus" class="btn btn-xs btn-default" formaction="{$self_url}&id_wo_s={$w.id_pulse_work_order}&status=in_progress">Start</button>{/if}{if $w.status=='in_progress'}<a class="btn btn-xs btn-success" href="{$self_url}&id_wo={$w.id_pulse_work_order}">Complete…</a>{/if}</td></tr>{foreachelse}<tr><td colspan="10"><em>No open work orders</em></td></tr>{/foreach}</tbody></table>
<div class="form-inline"><select name="assigned_to" class="form-control">{foreach $techs as $t}<option value="{$t.id_employee}">{$t.firstname} {$t.lastname}</option>{/foreach}</select> <button name="bulkAssign" class="btn btn-default">Assign selected</button></div></form></div>
<div class="tab-pane" id="m-new"><form method="post" class="form-horizontal"><div class="row"><div class="col-md-6">
<div class="form-group"><label class="col-sm-3">Subject</label><div class="col-sm-9"><input name="subject" class="form-control" required></div></div>
<div class="form-group"><label class="col-sm-3">Description</label><div class="col-sm-9"><textarea name="description" class="form-control" rows="3"></textarea></div></div>
<div class="form-group"><label class="col-sm-3">Type / Category</label><div class="col-sm-4"><select name="type" class="form-control"><option>corrective</option><option>preventive</option><option>inspection</option><option>project</option><option>safety</option></select></div><div class="col-sm-5"><select name="category" class="form-control">{foreach $categories as $c}<option>{$c}</option>{/foreach}</select></div></div>
<div class="form-group"><label class="col-sm-3">Priority</label><div class="col-sm-9"><select name="priority" class="form-control"><option value="emergency">Emergency (2h)</option><option value="high">High (8h)</option><option value="normal" selected>Normal (24h)</option><option value="low">Low (72h)</option></select></div></div></div>
<div class="col-md-6">
<div class="form-group"><label class="col-sm-3">Room</label><div class="col-sm-9"><select name="id_room" class="form-control"><option value="">—</option>{foreach $rooms as $r}<option value="{$r.id_room}">{$r.room_num}</option>{/foreach}</select><label><input type="checkbox" name="room_ooo" value="1"> Put room out of order until fixed</label></div></div>
<div class="form-group"><label class="col-sm-3">Asset</label><div class="col-sm-9"><select name="id_pulse_asset" class="form-control"><option value="">—</option>{foreach $assets as $a}<option value="{$a.id_pulse_asset}">{$a.code} {$a.name}</option>{/foreach}</select><label><input type="checkbox" name="asset_oos" value="1"> Asset out of service</label></div></div>
<div class="form-group"><label class="col-sm-3">Location</label><div class="col-sm-9"><input name="location" class="form-control" placeholder="Lobby, plant room, pool…"></div></div>
<div class="form-group"><label class="col-sm-3">Assign to</label><div class="col-sm-9"><select name="assigned_to" class="form-control"><option value="">Unassigned</option>{foreach $techs as $t}<option value="{$t.id_employee}">{$t.firstname} {$t.lastname}</option>{/foreach}</select></div></div>
<button name="createWo" class="btn btn-primary btn-lg pull-right">Raise work order</button></div></div></form></div>
<div class="tab-pane" id="m-done"><table class="table table-condensed"><tbody>{foreach $recent as $w}<tr><td><a href="{$self_url}&id_wo={$w.id_pulse_work_order}">{$w.wo_no}</a></td><td>{$w.subject}</td><td>{$w.room_num} {$w.asset_name}</td><td>{$w.technician}</td><td>{$w.date_completed}</td><td>{$w.status}</td>{if $w.status=='completed'}<td><form method="post" class="inline"><button name="setStatus" class="btn btn-xs btn-default" formaction="{$self_url}&id_wo_s={$w.id_pulse_work_order}&status=verified">Verify</button></form></td>{/if}</tr>{/foreach}</tbody></table></div>
<div class="tab-pane" id="m-rep"><form method="get" class="form-inline"><input type="hidden" name="controller" value="AdminPulseMaintenance"><input type="hidden" name="token" value="{$smarty.get.token|escape}"><input type="date" name="from" value="{$from}" class="form-control"> <input type="date" name="to" value="{$to}" class="form-control"> <button class="btn btn-default">Run</button></form>
<div class="row"><div class="col-md-6"><h4>By category</h4><table class="table table-condensed"><thead><tr><th>Category</th><th>WOs</th><th>MTTR h</th><th>Cost</th></tr></thead><tbody>{foreach $by_cat as $r}<tr><td>{$r.category}</td><td>{$r.n}</td><td>{$r.mttr_h}</td><td>{displayPrice price=$r.cost}</td></tr>{/foreach}</tbody></table>
<h4>Technicians</h4><table class="table table-condensed"><thead><tr><th>Technician</th><th>WOs</th><th>Done</th><th>MTTR h</th><th>Minutes</th></tr></thead><tbody>{foreach $by_tech as $r}<tr><td>{$r.technician}</td><td>{$r.n}</td><td>{$r.done}</td><td>{$r.mttr_h}</td><td>{$r.minutes}</td></tr>{/foreach}</tbody></table></div>
<div class="col-md-6"><h4>Problem rooms</h4><table class="table table-condensed"><thead><tr><th>Room</th><th>WOs</th><th>OOO events</th><th>Cost</th></tr></thead><tbody>{foreach $by_room as $r}<tr><td>{$r.room_num}</td><td>{$r.n}</td><td>{$r.ooo_events}</td><td>{displayPrice price=$r.cost}</td></tr>{/foreach}</tbody></table>
<h4>Problem assets</h4><table class="table table-condensed"><thead><tr><th>Asset</th><th>WOs</th><th>Cost</th></tr></thead><tbody>{foreach $by_asset as $r}<tr><td>{$r.code} {$r.name}</td><td>{$r.n}</td><td>{displayPrice price=$r.cost}</td></tr>{/foreach}</tbody></table>
{if $low_stock}<h4 class="text-danger">Parts below reorder level</h4><ul>{foreach $low_stock as $p}<li>{$p.sku} {$p.name}: {$p.qty_on_hand} {$p.unit} (reorder at {$p.reorder_level})</li>{/foreach}</ul>{/if}</div></div></div>
</div></div></div>
