<div class="pulse-mnt"><div class="panel"><h3>{$w.wo_no} — {$w.subject} <span class="label label-{if $w.priority=='emergency'}danger{elseif $w.priority=='high'}warning{else}default{/if}">{$w.priority}</span> <span class="label label-info">{$w.status|replace:'_':' '}</span> <a class="btn btn-default btn-sm pull-right" href="{$self_url}">Back</a> <a class="btn btn-default btn-sm pull-right" href="javascript:window.print()"><i class="icon-print"></i> Job card</a></h3>
<div class="row"><div class="col-md-6"><p>{$w.type|ucfirst} &middot; {$w.category} &middot; {if $w.room_num}Room {$w.room_num} {if $w.room_ooo}<span class="label label-default">OOO</span>{/if}{/if} {if $w.asset_name}&middot; {$w.asset_code} {$w.asset_name}{/if} {$w.location}<br>Raised {$w.date_add} by {$w.reporter} via {$w.source} {$w.source_ref} &middot; due <strong>{$w.due_at}</strong> ({$w.sla_hours}h SLA) &middot; technician {$w.technician|default:'—'}</p>
<p>{$w.description|nl2br}</p>
{if $w.checklist}<h4>Checklist</h4><ul class="checklist">{foreach explode("\n",$w.checklist) as $c}{if trim($c)}<li><label><input type="checkbox"> {$c}</label></li>{/if}{/foreach}</ul>{/if}
{if $w.resolution}<h4>Resolution</h4><p>{$w.resolution|nl2br}<br><small>Root cause: {$w.root_cause} &middot; labour {$w.labour_minutes} min ({displayPrice price=$w.labour_cost}) &middot; parts {displayPrice price=$w.parts_cost} &middot; vendor {displayPrice price=$w.vendor_cost}</small></p>{/if}
<h4>Parts used</h4><table class="table table-condensed"><tbody>{foreach $w.parts as $p}<tr><td>{$p.sku}</td><td>{$p.name}</td><td>{$p.qty}</td><td>@ {$p.unit_cost}</td></tr>{foreachelse}<tr><td><em>none</em></td></tr>{/foreach}</tbody></table>
{if $w.status!='completed' && $w.status!='verified' && $w.status!='cancelled'}<form method="post" class="form-inline noprint"><input type="hidden" name="id_wo_s" value="{$w.id_pulse_work_order}"><select name="id_part" class="form-control">{foreach $parts as $p}<option value="{$p.id_pulse_part}">{$p.sku} {$p.name} ({$p.qty_on_hand} {$p.unit})</option>{/foreach}</select> <input name="qty" type="number" step="0.01" value="1" class="form-control" style="width:80px"> <button name="issuePart" class="btn btn-default btn-sm">Issue part</button></form>{/if}</div>
<div class="col-md-6 noprint"><h4>Timeline</h4><ul class="timeline">{foreach $w.notes as $n}<li><small>{$n.date_add} — {$n.who}</small><br>{$n.note|nl2br}{if $n.photo_path} <a href="{$n.photo_path}" target="_blank">photo</a>{/if}</li>{/foreach}</ul>
<form method="post" class="form-inline"><input type="hidden" name="id_wo_s" value="{$w.id_pulse_work_order}"><input name="note" class="form-control" placeholder="Add note" style="width:70%"> <button name="addNote" class="btn btn-default btn-sm">Add</button></form>
<hr><form method="post"><input type="hidden" name="id_wo_s" value="{$w.id_pulse_work_order}">
{if $w.status=='open' || $w.status=='assigned'}<div class="form-inline"><select name="assigned_to" class="form-control">{foreach $techs as $t}<option value="{$t.id_employee}" {if $t.id_employee==$w.assigned_to}selected{/if}>{$t.firstname} {$t.lastname}</option>{/foreach}</select> <button name="assignWo" class="btn btn-default btn-sm">Assign</button> <button name="setStatus" class="btn btn-primary btn-sm" formaction="{$self_url}&id_wo_s={$w.id_pulse_work_order}&status=in_progress">Start work</button></div>{/if}
{if $w.status=='in_progress' || $w.status=='on_hold'}<h4>Complete</h4><textarea name="resolution" class="form-control" rows="2" placeholder="What was done"></textarea><input name="root_cause" class="form-control" placeholder="Root cause"><div class="form-inline"><input name="labour_minutes" type="number" class="form-control" placeholder="Labour minutes"> <input name="vendor_cost" type="number" step="0.01" class="form-control" placeholder="Vendor cost"></div><br>
<button name="setStatus" class="btn btn-success" formaction="{$self_url}&id_wo_s={$w.id_pulse_work_order}&status=completed">Mark completed{if $w.room_ooo} &amp; release room to housekeeping{/if}</button>
{if $w.status=='in_progress'}<div class="form-inline" style="margin-top:6px"><input name="reason" class="form-control" placeholder="Hold reason (waiting parts/vendor)"> <button name="setStatus" class="btn btn-default btn-sm" formaction="{$self_url}&id_wo_s={$w.id_pulse_work_order}&status=on_hold">Put on hold</button></div>{else}<button name="setStatus" class="btn btn-default btn-sm" formaction="{$self_url}&id_wo_s={$w.id_pulse_work_order}&status=in_progress">Resume</button>{/if}{/if}
{if $w.status=='completed'}<button name="setStatus" class="btn btn-primary" formaction="{$self_url}&id_wo_s={$w.id_pulse_work_order}&status=verified">Verify (supervisor)</button>{/if}
{if $w.status!='completed' && $w.status!='verified'}<button name="setStatus" class="btn btn-link btn-sm" formaction="{$self_url}&id_wo_s={$w.id_pulse_work_order}&status=cancelled" onclick="return confirm('Cancel work order?')">Cancel</button>{/if}</form></div></div></div></div>
