<div class="pulse-ldy"><div class="panel"><h3>Laundry order {$o.order_no} <span class="label label-info">{$o.status}</span> <span class="label label-default">{$o.service}</span> <a class="btn btn-default btn-sm pull-right" href="{$self_url}">Back</a> <a class="btn btn-default btn-sm pull-right" href="javascript:window.print()"><i class="icon-print"></i> Ticket</a></h3>
<p>{$o.type|ucfirst} &middot; {if $o.room_num}Room {$o.room_num} &middot; {/if}{$o.guest_name}{if $o.department} &middot; {$o.department}{/if} &middot; promised {$o.promised_at} {if $o.note}<br><em>{$o.note}</em>{/if}</p>
<table class="table"><thead><tr><th>Item</th><th>Process</th><th>Qty</th><th>Unit</th><th>Total</th><th>Condition</th><th class="noprint">Claim</th></tr></thead><tbody>
{foreach $o.lines as $l}<tr class="{if $l.damaged||$l.missing}danger{/if}"><td>{$l.item_name}</td><td>{$l.process}</td><td>{$l.qty}</td><td>{$l.unit_price}</td><td>{$l.line_total}</td><td>{$l.condition_note}{if $l.damaged} DAMAGED{/if}{if $l.missing} MISSING{/if}</td>
<td class="noprint"><form method="post" class="form-inline"><input type="hidden" name="id_order_s" value="{$o.id_pulse_laundry_order}"><input type="hidden" name="id_line" value="{$l.id_pulse_laundry_order_line}"><select name="ctype" class="input-sm"><option>damage</option><option>loss</option><option>quality</option><option>delay</option></select><input name="cdesc" class="input-sm" placeholder="what happened"><input name="camount" class="input-sm" type="number" step="0.01" placeholder="₦" style="width:90px"><button name="addClaim" class="btn btn-xs btn-warning">Log</button></form></td></tr>{/foreach}
<tr><td colspan="4" class="text-right"><strong>Total (tax incl)</strong></td><td colspan="3"><strong>{displayPrice price=$o.total_tax_incl}</strong> {if $o.complimentary}<span class="label label-success">complimentary</span>{/if} {if $o.posted_line}<span class="label label-success">posted to folio</span>{elseif $o.type=='guest' && $fd && $o.id_htl_booking}<form method="post" class="inline"><input type="hidden" name="id_order_s" value="{$o.id_pulse_laundry_order}"><button name="postNow" class="btn btn-xs btn-default noprint">Post to folio now</button></form>{/if}</td></tr></tbody></table>
{if $o.claims}<h4>Claims</h4><ul>{foreach $o.claims as $c}<li>{$c.type}: {$c.description} — claimed {$c.amount_claimed}, {$c.status}{if $c.settled_how} via {$c.settled_how}{/if}</li>{/foreach}</ul>{/if}
<form method="post" class="noprint"><input type="hidden" name="id_order_s" value="{$o.id_pulse_laundry_order}">{foreach ['collected','washing','ready','delivered','cancelled'] as $s}<button name="setStatus" class="btn btn-default btn-sm" formaction="{$self_url}&status={$s}">{$s|ucfirst}</button> {/foreach}</form>
</div></div>
