<div class="pulse-ldy"><div class="panel"><h3><i class="icon-tint"></i> Laundry — {$business_date}</h3>
<ul class="nav nav-tabs"><li class="active"><a data-toggle="tab" href="#l-queue">Queue ({$queue|count})</a></li><li><a data-toggle="tab" href="#l-new">New order</a></li><li><a data-toggle="tab" href="#l-done">Delivered today ({$done|count})</a></li><li><a data-toggle="tab" href="#l-rep">Reports</a></li></ul>
<div class="tab-content">
<div class="tab-pane active" id="l-queue"><table class="table"><thead><tr><th>Order</th><th>Type</th><th>Room / Dept</th><th>Guest</th><th>Service</th><th>Pcs</th><th>Total</th><th>Promised</th><th>Status</th><th></th></tr></thead><tbody>
{foreach $queue as $o}<tr class="{if $o.promised_at < $smarty.now|date_format:'%Y-%m-%d %H:%M:%S' && $o.status!='ready'}danger{elseif $o.service!='normal'}warning{/if}"><td><a href="{$self_url}&id_order={$o.id_pulse_laundry_order}">{$o.order_no}</a></td><td>{$o.type}</td><td>{$o.room_num|default:$o.department}</td><td>{$o.guest_name}</td><td>{$o.service}</td><td>{$o.pieces}</td><td>{displayPrice price=$o.total_tax_incl}</td><td>{$o.promised_at|date_format:"%d/%m %H:%M"}</td><td>{$o.status}</td>
<td><form method="post" class="inline"><input type="hidden" name="id_order_s" value="{$o.id_pulse_laundry_order}">{if $o.status=='requested'}<button name="setStatus" value="collected" class="btn btn-xs btn-default" formaction="{$self_url}&status=collected">Collected</button>{elseif $o.status=='collected'}<button name="setStatus" class="btn btn-xs btn-default" formaction="{$self_url}&status=washing">In wash</button>{elseif $o.status=='washing'}<button name="setStatus" class="btn btn-xs btn-info" formaction="{$self_url}&status=ready">Ready</button>{elseif $o.status=='ready'}<button name="setStatus" class="btn btn-xs btn-success" formaction="{$self_url}&status=delivered">Delivered</button>{/if} <button name="setStatus" class="btn btn-xs btn-link" formaction="{$self_url}&status=cancelled" onclick="return confirm('Cancel order?')">✕</button></form></td></tr>
{foreachelse}<tr><td colspan="10"><em>Nothing in the laundry</em></td></tr>{/foreach}</tbody></table></div>
<div class="tab-pane" id="l-new"><form method="post" class="form-horizontal">
<div class="row"><div class="col-md-4">
<div class="form-group"><label class="col-sm-4">Type</label><div class="col-sm-8"><select name="type" class="form-control" id="ldy-type"><option value="guest">Guest laundry (charge to room)</option><option value="house">House linen</option><option value="uniform">Staff uniform</option><option value="outside">Outside customer</option></select></div></div>
<div class="form-group"><label class="col-sm-4">Room</label><div class="col-sm-8"><select name="id_room" class="form-control"><option value="">—</option>{foreach $rooms as $r}<option value="{$r.id_room}">{$r.room_num}{if isset($r.guest) && $r.guest} — {$r.guest}{/if}</option>{/foreach}</select></div></div>
<div class="form-group"><label class="col-sm-4">Guest / Dept</label><div class="col-sm-8"><input name="guest_name" class="form-control" placeholder="Name (outside customer)"><input name="department" class="form-control" placeholder="Department (house/uniform)"></div></div>
<div class="form-group"><label class="col-sm-4">Service</label><div class="col-sm-8"><select name="service" class="form-control"><option value="normal">Normal</option><option value="express">Express (+{$sur_express}%)</option><option value="same_day">Same day (+{$sur_sameday}%, in by {$cutoff})</option></select></div></div>
<div class="form-group"><label class="col-sm-4">Vendor</label><div class="col-sm-8"><select name="id_vendor" class="form-control"><option value="">In-house</option>{foreach $vendors as $v}<option value="{$v.id_pulse_laundry_vendor}">{$v.name}</option>{/foreach}</select></div></div>
<div class="form-group"><label class="col-sm-4">Note</label><div class="col-sm-8"><input name="note" class="form-control"><label><input type="checkbox" name="complimentary" value="1"> Complimentary (no charge)</label></div></div>
<button name="createOrder" class="btn btn-primary btn-lg">Create order</button></div>
<div class="col-md-8"><table class="table table-condensed"><thead><tr><th>Item</th><th>Wash</th><th>Dry clean</th><th>Press</th><th>Process</th><th>Qty</th><th>Condition</th></tr></thead><tbody>
{foreach $items as $it}<tr><td>{$it.name} <small class="text-muted">{$it.category}</small></td><td>{$it.price_wash}</td><td>{$it.price_dryclean}</td><td>{$it.price_press}</td><td><select name="process[{$it.id_pulse_laundry_item}]" class="input-sm"><option value="wash">wash</option><option value="dryclean">dry clean</option><option value="press">press</option></select></td><td><input name="qty[{$it.id_pulse_laundry_item}]" type="number" min="0" value="0" class="input-sm" style="width:60px"></td><td><input name="cond[{$it.id_pulse_laundry_item}]" class="input-sm" placeholder="stain, tear…"></td></tr>{/foreach}</tbody></table></div></div></form></div>
<div class="tab-pane" id="l-done"><table class="table table-condensed"><tbody>{foreach $done as $o}<tr><td><a href="{$self_url}&id_order={$o.id_pulse_laundry_order}">{$o.order_no}</a></td><td>{$o.room_num}</td><td>{$o.guest_name}</td><td>{$o.pieces} pc</td><td>{displayPrice price=$o.total_tax_incl}</td><td>{$o.status}</td><td>{$o.delivered_at}</td></tr>{/foreach}</tbody></table></div>
<div class="tab-pane" id="l-rep"><form method="get" class="form-inline"><input type="hidden" name="controller" value="AdminPulseLaundry"><input type="hidden" name="token" value="{$smarty.get.token|escape}"><input type="date" name="from" value="{$from}" class="form-control"> <input type="date" name="to" value="{$to}" class="form-control"> <button class="btn btn-default">Run</button></form>
<h4>Guest laundry revenue &amp; turnaround</h4><table class="table table-condensed"><thead><tr><th>Date</th><th>Orders</th><th>Pieces</th><th>Express</th><th>Revenue</th><th>Avg turnaround h</th><th>Late</th></tr></thead><tbody>{foreach $rev as $r}<tr><td>{$r.business_date}</td><td>{$r.orders}</td><td>{$r.pieces}</td><td>{$r.express_orders}</td><td>{displayPrice price=$r.revenue}</td><td>{$r.avg_turnaround_hrs}</td><td>{$r.late}</td></tr>{/foreach}</tbody></table>
<h4>Claims</h4><table class="table table-condensed"><thead><tr><th>Date</th><th>Order</th><th>Guest</th><th>Type</th><th>Claimed</th><th>Settled</th><th>Status</th><th></th></tr></thead><tbody>{foreach $claims as $c}<tr><td>{$c.date_add|date_format:"%d/%m"}</td><td>{$c.order_no}</td><td>{$c.guest_name}</td><td>{$c.type}</td><td>{$c.amount_claimed}</td><td>{$c.amount_settled}</td><td>{$c.status}</td><td>{if $c.status=='open'}<form method="post" class="form-inline"><input type="hidden" name="id_claim" value="{$c.id_pulse_laundry_claim}"><select name="cstatus" class="input-sm"><option value="approved">approve</option><option value="rejected">reject</option><option value="settled">settle</option></select><input name="csettled" class="input-sm" type="number" step="0.01" value="{$c.amount_claimed}" style="width:90px"><select name="chow" class="input-sm"><option value="folio_credit">folio credit</option><option value="cash">cash</option><option value="replacement">replacement</option><option value="none">none</option></select><button name="settleClaim" class="btn btn-xs btn-default">Go</button></form>{/if}</td></tr>{/foreach}</tbody></table></div>
</div></div></div>
