CREATE TABLE IF NOT EXISTS `PREFIX_pulse_inv_store` (
  `id_pulse_inv_store` INT UNSIGNED NOT NULL AUTO_INCREMENT, `code` VARCHAR(16) NOT NULL, `name` VARCHAR(64) NOT NULL,
  `type` ENUM('central','kitchen','bar','housekeeping','floor_pantry','minibar','front_office','engineering','laundry','other') NOT NULL DEFAULT 'other',
  `department` ENUM('fnb','housekeeping','rooms','admin','maintenance','laundry','general') NOT NULL DEFAULT 'general', `id_employee_keeper` INT UNSIGNED, `allow_negative` TINYINT(1) NOT NULL DEFAULT 0, `active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_pulse_inv_store`), UNIQUE KEY `code` (`code`)
) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `PREFIX_pulse_inv_category` (
  `id_pulse_inv_category` INT UNSIGNED NOT NULL AUTO_INCREMENT, `code` VARCHAR(16) NOT NULL, `name` VARCHAR(64) NOT NULL,
  `group_name` ENUM('food','beverage','liquor','guest_amenity','cleaning','linen','minibar','stationery','printing','keycard','engineering','uniform','other') NOT NULL DEFAULT 'other',
  `expense_code` VARCHAR(16) DEFAULT NULL COMMENT 'pulse_expense_category code for purchases', `active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_pulse_inv_category`), UNIQUE KEY `code` (`code`)
) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `PREFIX_pulse_inv_unit` (`code` VARCHAR(12) NOT NULL, `name` VARCHAR(32) NOT NULL, `base` VARCHAR(12) NOT NULL COMMENT 'base unit code', `factor` DECIMAL(14,6) NOT NULL DEFAULT 1 COMMENT '1 unit = factor base', PRIMARY KEY (`code`)) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `PREFIX_pulse_inv_item` (
  `id_pulse_inv_item` INT UNSIGNED NOT NULL AUTO_INCREMENT, `sku` VARCHAR(32) NOT NULL, `name` VARCHAR(96) NOT NULL, `id_pulse_inv_category` INT UNSIGNED NOT NULL,
  `unit` VARCHAR(12) NOT NULL DEFAULT 'pc' COMMENT 'stock unit', `purchase_unit` VARCHAR(12) DEFAULT NULL, `purchase_factor` DECIMAL(14,6) NOT NULL DEFAULT 1 COMMENT '1 purchase unit = factor stock units',
  `avg_cost` DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT 'weighted average per stock unit', `last_cost` DECIMAL(20,6) NOT NULL DEFAULT 0, `sale_price` DECIMAL(20,6) DEFAULT NULL COMMENT 'minibar / resale price',
  `reorder_level` DECIMAL(14,3) NOT NULL DEFAULT 0, `reorder_qty` DECIMAL(14,3) NOT NULL DEFAULT 0, `max_level` DECIMAL(14,3) DEFAULT NULL, `lead_days` TINYINT NOT NULL DEFAULT 3,
  `track_expiry` TINYINT(1) NOT NULL DEFAULT 0, `track_batch` TINYINT(1) NOT NULL DEFAULT 0, `is_asset` TINYINT(1) NOT NULL DEFAULT 0, `id_supplier_pref` INT UNSIGNED,
  `link_type` ENUM('pos_ingredient','maintenance_part','laundry_linen') DEFAULT NULL, `link_id` INT UNSIGNED DEFAULT NULL, `barcode` VARCHAR(32), `note` VARCHAR(255), `active` TINYINT(1) NOT NULL DEFAULT 1, `date_add` DATETIME NOT NULL, `date_upd` DATETIME NOT NULL,
  PRIMARY KEY (`id_pulse_inv_item`), UNIQUE KEY `sku` (`sku`), KEY `cat` (`id_pulse_inv_category`), KEY `link` (`link_type`,`link_id`)
) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `PREFIX_pulse_inv_stock` (`id_pulse_inv_item` INT UNSIGNED NOT NULL, `id_pulse_inv_store` INT UNSIGNED NOT NULL, `qty` DECIMAL(14,3) NOT NULL DEFAULT 0, `par` DECIMAL(14,3) DEFAULT NULL COMMENT 'par level for this store', `date_upd` DATETIME NOT NULL, PRIMARY KEY (`id_pulse_inv_item`,`id_pulse_inv_store`)) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `PREFIX_pulse_inv_batch` (`id_pulse_inv_batch` INT UNSIGNED NOT NULL AUTO_INCREMENT, `id_pulse_inv_item` INT UNSIGNED NOT NULL, `id_pulse_inv_store` INT UNSIGNED NOT NULL, `batch_no` VARCHAR(32), `expiry` DATE, `qty` DECIMAL(14,3) NOT NULL DEFAULT 0, `unit_cost` DECIMAL(20,6), `grn_no` VARCHAR(16), `date_add` DATETIME NOT NULL, PRIMARY KEY (`id_pulse_inv_batch`), KEY `i` (`id_pulse_inv_item`,`id_pulse_inv_store`,`expiry`)) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `PREFIX_pulse_inv_movement` (
  `id_pulse_inv_movement` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, `id_pulse_inv_item` INT UNSIGNED NOT NULL, `id_pulse_inv_store` INT UNSIGNED NOT NULL,
  `type` ENUM('receive','issue','transfer_out','transfer_in','consume','sale','waste','return','count_adjust','opening','minibar','amenity','production') NOT NULL,
  `qty` DECIMAL(14,3) NOT NULL COMMENT 'signed: + in, - out', `unit_cost` DECIMAL(20,6) NOT NULL DEFAULT 0, `value` DECIMAL(20,6) NOT NULL DEFAULT 0,
  `department` VARCHAR(32), `cost_centre` VARCHAR(32), `reference` VARCHAR(64), `reason` VARCHAR(128), `id_room` INT UNSIGNED, `id_pulse_inv_batch` INT UNSIGNED, `id_employee` INT UNSIGNED, `business_date` DATE NOT NULL, `date_add` DATETIME NOT NULL,
  PRIMARY KEY (`id_pulse_inv_movement`), KEY `item_date` (`id_pulse_inv_item`,`business_date`), KEY `store_date` (`id_pulse_inv_store`,`business_date`), KEY `type` (`type`,`business_date`), KEY `ref` (`reference`)
) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `PREFIX_pulse_inv_supplier` (`id_pulse_inv_supplier` INT UNSIGNED NOT NULL AUTO_INCREMENT, `name` VARCHAR(96) NOT NULL, `contact` VARCHAR(96), `phone` VARCHAR(32), `email` VARCHAR(96), `address` VARCHAR(255), `tin` VARCHAR(32), `payment_terms_days` SMALLINT NOT NULL DEFAULT 0, `categories` VARCHAR(255), `rating` TINYINT DEFAULT NULL, `active` TINYINT(1) NOT NULL DEFAULT 1, `date_add` DATETIME NOT NULL, PRIMARY KEY (`id_pulse_inv_supplier`)) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `PREFIX_pulse_inv_supplier_price` (`id_pulse_inv_supplier` INT UNSIGNED NOT NULL, `id_pulse_inv_item` INT UNSIGNED NOT NULL, `price` DECIMAL(20,6) NOT NULL COMMENT 'per purchase unit', `supplier_sku` VARCHAR(32), `lead_days` TINYINT, `date_upd` DATETIME NOT NULL, PRIMARY KEY (`id_pulse_inv_supplier`,`id_pulse_inv_item`)) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `PREFIX_pulse_inv_request` (
  `id_pulse_inv_request` INT UNSIGNED NOT NULL AUTO_INCREMENT, `req_no` VARCHAR(16) NOT NULL, `type` ENUM('store_issue','purchase') NOT NULL DEFAULT 'store_issue',
  `id_store_from` INT UNSIGNED, `id_store_to` INT UNSIGNED, `department` VARCHAR(32), `status` ENUM('draft','submitted','approved','partially_issued','issued','ordered','rejected','cancelled') NOT NULL DEFAULT 'submitted',
  `note` VARCHAR(255), `requested_by` INT UNSIGNED, `approved_by` INT UNSIGNED, `needed_by` DATE, `business_date` DATE NOT NULL, `date_add` DATETIME NOT NULL, `date_upd` DATETIME NOT NULL,
  PRIMARY KEY (`id_pulse_inv_request`), UNIQUE KEY `n` (`req_no`), KEY `st` (`status`)
) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `PREFIX_pulse_inv_request_line` (`id_pulse_inv_request_line` INT UNSIGNED NOT NULL AUTO_INCREMENT, `id_pulse_inv_request` INT UNSIGNED NOT NULL, `id_pulse_inv_item` INT UNSIGNED NOT NULL, `qty_requested` DECIMAL(14,3) NOT NULL, `qty_approved` DECIMAL(14,3), `qty_issued` DECIMAL(14,3) NOT NULL DEFAULT 0, `note` VARCHAR(128), PRIMARY KEY (`id_pulse_inv_request_line`), KEY `r` (`id_pulse_inv_request`)) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `PREFIX_pulse_inv_po` (
  `id_pulse_inv_po` INT UNSIGNED NOT NULL AUTO_INCREMENT, `po_no` VARCHAR(16) NOT NULL, `id_pulse_inv_supplier` INT UNSIGNED NOT NULL, `id_pulse_inv_request` INT UNSIGNED,
  `status` ENUM('draft','sent','partially_received','received','closed','cancelled') NOT NULL DEFAULT 'draft', `subtotal` DECIMAL(20,6) NOT NULL DEFAULT 0, `tax` DECIMAL(20,6) NOT NULL DEFAULT 0, `total` DECIMAL(20,6) NOT NULL DEFAULT 0,
  `expected_date` DATE, `note` VARCHAR(255), `created_by` INT UNSIGNED, `approved_by` INT UNSIGNED, `business_date` DATE NOT NULL, `date_add` DATETIME NOT NULL, `date_upd` DATETIME NOT NULL,
  PRIMARY KEY (`id_pulse_inv_po`), UNIQUE KEY `n` (`po_no`), KEY `sup` (`id_pulse_inv_supplier`,`status`)
) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `PREFIX_pulse_inv_po_line` (`id_pulse_inv_po_line` INT UNSIGNED NOT NULL AUTO_INCREMENT, `id_pulse_inv_po` INT UNSIGNED NOT NULL, `id_pulse_inv_item` INT UNSIGNED NOT NULL, `qty_ordered` DECIMAL(14,3) NOT NULL COMMENT 'purchase units', `qty_received` DECIMAL(14,3) NOT NULL DEFAULT 0, `unit_price` DECIMAL(20,6) NOT NULL, `tax_pct` DECIMAL(6,3) NOT NULL DEFAULT 0, PRIMARY KEY (`id_pulse_inv_po_line`), KEY `po` (`id_pulse_inv_po`)) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `PREFIX_pulse_inv_grn` (
  `id_pulse_inv_grn` INT UNSIGNED NOT NULL AUTO_INCREMENT, `grn_no` VARCHAR(16) NOT NULL, `id_pulse_inv_po` INT UNSIGNED, `id_pulse_inv_supplier` INT UNSIGNED NOT NULL, `id_pulse_inv_store` INT UNSIGNED NOT NULL,
  `invoice_no` VARCHAR(64), `invoice_date` DATE, `invoice_total` DECIMAL(20,6), `total` DECIMAL(20,6) NOT NULL DEFAULT 0, `status` ENUM('received','invoiced','paid') NOT NULL DEFAULT 'received', `id_pulse_expense` INT UNSIGNED, `received_by` INT UNSIGNED, `note` VARCHAR(255), `business_date` DATE NOT NULL, `date_add` DATETIME NOT NULL,
  PRIMARY KEY (`id_pulse_inv_grn`), UNIQUE KEY `n` (`grn_no`)
) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `PREFIX_pulse_inv_grn_line` (`id_pulse_inv_grn_line` INT UNSIGNED NOT NULL AUTO_INCREMENT, `id_pulse_inv_grn` INT UNSIGNED NOT NULL, `id_pulse_inv_item` INT UNSIGNED NOT NULL, `qty` DECIMAL(14,3) NOT NULL COMMENT 'purchase units', `unit_price` DECIMAL(20,6) NOT NULL, `tax_pct` DECIMAL(6,3) NOT NULL DEFAULT 0, `batch_no` VARCHAR(32), `expiry` DATE, `rejected_qty` DECIMAL(14,3) NOT NULL DEFAULT 0, `reject_reason` VARCHAR(96), PRIMARY KEY (`id_pulse_inv_grn_line`), KEY `g` (`id_pulse_inv_grn`)) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `PREFIX_pulse_inv_count` (`id_pulse_inv_count` INT UNSIGNED NOT NULL AUTO_INCREMENT, `count_no` VARCHAR(16) NOT NULL, `id_pulse_inv_store` INT UNSIGNED NOT NULL, `type` ENUM('full','cycle','spot') NOT NULL DEFAULT 'full', `status` ENUM('open','counted','posted','cancelled') NOT NULL DEFAULT 'open', `counted_by` INT UNSIGNED, `approved_by` INT UNSIGNED, `variance_value` DECIMAL(20,6), `note` VARCHAR(255), `business_date` DATE NOT NULL, `date_add` DATETIME NOT NULL, `date_posted` DATETIME, PRIMARY KEY (`id_pulse_inv_count`), UNIQUE KEY `n` (`count_no`)) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `PREFIX_pulse_inv_count_line` (`id_pulse_inv_count_line` INT UNSIGNED NOT NULL AUTO_INCREMENT, `id_pulse_inv_count` INT UNSIGNED NOT NULL, `id_pulse_inv_item` INT UNSIGNED NOT NULL, `system_qty` DECIMAL(14,3) NOT NULL, `counted_qty` DECIMAL(14,3), `unit_cost` DECIMAL(20,6), `note` VARCHAR(96), PRIMARY KEY (`id_pulse_inv_count_line`), KEY `c` (`id_pulse_inv_count`)) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `PREFIX_pulse_inv_minibar_item` (`id_pulse_inv_item` INT UNSIGNED NOT NULL, `id_product` INT UNSIGNED DEFAULT NULL COMMENT 'room type; NULL = all', `par` DECIMAL(6,2) NOT NULL DEFAULT 2, `sort` TINYINT NOT NULL DEFAULT 0, PRIMARY KEY (`id_pulse_inv_item`)) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `PREFIX_pulse_inv_amenity` (`id_pulse_inv_item` INT UNSIGNED NOT NULL, `id_product` INT UNSIGNED DEFAULT NULL, `par_per_room` DECIMAL(6,2) NOT NULL DEFAULT 1, `frequency` ENUM('arrival','daily','on_request') NOT NULL DEFAULT 'daily', PRIMARY KEY (`id_pulse_inv_item`)) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `PREFIX_pulse_inv_minibar_post` (`id_pulse_inv_minibar_post` INT UNSIGNED NOT NULL AUTO_INCREMENT, `id_room` INT UNSIGNED NOT NULL, `id_htl_booking` INT UNSIGNED, `lines` TEXT COMMENT 'JSON [{id,qty,price}]', `total` DECIMAL(20,6) NOT NULL DEFAULT 0, `folio_line` BIGINT UNSIGNED, `complimentary` TINYINT(1) NOT NULL DEFAULT 0, `id_employee` INT UNSIGNED, `business_date` DATE NOT NULL, `date_add` DATETIME NOT NULL, PRIMARY KEY (`id_pulse_inv_minibar_post`), KEY `r` (`id_room`,`business_date`)) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8;

INSERT IGNORE INTO `PREFIX_pulse_inv_unit` (`code`,`name`,`base`,`factor`) VALUES ('pc','Piece','pc',1),('kg','Kilogram','g',1000),('g','Gram','g',1),('l','Litre','ml',1000),('ml','Millilitre','ml',1),('cl','Centilitre','ml',10),('btl','Bottle','btl',1),('ctn','Carton','pc',1),('crate','Crate','btl',1),('bag','Bag','kg',1),('roll','Roll','pc',1),('pack','Pack','pc',1),('tot','Tot (3cl)','ml',30),('set','Set','pc',1);
INSERT IGNORE INTO `PREFIX_pulse_inv_store` (`code`,`name`,`type`,`department`) VALUES ('MAIN','Central store','central','general'),('KITCHEN','Kitchen store','kitchen','fnb'),('BAR','Bar store','bar','fnb'),('HK','Housekeeping store','housekeeping','housekeeping'),('MINIBAR','Minibar stock','minibar','rooms'),('FO','Front office store','front_office','rooms'),('ENG','Engineering store','engineering','maintenance');
INSERT IGNORE INTO `PREFIX_pulse_inv_category` (`code`,`name`,`group_name`,`expense_code`) VALUES ('FOOD','Food','food','FOOD'),('BEV','Soft drinks & water','beverage','BEV'),('LIQ','Beer, wine & spirits','liquor','BEV'),('AMEN','Guest amenities','guest_amenity','GSUP'),('CLEAN','Cleaning & chemicals','cleaning','CLEAN'),('MINI','Minibar stock','minibar','BEV'),('STAT','Stationery & printing','stationery','ADMIN'),('KEY','Key cards & FO consumables','keycard','GSUP'),('ENG','Engineering consumables','engineering','PARTS'),('UNIF','Uniforms','uniform','GSUP');
INSERT IGNORE INTO `PREFIX_pulse_inv_item` (`sku`,`name`,`id_pulse_inv_category`,`unit`,`purchase_unit`,`purchase_factor`,`avg_cost`,`sale_price`,`reorder_level`,`reorder_qty`,`date_add`,`date_upd`) VALUES
('AM-SOAP','Bath soap 40g',4,'pc','ctn',144,120,NULL,300,576,NOW(),NOW()),('AM-SHAM','Shampoo 30ml',4,'pc','ctn',200,150,NULL,300,600,NOW(),NOW()),('AM-TP','Toilet roll',4,'roll','bag',48,180,NULL,200,480,NOW(),NOW()),('AM-TISS','Facial tissue box',4,'pc','ctn',36,400,NULL,60,144,NOW(),NOW()),('AM-SLIP','Slippers (pair)',4,'pc','ctn',100,350,NULL,100,300,NOW(),NOW()),('AM-KIT','Dental kit',4,'pc','ctn',200,220,NULL,200,400,NOW(),NOW()),
('CL-BLEACH','Bleach 5L',5,'l','btl',5,700,NULL,20,60,NOW(),NOW()),('CL-DET','Multi-surface detergent 5L',5,'l','btl',5,900,NULL,20,60,NOW(),NOW()),('CL-GLASS','Glass cleaner 1L',5,'l','btl',1,1200,NULL,10,24,NOW(),NOW()),
('MB-WATER','Water 50cl',6,'btl','pack',12,250,1000,100,240,NOW(),NOW()),('MB-COKE','Coke 33cl can',6,'btl','pack',24,300,1500,100,240,NOW(),NOW()),('MB-BEER','Heineken 33cl',6,'btl','crate',24,900,3000,72,144,NOW(),NOW()),('MB-NUTS','Peanuts 50g',6,'pc','ctn',48,400,1500,50,96,NOW(),NOW()),('MB-CHOC','Chocolate bar',6,'pc','ctn',48,600,2000,50,96,NOW(),NOW()),
('FO-KEY','RFID key card',8,'pc','pack',100,350,NULL,100,300,NOW(),NOW()),('FO-REG','Registration card pad',7,'pc','pack',10,1500,NULL,5,10,NOW(),NOW()),('FO-A4','A4 paper ream',7,'pc','ctn',5,4500,NULL,5,10,NOW(),NOW()),('FO-ROLL','Receipt roll 80mm',7,'roll','ctn',50,450,NULL,30,100,NOW(),NOW());
INSERT IGNORE INTO `PREFIX_pulse_inv_minibar_item` (`id_pulse_inv_item`,`par`,`sort`) SELECT id_pulse_inv_item, 2, 0 FROM `PREFIX_pulse_inv_item` WHERE sku LIKE 'MB-%';
INSERT IGNORE INTO `PREFIX_pulse_inv_amenity` (`id_pulse_inv_item`,`par_per_room`,`frequency`) SELECT id_pulse_inv_item, 1, 'daily' FROM `PREFIX_pulse_inv_item` WHERE sku IN ('AM-SOAP','AM-SHAM','AM-KIT');
INSERT IGNORE INTO `PREFIX_pulse_inv_amenity` (`id_pulse_inv_item`,`par_per_room`,`frequency`) SELECT id_pulse_inv_item, 2, 'daily' FROM `PREFIX_pulse_inv_item` WHERE sku='AM-TP';
INSERT IGNORE INTO `PREFIX_pulse_inv_amenity` (`id_pulse_inv_item`,`par_per_room`,`frequency`) SELECT id_pulse_inv_item, 1, 'arrival' FROM `PREFIX_pulse_inv_item` WHERE sku='AM-SLIP';
