<div class="pulse-ldy"><div class="panel"><h3><i class="icon-archive"></i> Linen &amp; par stock</h3>
<table class="table"><thead><tr><th>Linen</th><th>Par target</th><th>Clean</th><th>In rooms</th><th>Soiled</th><th>In wash</th><th>Circulating</th><th>Shortfall</th><th>Discarded</th><th>Value</th><th>Unit cost</th></tr></thead><tbody>
{foreach $linen as $l}<tr class="{if $l.shortfall>0}warning{/if}"><td>{$l.name}</td><td>{$l.par_target}</td><td>{$l.qty_clean}</td><td>{$l.qty_in_rooms}</td><td>{$l.qty_soiled}</td><td>{$l.qty_in_wash}</td><td>{$l.in_circulation}</td><td>{$l.shortfall}</td><td>{$l.qty_discarded}</td><td>{displayPrice price=$l.value}</td><td>{$l.unit_cost}</td></tr>{/foreach}</tbody></table>
<div class="row"><div class="col-md-6"><h4>Record movement</h4><form method="post" class="form-inline"><select name="id_type" class="form-control">{foreach $linen as $l}<option value="{$l.id_pulse_linen_type}">{$l.name}</option>{/foreach}</select>
<select name="mtype" class="form-control"><option value="issue">Issue to floors</option><option value="return">Return soiled</option><option value="to_wash">To wash</option><option value="from_wash">From wash (clean)</option><option value="discard">Discard</option><option value="purchase">Purchase / new stock</option><option value="count_adjust">Physical count (clean)</option></select>
<input name="qty" type="number" class="form-control" placeholder="qty" style="width:90px"> <input name="reason" class="form-control" placeholder="reason / floor"> <button name="move" class="btn btn-default">Record</button></form></div>
<div class="col-md-6"><h4>Add / edit linen type</h4><form method="post" class="form-inline"><input type="hidden" name="id_type"><input name="name" class="form-control" placeholder="Name"> <input name="unit_cost" class="form-control" placeholder="Unit cost" style="width:100px"> <input name="par_per_room" class="form-control" placeholder="Par/room" style="width:90px"> <input name="expected_washes" class="form-control" placeholder="Washes" style="width:90px"> <button name="saveType" class="btn btn-default">Save</button></form></div></div></div>
<div class="row"><div class="col-md-6"><div class="panel"><h3>Wash batches</h3><form method="post" class="form-inline"><input name="machine" class="form-control" placeholder="Machine"> <input name="program" class="form-control" placeholder="Program"> <input name="kg" class="form-control" placeholder="kg" style="width:70px"> <input name="chem" class="form-control" placeholder="Chemicals ₦" style="width:110px"> <button name="addBatch" class="btn btn-default">Start batch</button></form>
<table class="table table-condensed"><tbody>{foreach $batches as $b}<tr><td>{$b.batch_no}</td><td>{$b.machine} {$b.program}</td><td>{$b.kg} kg</td><td>{$b.started_at|date_format:"%d/%m %H:%M"} → {if $b.finished_at}{$b.finished_at|date_format:"%H:%M"}{else}<form method="post" class="inline"><input type="hidden" name="id_batch" value="{$b.id_pulse_laundry_batch}"><button name="finishBatch" class="btn btn-xs btn-default">finish</button></form>{/if}</td></tr>{/foreach}</tbody></table></div></div>
<div class="col-md-6"><div class="panel"><h3>Linen loss {$from} → {$to}</h3><form method="get" class="form-inline"><input type="hidden" name="controller" value="AdminPulseLaundryLinen"><input type="hidden" name="token" value="{$smarty.get.token|escape}"><input type="date" name="from" value="{$from}" class="form-control"> <input type="date" name="to" value="{$to}" class="form-control"> <button class="btn btn-default btn-sm">Run</button></form>
<table class="table table-condensed"><thead><tr><th>Linen</th><th>Discarded</th><th>Purchased</th><th>Loss value</th></tr></thead><tbody>{foreach $loss as $l}<tr><td>{$l.name}</td><td>{$l.discarded}</td><td>{$l.purchased}</td><td>{displayPrice price=$l.loss_value}</td></tr>{/foreach}</tbody></table></div></div></div>
<div class="panel"><h3>Recent movements</h3><table class="table table-condensed"><tbody>{foreach $movements as $m}<tr><td>{$m.date_add}</td><td>{$m.name}</td><td>{$m.type}</td><td>{$m.qty}</td><td>{$m.reason}</td><td>{$m.who}</td></tr>{/foreach}</tbody></table></div></div>
