<div class="pulse-fd"><div class="row">
<div class="col-md-{if $ticket}7{else}12{/if}"><div class="panel"><h3><i class="icon-ticket"></i> Guest Services &amp; Tickets <span class="pull-right"><a class="btn btn-sm {if $mine}btn-primary{else}btn-default{/if}" href="{$self_url}&mine=1">Mine</a> <a class="btn btn-sm {if !$mine}btn-primary{else}btn-default{/if}" href="{$self_url}">All</a></span></h3>
<form method="post" class="form-inline" style="margin-bottom:10px"><select name="category" class="form-control"><option>complaint</option><option>maintenance</option><option>housekeeping</option><option>amenity</option><option>concierge</option><option>it</option><option>other</option></select> <select name="department" class="form-control"><option>frontdesk</option><option>housekeeping</option><option>engineering</option><option>fnb</option><option>security</option><option>management</option></select> <select name="id_room" class="form-control"><option value="">No room</option>{foreach $rooms as $r}<option value="{$r.id}">{$r.room_num}</option>{/foreach}</select> <input name="title" class="form-control" placeholder="Title" required> <select name="priority" class="form-control"><option>low</option><option selected>normal</option><option>high</option><option>urgent</option></select> <select name="assigned_to" class="form-control"><option value="">Unassigned</option>{foreach $employees as $e}<option value="{$e.id_employee}">{$e.firstname} {$e.lastname}</option>{/foreach}</select> <button name="addTicket" class="btn btn-default">Log ticket</button><br><textarea name="description" class="form-control" placeholder="Details" style="width:100%;margin-top:4px"></textarea></form>
<table class="table"><thead><tr><th>#</th><th>P</th><th>Room</th><th>Title</th><th>Dept</th><th>Assigned</th><th>SLA due</th><th>Status</th></tr></thead><tbody>
{foreach $tickets as $t}<tr class="{if $t.overdue}danger{elseif $t.priority=='urgent'}warning{/if}"><td><a href="{$self_url}&id_ticket={$t.id_pulse_ticket}">{$t.ticket_no}</a></td><td>{$t.priority}</td><td>{$t.room_num}</td><td>{$t.title}<br><small>{$t.category} · {$t.source}</small></td><td>{$t.department}</td><td>{$t.assignee|default:'—'}</td><td>{$t.sla_due|date_format:"%d/%m %H:%M"}{if $t.overdue} <b>OVERDUE</b>{/if}</td><td>{$t.status|replace:'_':' '}</td></tr>{foreachelse}<tr><td colspan="8"><em>No open tickets</em></td></tr>{/foreach}</tbody></table>
<h4>Recently closed</h4><table class="table table-condensed"><tbody>{foreach $closed|@array_slice:0:15 as $t}<tr><td>{$t.ticket_no}</td><td>{$t.room_num}</td><td>{$t.title}</td><td>{$t.status}</td><td>{$t.date_resolved}</td></tr>{/foreach}</tbody></table></div></div>
{if $ticket}<div class="col-md-5"><div class="panel"><h3>{$ticket.ticket_no} &mdash; {$ticket.title}</h3><p>{$ticket.category} · {$ticket.department} · room {$ticket.room_num|default:'—'} · opened {$ticket.date_add} · SLA {$ticket.sla_due}</p><p>{$ticket.description|nl2br}</p>
<form method="post" class="form-horizontal"><input type="hidden" name="id_ticket" value="{$ticket.id_pulse_ticket}">
<div class="form-group"><label class="col-sm-3">Status</label><div class="col-sm-9"><select name="status" class="form-control">{foreach ['open','assigned','in_progress','resolved','closed','reopened'] as $s}<option {if $ticket.status==$s}selected{/if}>{$s}</option>{/foreach}</select></div></div>
<div class="form-group"><label class="col-sm-3">Priority</label><div class="col-sm-9"><select name="priority" class="form-control">{foreach ['low','normal','high','urgent'] as $s}<option {if $ticket.priority==$s}selected{/if}>{$s}</option>{/foreach}</select></div></div>
<div class="form-group"><label class="col-sm-3">Department</label><div class="col-sm-9"><select name="department" class="form-control">{foreach ['frontdesk','housekeeping','engineering','fnb','security','management'] as $s}<option {if $ticket.department==$s}selected{/if}>{$s}</option>{/foreach}</select></div></div>
<div class="form-group"><label class="col-sm-3">Assign</label><div class="col-sm-9"><select name="assigned_to" class="form-control"><option value="0">Unassigned</option>{foreach $employees as $e}<option value="{$e.id_employee}" {if $ticket.assigned_to==$e.id_employee}selected{/if}>{$e.firstname} {$e.lastname}</option>{/foreach}</select></div></div>
<div class="form-group"><label class="col-sm-3">Note</label><div class="col-sm-9"><textarea name="note" class="form-control"></textarea></div></div>
<div class="form-group"><label class="col-sm-3">Resolution</label><div class="col-sm-9"><textarea name="resolution" class="form-control">{$ticket.resolution}</textarea><label><input type="checkbox" name="notify" value="1"> Notify guest (SMS/email)</label></div></div>
<button name="updTicket" class="btn btn-primary pull-right">Update</button></form>
<h4>Timeline</h4><ul>{foreach $notes as $n}<li><small>{$n.date_add} {$n.who}</small><br>{$n.note|nl2br}</li>{/foreach}</ul></div></div>{/if}
</div></div>
