<div class="pulse-fd"><div class="row">
<div class="col-md-6"><div class="panel"><h3><i class="icon-user"></i> {$p.firstname} {$p.lastname} {if $p.vip_level}<span class="badge badge-warning">VIP {$p.vip_level}</span>{/if} {if $p.blacklisted}<span class="badge badge-danger">BLACKLISTED</span>{/if}</h3>
  <p>{$p.email} &middot; {$p.stays} stay(s), {$p.nights} night(s), lifetime {displayPrice price=$p.lifetime_revenue} &middot; last stay {$p.last_stay|default:'—'}</p>
  <form method="post" class="form-horizontal"><input type="hidden" name="id_customer" value="{$p.id_customer}">
    <div class="form-group"><label class="col-sm-3">VIP level</label><div class="col-sm-9"><select name="vip_level" class="form-control"><option value="0" {if $p.vip_level==0}selected{/if}>None</option><option value="1" {if $p.vip_level==1}selected{/if}>VIP 1</option><option value="2" {if $p.vip_level==2}selected{/if}>VIP 2 – Gold</option><option value="3" {if $p.vip_level==3}selected{/if}>VIP 3 – Owner / Dignitary</option></select></div></div>
    <div class="form-group"><label class="col-sm-3">Company</label><div class="col-sm-9"><select name="id_pulse_company" class="form-control"><option value="0">—</option>{foreach $companies as $c}<option value="{$c.id_pulse_company}" {if $p.id_pulse_company==$c.id_pulse_company}selected{/if}>{$c.name}</option>{/foreach}</select></div></div>
    <div class="form-group"><label class="col-sm-3">Phone</label><div class="col-sm-9"><input name="phone" class="form-control" value="{$p.phone}"></div></div>
    <div class="form-group"><label class="col-sm-3">Nationality</label><div class="col-sm-9"><input name="nationality" class="form-control" value="{$p.nationality}" maxlength="3" placeholder="NGA"></div></div>
    <div class="form-group"><label class="col-sm-3">Address</label><div class="col-sm-9"><input name="address" class="form-control" value="{$p.address}"></div></div>
    <h4>Preferences</h4>
    {foreach ['pillow','floor','smoking','newspaper','dietary','other'] as $k}<div class="form-group"><label class="col-sm-3">{$k|ucfirst}</label><div class="col-sm-9"><input name="pref_{$k}" class="form-control" value="{$p.preferences[$k]|default:''}"></div></div>{/foreach}
    <div class="form-group"><label class="col-sm-3">Notes</label><div class="col-sm-9"><textarea name="notes" class="form-control">{$p.notes}</textarea></div></div>
    <div class="form-group"><label class="col-sm-3">Blacklist</label><div class="col-sm-9"><label><input type="checkbox" name="blacklisted" value="1" {if $p.blacklisted}checked{/if}> Do not accept bookings</label><input name="blacklist_reason" class="form-control" placeholder="Reason" value="{$p.blacklist_reason}"></div></div>
    <button name="saveProfile" class="btn btn-primary pull-right">Save profile</button></form></div></div>
<div class="col-md-6">
  <div class="panel"><h3>Identity documents</h3><table class="table table-condensed"><thead><tr><th>Type</th><th>Number</th><th>Country</th><th>Expiry</th><th>Captured</th></tr></thead><tbody>{foreach $p.identities as $i}<tr><td>{$i.id_type}</td><td>{$i.id_number}</td><td>{$i.issuing_country}</td><td>{$i.expiry}</td><td>{$i.date_add|date_format:"%d/%m/%Y"}</td></tr>{foreachelse}<tr><td colspan="5"><em>None captured</em></td></tr>{/foreach}</tbody></table></div>
  <div class="panel"><h3>Stay history</h3><table class="table table-condensed"><thead><tr><th>Dates</th><th>Room</th><th>Type</th><th class="text-right">Total</th><th>Status</th></tr></thead><tbody>{foreach $p.history as $h}<tr><td>{$h.date_from} → {$h.date_to}</td><td>{$h.room_num}</td><td>{$h.room_type_name}</td><td class="text-right">{displayPrice price=$h.total_price_tax_incl}</td><td>{if $h.id_status==1}Reserved{elseif $h.id_status==2}In house{else}Departed{/if}</td></tr>{/foreach}</tbody></table></div>
</div></div></div>
