<?php
class AdminPulseInventorySettingsController extends ModuleAdminController
{
    public function __construct()
    {
        $this->bootstrap = true; parent::__construct(); $this->meta_title = $this->l('Items, Stores & Suppliers');
        $this->fields_options = array('inv' => array('title' => $this->l('Inventory options'), 'fields' => array('PULSE_INV_PO_APPROVAL_LIMIT' => array('title' => $this->l('PO value above which a SuperAdmin must approve'), 'type' => 'text'), 'PULSE_INV_AUTO_AMENITY' => array('title' => $this->l('Post standard guest-amenity consumption at night audit'), 'type' => 'bool'), 'PULSE_INV_EXPIRY_DAYS' => array('title' => $this->l('Expiry alert horizon (days)'), 'type' => 'text'), 'PULSE_INV_MINIBAR_CHECKOUT_TRACE' => array('title' => $this->l('Alert front desk if minibar was not checked on the day of check-out'), 'type' => 'bool')), 'submit' => array('title' => $this->l('Save'))));
    }
    public function initContent()
    {
        parent::initContent();
        $D = Db::getInstance(); $edit = (int) Tools::getValue('id_item');
        $this->context->smarty->assign(array('items' => $D->executeS('SELECT i.*, c.name category FROM `'._DB_PREFIX_.'pulse_inv_item` i INNER JOIN `'._DB_PREFIX_.'pulse_inv_category` c ON c.id_pulse_inv_category=i.id_pulse_inv_category ORDER BY c.name, i.name'), 'item' => $edit ? PulseInvService::item($edit) : null, 'price_history' => $edit ? PulseInvPurchasing::priceHistory($edit) : array(), 'categories' => $D->executeS('SELECT * FROM `'._DB_PREFIX_.'pulse_inv_category` ORDER BY name'), 'units' => $D->executeS('SELECT * FROM `'._DB_PREFIX_.'pulse_inv_unit` ORDER BY code'), 'stores' => $D->executeS('SELECT s.*, CONCAT(e.firstname," ",e.lastname) keeper FROM `'._DB_PREFIX_.'pulse_inv_store` s LEFT JOIN `'._DB_PREFIX_.'employee` e ON e.id_employee=s.id_employee_keeper'), 'suppliers' => $D->executeS('SELECT * FROM `'._DB_PREFIX_.'pulse_inv_supplier` ORDER BY name'), 'employees' => Employee::getEmployees(), 'expense_codes' => class_exists('PulseExpense') ? $D->executeS('SELECT code, name FROM `'._DB_PREFIX_.'pulse_expense_category` WHERE active=1 ORDER BY name') : array(), 'self_url' => self::$currentIndex.'&token='.$this->token, 'cron_url' => Tools::getShopDomainSsl(true).__PS_BASE_URI__.'modules/pulseinventory/cron/daily.php?token='.Configuration::get('PULSE_INV_CRON_TOKEN')));
        $this->content .= $this->context->smarty->fetch($this->getTemplatePath().'pulse_inventory_settings/settings.tpl');
        $this->context->smarty->assign('content', $this->content);
    }
    public function postProcess()
    {
        $D = Db::getInstance();
        try {
            if (Tools::isSubmit('saveItem')) { $id = (int) Tools::getValue('id_item'); $d = array('sku' => pSQL(strtoupper(Tools::getValue('sku'))), 'name' => pSQL(Tools::getValue('name')), 'id_pulse_inv_category' => (int) Tools::getValue('id_category'), 'unit' => pSQL(Tools::getValue('unit')), 'purchase_unit' => pSQL(Tools::getValue('purchase_unit')) ?: null, 'purchase_factor' => max(0.000001, (float) Tools::getValue('purchase_factor', 1)), 'sale_price' => Tools::getValue('sale_price') !== '' ? (float) Tools::getValue('sale_price') : null, 'reorder_level' => (float) Tools::getValue('reorder_level'), 'reorder_qty' => (float) Tools::getValue('reorder_qty'), 'max_level' => Tools::getValue('max_level') !== '' ? (float) Tools::getValue('max_level') : null, 'lead_days' => (int) Tools::getValue('lead_days', 3), 'track_expiry' => (int) Tools::getValue('track_expiry'), 'track_batch' => (int) Tools::getValue('track_batch'), 'id_supplier_pref' => (int) Tools::getValue('id_supplier_pref') ?: null, 'barcode' => pSQL(Tools::getValue('barcode')), 'note' => pSQL(Tools::getValue('note')), 'active' => (int) Tools::getValue('active', 1), 'date_upd' => date('Y-m-d H:i:s')); if (!$id) { $d['avg_cost'] = (float) Tools::getValue('avg_cost'); $d['last_cost'] = (float) Tools::getValue('avg_cost'); $d['date_add'] = date('Y-m-d H:i:s'); $D->insert('pulse_inv_item', $d); $id = (int) $D->Insert_ID(); if ((float) Tools::getValue('opening_qty') > 0) { PulseInvService::move($id, (int) Tools::getValue('opening_store'), 'opening', (float) Tools::getValue('opening_qty'), (float) Tools::getValue('avg_cost'), array('reference' => 'opening balance')); } } else { $D->update('pulse_inv_item', $d, 'id_pulse_inv_item='.$id); } $this->confirmations[] = $this->l('Item saved'); }
            if (Tools::isSubmit('saveCategory')) { $D->insert('pulse_inv_category', array('code' => pSQL(strtoupper(Tools::getValue('ccode'))), 'name' => pSQL(Tools::getValue('cname')), 'group_name' => pSQL(Tools::getValue('cgroup')), 'expense_code' => pSQL(Tools::getValue('cexp')) ?: null)); $this->confirmations[] = $this->l('Category added'); }
            if (Tools::isSubmit('saveStore')) { $id = (int) Tools::getValue('id_store'); $d = array('code' => pSQL(strtoupper(Tools::getValue('scode'))), 'name' => pSQL(Tools::getValue('sname')), 'type' => pSQL(Tools::getValue('stype')), 'department' => pSQL(Tools::getValue('sdept')), 'id_employee_keeper' => (int) Tools::getValue('keeper') ?: null, 'allow_negative' => (int) Tools::getValue('allow_negative'), 'active' => (int) Tools::getValue('sactive', 1)); $id ? $D->update('pulse_inv_store', $d, 'id_pulse_inv_store='.$id) : $D->insert('pulse_inv_store', $d); $this->confirmations[] = $this->l('Store saved'); }
            if (Tools::isSubmit('saveSupplier')) { $id = (int) Tools::getValue('id_supplier'); $d = array('name' => pSQL(Tools::getValue('supname')), 'contact' => pSQL(Tools::getValue('contact')), 'phone' => pSQL(Tools::getValue('phone')), 'email' => pSQL(Tools::getValue('email')), 'address' => pSQL(Tools::getValue('address')), 'tin' => pSQL(Tools::getValue('tin')), 'payment_terms_days' => (int) Tools::getValue('terms'), 'categories' => pSQL(Tools::getValue('supcats')), 'active' => (int) Tools::getValue('supactive', 1)); if ($id) { $D->update('pulse_inv_supplier', $d, 'id_pulse_inv_supplier='.$id); } else { $d['date_add'] = date('Y-m-d H:i:s'); $D->insert('pulse_inv_supplier', $d); } $this->confirmations[] = $this->l('Supplier saved'); }
            if (Tools::isSubmit('saveUnit')) { $D->execute('INSERT INTO `'._DB_PREFIX_.'pulse_inv_unit` (code,name,base,factor) VALUES ("'.pSQL(Tools::getValue('ucode')).'","'.pSQL(Tools::getValue('uname')).'","'.pSQL(Tools::getValue('ubase')).'",'.(float) Tools::getValue('ufactor', 1).') ON DUPLICATE KEY UPDATE name=VALUES(name), base=VALUES(base), factor=VALUES(factor)'); }
            if (Tools::isSubmit('importCsv') && !empty($_FILES['csv']['tmp_name'])) { $n = 0; $h = fopen($_FILES['csv']['tmp_name'], 'r'); fgetcsv($h); while (($r = fgetcsv($h)) !== false) { if (count($r) < 4) { continue; } $cat = (int) $D->getValue('SELECT id_pulse_inv_category FROM `'._DB_PREFIX_.'pulse_inv_category` WHERE code="'.pSQL($r[2]).'"'); if (!$cat) { continue; } $D->execute('INSERT INTO `'._DB_PREFIX_.'pulse_inv_item` (sku,name,id_pulse_inv_category,unit,purchase_unit,purchase_factor,avg_cost,last_cost,reorder_level,reorder_qty,date_add,date_upd) VALUES ("'.pSQL($r[0]).'","'.pSQL($r[1]).'",'.$cat.',"'.pSQL($r[3]).'",'.(isset($r[4]) && $r[4] !== '' ? '"'.pSQL($r[4]).'"' : 'NULL').','.(isset($r[5]) && $r[5] !== '' ? (float) $r[5] : 1).','.(isset($r[6]) ? (float) $r[6] : 0).','.(isset($r[6]) ? (float) $r[6] : 0).','.(isset($r[7]) ? (float) $r[7] : 0).','.(isset($r[8]) ? (float) $r[8] : 0).',NOW(),NOW()) ON DUPLICATE KEY UPDATE name=VALUES(name), id_pulse_inv_category=VALUES(id_pulse_inv_category), reorder_level=VALUES(reorder_level), reorder_qty=VALUES(reorder_qty)'); $n++; } $this->confirmations[] = sprintf($this->l('%d items imported'), $n); }
        } catch (Exception $e) { $this->errors[] = $e->getMessage(); }
        return parent::postProcess();
    }
}
