<?php
class AdminPulseInventoryPurchasingController extends ModuleAdminController
{
    public function __construct() { $this->bootstrap = true; parent::__construct(); $this->meta_title = $this->l('Purchasing & Requisitions'); }
    public function initContent()
    {
        parent::initContent();
        $D = Db::getInstance(); $items = $D->executeS('SELECT i.id_pulse_inv_item, i.sku, i.name, i.unit, i.purchase_unit, i.purchase_factor, i.last_cost FROM `'._DB_PREFIX_.'pulse_inv_item` i WHERE i.active=1 ORDER BY i.name');
        $data = array('items' => $items, 'stores' => $D->executeS('SELECT * FROM `'._DB_PREFIX_.'pulse_inv_store` WHERE active=1'), 'suppliers' => $D->executeS('SELECT * FROM `'._DB_PREFIX_.'pulse_inv_supplier` WHERE active=1 ORDER BY name'),
            'requests' => $D->executeS('SELECT r.*, sf.code from_store, st.code to_store, CONCAT(e.firstname," ",e.lastname) who, (SELECT COUNT(*) FROM `'._DB_PREFIX_.'pulse_inv_request_line` l WHERE l.id_pulse_inv_request=r.id_pulse_inv_request) request_lines FROM `'._DB_PREFIX_.'pulse_inv_request` r LEFT JOIN `'._DB_PREFIX_.'pulse_inv_store` sf ON sf.id_pulse_inv_store=r.id_store_from LEFT JOIN `'._DB_PREFIX_.'pulse_inv_store` st ON st.id_pulse_inv_store=r.id_store_to LEFT JOIN `'._DB_PREFIX_.'employee` e ON e.id_employee=r.requested_by ORDER BY FIELD(r.status,"submitted","approved","partially_issued"), r.id_pulse_inv_request DESC LIMIT 60'),
            'pos' => $D->executeS('SELECT p.*, s.name supplier FROM `'._DB_PREFIX_.'pulse_inv_po` p INNER JOIN `'._DB_PREFIX_.'pulse_inv_supplier` s ON s.id_pulse_inv_supplier=p.id_pulse_inv_supplier ORDER BY p.id_pulse_inv_po DESC LIMIT 40'),
            'grns' => $D->executeS('SELECT g.*, s.name supplier, st.code store FROM `'._DB_PREFIX_.'pulse_inv_grn` g INNER JOIN `'._DB_PREFIX_.'pulse_inv_supplier` s ON s.id_pulse_inv_supplier=g.id_pulse_inv_supplier INNER JOIN `'._DB_PREFIX_.'pulse_inv_store` st ON st.id_pulse_inv_store=g.id_pulse_inv_store ORDER BY g.id_pulse_inv_grn DESC LIMIT 40'),
            'reorder' => PulseInvService::reorderSuggestions(), 'self_url' => self::$currentIndex.'&token='.$this->token, 'approval_limit' => Configuration::get('PULSE_INV_PO_APPROVAL_LIMIT'), 'cur' => $this->context->currency->sign);
        if ($id = (int) Tools::getValue('id_request')) { $data['req'] = $D->getRow('SELECT r.*, sf.name from_store, st.name to_store FROM `'._DB_PREFIX_.'pulse_inv_request` r LEFT JOIN `'._DB_PREFIX_.'pulse_inv_store` sf ON sf.id_pulse_inv_store=r.id_store_from LEFT JOIN `'._DB_PREFIX_.'pulse_inv_store` st ON st.id_pulse_inv_store=r.id_store_to WHERE r.id_pulse_inv_request='.$id); $data['req_lines'] = $D->executeS('SELECT l.*, i.name, i.unit, i.sku, COALESCE(s.qty,0) available FROM `'._DB_PREFIX_.'pulse_inv_request_line` l INNER JOIN `'._DB_PREFIX_.'pulse_inv_item` i ON i.id_pulse_inv_item=l.id_pulse_inv_item LEFT JOIN `'._DB_PREFIX_.'pulse_inv_stock` s ON s.id_pulse_inv_item=i.id_pulse_inv_item AND s.id_pulse_inv_store='.(int) $data['req']['id_store_from'].' WHERE l.id_pulse_inv_request='.$id); }
        if ($id = (int) Tools::getValue('id_po')) { $data['po'] = PulseInvPurchasing::po($id); }
        $this->context->smarty->assign($data);
        $this->setTemplate('purchasing.tpl');
    }
    public function postProcess()
    {
        try {
            $lines = function ($p) { $out = array(); foreach ((array) Tools::getValue($p.'_id') as $k => $id) { $q = (float) Tools::getValue($p.'_qty')[$k]; if ($id && $q > 0) { $out[] = array('id' => (int) $id, 'qty' => $q, 'price' => isset(Tools::getValue($p.'_price')[$k]) ? Tools::getValue($p.'_price')[$k] : null, 'unit_price' => isset(Tools::getValue($p.'_price')[$k]) ? (float) Tools::getValue($p.'_price')[$k] : 0, 'tax_pct' => isset(Tools::getValue($p.'_tax')[$k]) ? (float) Tools::getValue($p.'_tax')[$k] : 0, 'batch_no' => isset(Tools::getValue($p.'_batch')[$k]) ? Tools::getValue($p.'_batch')[$k] : '', 'expiry' => isset(Tools::getValue($p.'_exp')[$k]) ? Tools::getValue($p.'_exp')[$k] : null, 'rejected_qty' => isset(Tools::getValue($p.'_rej')[$k]) ? (float) Tools::getValue($p.'_rej')[$k] : 0); } } return $out; };
            if (Tools::isSubmit('createRequest')) { $id = PulseInvPurchasing::createRequest(Tools::getValue('rtype'), $lines('r'), array('from' => Tools::getValue('from_store'), 'to' => Tools::getValue('to_store'), 'department' => Tools::getValue('department'), 'note' => Tools::getValue('rnote'), 'needed_by' => Tools::getValue('needed_by'))); Tools::redirectAdmin(self::$currentIndex.'&token='.$this->token.'&id_request='.$id.'&conf=3'); }
            if (Tools::isSubmit('approveRequest')) { PulseInvPurchasing::approve((int) Tools::getValue('id_request'), (array) Tools::getValue('approved'), (bool) Tools::getValue('reject')); $this->confirmations[] = $this->l('Requisition updated'); }
            if (Tools::isSubmit('issueRequest')) { $all = PulseInvPurchasing::issue((int) Tools::getValue('id_request'), (array) Tools::getValue('issued')); $this->confirmations[] = $all ? $this->l('Issued in full') : $this->l('Partially issued'); }
            if (Tools::isSubmit('createPo')) { $id = PulseInvPurchasing::createPo((int) Tools::getValue('id_supplier'), $lines('p'), array('id_request' => (int) Tools::getValue('po_request') ?: null, 'expected_date' => Tools::getValue('expected_date'), 'note' => Tools::getValue('pnote'))); Tools::redirectAdmin(self::$currentIndex.'&token='.$this->token.'&id_po='.$id.'&conf=3'); }
            if (Tools::isSubmit('poStatus')) { $st = Tools::getValue('status'); if ($st === 'sent') { $po = PulseInvPurchasing::po((int) Tools::getValue('id_po')); if ($po['total'] > (float) Configuration::get('PULSE_INV_PO_APPROVAL_LIMIT') && !$this->context->employee->isSuperAdmin()) { throw new PrestaShopException('PO above approval limit — a SuperAdmin must approve'); } } PulseInvPurchasing::setPoStatus((int) Tools::getValue('id_po'), $st); $this->confirmations[] = $this->l('PO updated'); }
            if (Tools::isSubmit('receive')) { $id = PulseInvPurchasing::receive((int) Tools::getValue('id_supplier'), (int) Tools::getValue('id_store'), $lines('g'), array('id_po' => (int) Tools::getValue('grn_po') ?: null, 'invoice_no' => Tools::getValue('invoice_no'), 'invoice_date' => Tools::getValue('invoice_date'), 'invoice_total' => Tools::getValue('invoice_total'), 'note' => Tools::getValue('gnote'), 'department' => Tools::getValue('gdept'))); $this->confirmations[] = $this->l('Goods received — stock, costs and expense ledger updated'); }
            if (Tools::isSubmit('autoPr')) { $sug = PulseInvService::reorderSuggestions(); if (!$sug) { throw new PrestaShopException('Nothing below reorder level'); } $ls = array(); foreach ($sug as $s) { $ls[] = array('id' => (int) $s['id_pulse_inv_item'], 'qty' => (float) $s['suggest_purchase_units'], 'note' => 'auto'); } $id = PulseInvPurchasing::createRequest('purchase', $ls, array('note' => 'Auto-generated from reorder levels', 'department' => 'general')); Tools::redirectAdmin(self::$currentIndex.'&token='.$this->token.'&id_request='.$id.'&conf=3'); }
        } catch (Exception $e) { $this->errors[] = $e->getMessage(); }
        return parent::postProcess();
    }
}
