{assign var=r value=$d.revenue}{assign var=o value=$d.occupancy}{assign var=e value=$d.expenses}{assign var=pl value=$d.pl}
<div class="pulse-rpt">
<div class="panel"><h3><i class="icon-bar-chart"></i> Hotel performance dashboard <small>business date {$business_date}</small>
  <span class="pull-right"><a class="btn btn-default btn-sm" href="{$links.expenses}">Expenses</a> <a class="btn btn-default btn-sm" href="{$links.schedules}">Scheduled reports</a> <a class="btn btn-default btn-sm" href="{$links.fd}">Front desk detail reports</a></span></h3>
  <form method="get" class="form-inline"><input type="hidden" name="controller" value="AdminPulseReports"><input type="hidden" name="token" value="{$smarty.get.token|escape}">
    {foreach ['yesterday'=>'Yesterday','today'=>'Today','week'=>'Last 7 days','mtd'=>'Month to date','last_month'=>'Last month','ytd'=>'Year to date'] as $k=>$v}<button name="preset" value="{$k}" class="btn btn-sm {if $preset==$k}btn-primary{else}btn-default{/if}">{$v}</button> {/foreach}
    <input type="hidden" name="preset" value="custom"><input type="date" name="from" value="{$from}" class="form-control input-sm"> <input type="date" name="to" value="{$to}" class="form-control input-sm"> <button class="btn btn-sm btn-default">Custom</button> <button name="export" value="1" class="btn btn-sm btn-default"><i class="icon-download"></i> CSV</button></form>
  <p class="text-muted" style="margin-top:6px">{$from} → {$to} · comparison with the previous {$d.days} day(s)</p>
  {if $d.alerts}<div class="alert alert-warning"><strong>Needs attention</strong><ul style="margin:4px 0 0 16px">{foreach $d.alerts as $a}<li class="{if $a.level=='danger'}text-danger{/if}">{$a.text}</li>{/foreach}</ul></div>{/if}
  <div class="row tiles">
    {function tile label="" value="" sub="" now=0 before=0 pct=false}<div class="col-md-2 tile"><div class="lbl">{$label}</div><div class="val">{$value}</div><div class="sub">{$sub}{if $before}{assign var=ch value=(($now-$before)/abs($before)*100)|round:1} <span class="{if $ch>=0}up{else}down{/if}">{if $ch>=0}▲{else}▼{/if} {$ch|abs}%</span>{/if}</div></div>{/function}
    {tile label="Revenue (net)" value="{$cur}{$r.net|number_format:0}" sub="gross {$cur}{$r.gross|number_format:0}" now=$r.net before=$prev.revenue.net}
    {tile label="Expenses" value="{$cur}{$e.total|number_format:0}" sub="{$e.pending} pending" now=$e.total before=$prev.expenses.total}
    {tile label="Operating profit" value="{$cur}{$pl.gop|number_format:0}" sub="{$pl.gop_pct}% margin" now=$pl.gop before=$prev.pl.gop}
    {tile label="Occupancy" value="{$o.occupancy_pct}%" sub="{$o.room_nights_sold}/{$o.room_nights_available} nights" now=$o.occupancy_pct before=$prev.occupancy.occupancy_pct}
    {tile label="ADR" value="{$cur}{$o.adr|number_format:0}" sub="RevPAR {$cur}{$o.revpar|number_format:0}" now=$o.adr before=$prev.occupancy.adr}
    {tile label="Cash collected" value="{$cur}{$d.payments.total|number_format:0}" sub="net cash {$cur}{$pl.net_cash|number_format:0}" now=$d.payments.total before=$prev.payments.total}
  </div>
</div>
<div class="row">
  <div class="col-md-8"><div class="panel"><h3>Revenue by day</h3>{if $charts.revenue}{$charts.revenue nofilter}{else}<em>Single-day range — choose a longer period for the trend.</em>{/if}</div></div>
  <div class="col-md-4"><div class="panel"><h3>Revenue mix</h3>{$charts.rev_mix nofilter}<table class="table table-condensed"><tbody>{foreach $r.by_department as $x}<tr><td>{$x.department|ucfirst}</td><td class="text-right">{$cur}{$x.net|number_format:0}</td><td class="text-right text-muted">tax {$cur}{$x.tax|number_format:0}</td></tr>{/foreach}<tr><th>Total</th><th class="text-right">{$cur}{$r.net|number_format:0}</th><th class="text-right">{$cur}{$r.tax|number_format:0}</th></tr></tbody></table>{if $r.voids>0}<small class="text-muted">Voids {$cur}{$r.voids|number_format:0}</small>{/if}</div></div>
</div>
<div class="row">
  <div class="col-md-6"><div class="panel"><h3>Occupancy trend</h3>{if $charts.occupancy}{$charts.occupancy nofilter}{else}<em>Run night audit for daily history.</em>{/if}
    <table class="table table-condensed"><thead><tr><th>Room type</th><th>Nights</th><th>Avg rate</th></tr></thead><tbody>{foreach $o.by_type as $t}<tr><td>{$t.type}</td><td>{$t.nights}</td><td>{$cur}{$t.avg_rate|number_format:0}</td></tr>{/foreach}</tbody></table>
    <h4>Next 7 days</h4><table class="table table-condensed"><tbody>{foreach $o.forecast as $f}<tr><td>{$f.d|date_format:"%a %d %b"}</td><td>{$f.occupied} rooms</td><td>{$f.pct}%</td><td>{$f.arrivals} arrivals</td></tr>{/foreach}</tbody></table></div></div>
  <div class="col-md-6"><div class="panel"><h3>Operating statement</h3><table class="table table-condensed"><tbody>
    <tr><td>Revenue (net of tax)</td><td class="text-right">{$cur}{$pl.revenue|number_format:0}</td></tr><tr><td>Cost of sales</td><td class="text-right">({$cur}{$pl.cost_of_sales|number_format:0})</td></tr><tr class="info"><th>Gross profit</th><th class="text-right">{$cur}{$pl.gross_profit|number_format:0}</th></tr>
    <tr><td>Payroll</td><td class="text-right">({$cur}{$pl.payroll|number_format:0})</td></tr><tr><td>Utilities &amp; energy</td><td class="text-right">({$cur}{$pl.utilities|number_format:0})</td></tr><tr><td>Repairs &amp; maintenance</td><td class="text-right">({$cur}{$pl.repairs|number_format:0})</td></tr><tr><td>Other operating</td><td class="text-right">({$cur}{$pl.other_opex|number_format:0})</td></tr>
    <tr class="success"><th>Gross operating profit</th><th class="text-right">{$cur}{$pl.gop|number_format:0} ({$pl.gop_pct}%)</th></tr><tr><td>Cash collected</td><td class="text-right">{$cur}{$pl.cash_in|number_format:0}</td></tr><tr><td>Cash paid out</td><td class="text-right">({$cur}{$pl.cash_out|number_format:0})</td></tr><tr><th>Net cash movement</th><th class="text-right">{$cur}{$pl.net_cash|number_format:0}</th></tr></tbody></table>
    <h4>Expenses by group</h4>{$charts.exp_mix nofilter}{if $charts.expenses}{$charts.expenses nofilter}{/if}</div></div>
</div>
<div class="row">
  <div class="col-md-4"><div class="panel"><h3>Collections &amp; ledgers</h3>{$charts.pay_mix nofilter}<table class="table table-condensed"><tbody>{foreach $d.payments.by_method as $p}<tr><td>{$p.method|replace:'_':' '|ucfirst}</td><td>{$p.n}</td><td class="text-right">{$cur}{$p.total|number_format:0}</td></tr>{/foreach}</tbody></table>
    <p>Guest ledger <strong>{$cur}{$d.ledgers.guest_ledger|number_format:0}</strong><br>City ledger <strong>{$cur}{$d.ledgers.city_ledger|number_format:0}</strong><br>Deposits held <strong>{$cur}{$d.ledgers.deposits_held|number_format:0}</strong></p>
    {if $d.cash}<p class="text-muted">Cashier shifts {$d.cash.shifts} · cash taken {$cur}{$d.cash.cash_taken|number_format:0} · variance {$cur}{$d.cash.variance_total|number_format:0} on {$d.cash.shifts_with_variance} shift(s) · voids {$d.cash.voids_count}</p>{if $d.cash.variances}<table class="table table-condensed"><tbody>{foreach $d.cash.variances as $v}<tr class="warning"><td>{$v.cashier}</td><td>{$v.business_date}</td><td class="text-right">{$v.variance}</td></tr>{/foreach}</tbody></table>{/if}{/if}</div></div>
  <div class="col-md-4"><div class="panel"><h3>Front office &amp; guests</h3>{assign var=f value=$d.frontoffice}{assign var=g value=$d.guests}
    <table class="table table-condensed"><tbody><tr><td>Arrivals / departures</td><td class="text-right">{$f.arrivals} / {$f.departures}</td></tr><tr><td>No-shows / cancellations</td><td class="text-right">{$f.no_shows} / {$f.cancellations}</td></tr><tr><td>Walk-ins</td><td class="text-right">{$f.walk_ins}</td></tr><tr><td>Average length of stay</td><td class="text-right">{$g.avg_los} nights</td></tr><tr><td>Repeat guests</td><td class="text-right">{$g.repeat_pct}%</td></tr><tr><td>VIP in house</td><td class="text-right">{$g.vip_in_house}</td></tr><tr><td>Upsells</td><td class="text-right">{$f.upsell_count} · {$cur}{$f.upsell_revenue|number_format:0}</td></tr><tr><td>Guest requests / complaints</td><td class="text-right">{$f.tickets_raised} / {$f.complaints}</td></tr><tr><td>SLA breached / open now</td><td class="text-right">{$f.tickets_sla_breached} / {$f.tickets_open}</td></tr>{if isset($f.waitlist)}<tr><td>Waitlist</td><td class="text-right">{$f.waitlist}</td></tr>{/if}</tbody></table>
    {if $f.source_mix}<small>Sources: {foreach $f.source_mix as $s}{$s.source|ucfirst} {$s.n} · {/foreach}</small><br>{/if}{if $g.nationality_mix}<small>Nationality: {foreach $g.nationality_mix as $n}{$n.nationality} {$n.n} · {/foreach}</small>{/if}
    {if $g.top_companies}<h4>Top companies</h4><table class="table table-condensed"><tbody>{foreach $g.top_companies as $c}<tr><td>{$c.name}</td><td>{$c.nights}</td><td class="text-right">{$cur}{$c.value|number_format:0}</td></tr>{/foreach}</tbody></table>{/if}</div></div>
  <div class="col-md-4"><div class="panel"><h3>Housekeeping · Laundry · Maintenance</h3>
    {if $d.housekeeping}{assign var=h value=$d.housekeeping}<p><strong>Housekeeping</strong> — tasks {$h.tasks}, done {$h.done}, skipped {$h.skipped}, avg {$h.avg_min} min, open now {$h.open_now}<br><small>{foreach $h.status_now as $s}{$s.hk_status|replace:'_':' '} {$s.n} · {/foreach}</small></p>{if $h.ooo_rooms}<ul>{foreach $h.ooo_rooms as $x}<li>Room {$x.room_num}: {$x.ooo_reason} {if $x.ooo_until}until {$x.ooo_until}{/if}</li>{/foreach}</ul>{/if}{/if}
    {if $d.laundry}{assign var=l value=$d.laundry}<p><strong>Laundry</strong> — orders {$l.orders}, pieces {$l.pieces}, revenue {$cur}{$l.revenue|number_format:0}, express {$l.express}, late {$l.late}, turnaround {$l.turnaround_h}h, in process {$l.in_process}, claims {$l.claims} (open {$l.claims_open}), linen discarded {$l.linen_discarded}</p>{if $l.linen_shortfall}<small class="text-warning">Below par: {foreach $l.linen_shortfall as $x}{$x.name} −{$x.shortfall} · {/foreach}</small>{/if}{/if}
    {if $d.maintenance}{assign var=m value=$d.maintenance}<p><strong>Maintenance</strong> — raised {$m.total|default:0}, closed {$m.closed|default:0}, open now {$m.open_now} (overdue {$m.overdue_now}), emergencies {$m.emergencies}, MTTR {$m.mttr_hours|default:'—'}h, SLA breached {$m.sla_breached|default:0}, cost {$cur}{$m.cost|default:0|number_format:0}</p>{if $m.open_list}<table class="table table-condensed"><tbody>{foreach $m.open_list as $w}<tr class="{if $w.priority=='emergency'}danger{/if}"><td>{$w.wo_no}</td><td>{$w.subject}{if $w.room_num} (Rm {$w.room_num}){/if}</td><td>{$w.priority}</td></tr>{/foreach}</tbody></table>{/if}{if $m.low_stock}<small class="text-warning">Low stock: {foreach $m.low_stock as $p}{$p.name} · {/foreach}</small>{/if}{if $m.meters}<br><small>{foreach $m.meters as $x}{$x.meter|replace:'_':' '} +{$x.delta} · {/foreach}</small>{/if}{/if}</div></div>
</div>
<div class="panel"><h3>Budget vs actual — month to date ({$to|date_format:"%B %Y"})</h3><table class="table table-condensed"><thead><tr><th>Line</th><th class="text-right">Actual MTD</th><th class="text-right">Budget (month)</th><th class="text-right">% of budget</th></tr></thead><tbody>
{foreach $bva as $b}<tr><td>{$b[0]}</td><td class="text-right">{$b[1]|number_format:1}</td><td class="text-right">{if $b[2]!==null}{$b[2]|number_format:1}{else}<em>not set</em>{/if}</td><td class="text-right">{if $b[2]}{($b[1]/$b[2]*100)|round:0}%{/if}</td></tr>{/foreach}</tbody></table><small class="text-muted">Set budgets under Expenses &amp; Budgets.</small></div>
</div>
