<div class="pulse-fd"><div class="panel"><h3><i class="icon-moon"></i> Night Audit &mdash; close business date <strong>{$business_date}</strong></h3>
  <p>The audit will: mark no-shows ({$no_shows|count} candidate(s)) &rarr; post tonight's room charge to {$in_house|count} in-house folio(s) &rarr; create tomorrow's housekeeping tasks &rarr; snapshot statistics &rarr; roll the business date.</p>
  {if $issues}<div class="alert alert-warning"><strong>Pre-checks failed:</strong><ul>{foreach $issues as $i}<li>{$i}</li>{/foreach}</ul></div>{else}<div class="alert alert-success">Pre-checks passed.</div>{/if}
  <form method="post"><label><input type="checkbox" name="force" value="1"> Force run despite warnings (manager only)</label><br>
    <button name="runAudit" class="btn btn-primary btn-lg" onclick="return confirm('Run night audit and close {$business_date}?')"><i class="icon-moon"></i> Run night audit</button></form>
  <p class="help-block" style="margin-top:10px">Automate with cron (03:00 daily): <code>{$cron_url}</code></p>
</div>
{if $no_shows}<div class="panel"><h3>No-show candidates</h3><table class="table table-condensed"><tbody>{foreach $no_shows as $n}<tr><td>{$n.guest}</td><td>{$n.room_num}</td><td>{$n.date_from} → {$n.date_to}</td><td>{$n.order_ref}</td></tr>{/foreach}</tbody></table></div>{/if}
<div class="panel"><h3>Audit history</h3><table class="table table-condensed"><thead><tr><th>Date</th><th>Auditor</th><th>Occ</th><th>Arr/Dep/NS</th><th class="text-right">Rooms</th><th class="text-right">F&amp;B</th><th class="text-right">Other</th><th class="text-right">Tax</th><th class="text-right">Payments</th><th class="text-right">Guest ledger</th><th class="text-right">City ledger</th><th>Status</th></tr></thead><tbody>
{foreach $history as $h}<tr class="{if $h.status=='failed'}danger{/if}"><td>{$h.business_date}</td><td>{$h.auditor}</td><td>{$h.rooms_occupied}/{$h.rooms_total-$h.rooms_ooo}</td><td>{$h.arrivals}/{$h.departures}/{$h.no_shows}</td><td class="text-right">{displayPrice price=$h.room_revenue}</td><td class="text-right">{displayPrice price=$h.fnb_revenue}</td><td class="text-right">{displayPrice price=$h.other_revenue}</td><td class="text-right">{displayPrice price=$h.tax}</td><td class="text-right">{displayPrice price=$h.payments}</td><td class="text-right">{displayPrice price=$h.guest_ledger}</td><td class="text-right">{displayPrice price=$h.city_ledger}</td><td>{$h.status} <a href="#" onclick="$('#log{$h.id_pulse_night_audit}').toggle();return false">log</a><pre id="log{$h.id_pulse_night_audit}" style="display:none">{$h.log}</pre></td></tr>{/foreach}</tbody></table></div></div>
