<div class="pulse-rpt"><div class="panel"><h3><i class="icon-envelope"></i> Scheduled reports</h3>
<table class="table"><thead><tr><th>Name</th><th>Report</th><th>Email recipients</th><th>SMS recipients</th><th>When</th><th>Last sent</th><th>Active</th><th></th></tr></thead><tbody>
{foreach $schedules as $s}<tr class="{if !$s.active}text-muted{/if}"><td>{$s.name}</td><td>{$s.report|replace:'_':' '}</td><td><small>{$s.recipients_email}</small></td><td><small>{$s.recipients_sms}</small></td><td>{if $s.send_after_audit && ($s.report=='owner_daily'||$s.report=='manager_daily')}after night audit, or {/if}{$s.send_time|substr:0:5}{if $s.report=='weekly'} (weekday {$s.weekday}){elseif $s.report=='monthly'} (day {$s.month_day}){/if}</td><td>{$s.last_sent|default:'—'}<br><small>{$s.last_business_date}</small></td><td>{if $s.active}yes{else}no{/if}</td>
<td><form method="post" class="inline"><input type="hidden" name="id_schedule" value="{$s.id_pulse_report_schedule}"><input type="hidden" name="bd" value="{$bd}"><button name="preview" class="btn btn-xs btn-default" formtarget="_blank">Preview</button> <button name="sendNow" class="btn btn-xs btn-primary" onclick="return confirm('Send now for business date {$bd}?')">Send now</button></form></td></tr>{/foreach}</tbody></table>
<h4>Add / edit schedule</h4><form method="post" class="form-inline"><input name="id_schedule" type="hidden"><input name="name" class="form-control" placeholder="Name" required> <select name="report" class="form-control"><option value="owner_daily">Owner daily snapshot</option><option value="manager_daily">Manager daily operations</option><option value="weekly">Weekly owner summary</option><option value="monthly">Monthly owner report</option><option value="alerts">Alerts only</option></select><br>
<input name="recipients_email" class="form-control" placeholder="owner@…, gm@… (comma separated)" style="width:45%"> <input name="recipients_sms" class="form-control" placeholder="+234… (comma separated)" {if !$sms_ok}disabled title="Needs Front Desk comms"{/if}> <input name="send_time" type="time" class="form-control" value="06:30"> <label><input type="checkbox" name="send_after_audit" value="1" checked> also right after night audit</label> <select name="weekday" class="form-control"><option value="">weekday—</option>{foreach ['1'=>'Mon','2'=>'Tue','3'=>'Wed','4'=>'Thu','5'=>'Fri','6'=>'Sat','7'=>'Sun'] as $k=>$v}<option value="{$k}">{$v}</option>{/foreach}</select> <input name="month_day" class="form-control" placeholder="day of month" style="width:110px"> <label><input type="checkbox" name="active" value="1" checked> active</label> <button name="saveSchedule" class="btn btn-default">Save</button></form>
<p class="help-block">Cron (every 15 minutes): <code>{$cron_url}</code>. Daily reports flagged "after night audit" go out the moment the audit closes; the send time is the fallback if the audit is late.</p></div>
<div class="panel"><h3>Send history</h3><table class="table table-condensed"><thead><tr><th>Sent</th><th>Report</th><th>Business date</th><th>Recipients</th><th>Status</th><th></th></tr></thead><tbody>{foreach $log as $l}<tr class="{if $l.status=='failed'}danger{/if}"><td>{$l.date_add}</td><td>{$l.report}</td><td>{$l.business_date}</td><td><small>{$l.recipients}</small></td><td>{$l.status} {$l.error}</td><td><a href="{$self_url}&view_log={$l.id_pulse_report_log}">view</a></td></tr>{/foreach}</tbody></table></div>
{if isset($log_html)}<div class="panel"><h3>Report as sent</h3><div style="background:#f4f6f8;padding:12px">{$log_html nofilter}</div></div>{/if}</div>
