<div class="pulse-mnt"><div class="panel"><h3><i class="icon-calendar"></i> Preventive maintenance programme ({$rooms_total} rooms)
<form method="post" class="pull-right"><button name="generatePm" class="btn btn-primary btn-sm">Generate today's PM work orders</button></form></h3>
<table class="table table-condensed"><thead><tr><th>Schedule</th><th>Scope</th><th>Every</th><th>Rooms/day</th><th>Rooms current</th><th>Next due</th><th>Last run</th><th>Tech</th><th>Open WO</th><th>Active</th></tr></thead><tbody>
{foreach $schedules as $s}<tr class="{if !$s.active}text-muted{/if}"><td>{$s.name}<br><small>{$s.category} &middot; {$s.est_minutes} min &middot; {$s.priority}</small></td><td>{$s.scope|replace:'_':' '} {$s.asset_name} {$s.location}</td><td>{$s.interval_days} d</td><td>{if $s.scope=='all_rooms' || $s.scope=='room_type'}{$s.rooms_per_run}{/if}</td><td>{if $s.scope=='all_rooms'}{$s.rooms_current}/{$rooms_total}{/if}</td><td>{$s.next_due}</td><td>{$s.last_run}</td><td>{$s.tech}</td><td>{$s.open_wo}</td><td><form method="post" class="inline"><input type="hidden" name="id_schedule" value="{$s.id_pulse_pm_schedule}"><button name="toggleSchedule" class="btn btn-xs btn-default">{if $s.active}pause{else}resume{/if}</button></form></td></tr>{/foreach}</tbody></table>
<h4>Add schedule</h4><form method="post" class="form-horizontal"><input type="hidden" name="id_schedule"><div class="row"><div class="col-md-6">
<div class="form-group"><label class="col-sm-3">Name</label><div class="col-sm-9"><input name="name" class="form-control" required></div></div>
<div class="form-group"><label class="col-sm-3">Category / priority</label><div class="col-sm-5"><select name="category" class="form-control">{foreach $categories as $c}<option>{$c}</option>{/foreach}</select></div><div class="col-sm-4"><select name="priority" class="form-control"><option value="normal">normal</option><option value="high">high</option><option value="low">low</option></select></div></div>
<div class="form-group"><label class="col-sm-3">Scope</label><div class="col-sm-9"><select name="scope" class="form-control"><option value="all_rooms">All rooms (rolling)</option><option value="room_type">Rooms of one type (rolling)</option><option value="asset">One asset</option><option value="location">A location</option></select><select name="id_pulse_asset" class="form-control"><option value="">asset —</option>{foreach $assets as $a}<option value="{$a.id_pulse_asset}">{$a.code} {$a.name}</option>{/foreach}</select><select name="id_product" class="form-control"><option value="">room type —</option>{foreach $room_types as $t}<option value="{$t.id_product}">{$t.name}</option>{/foreach}</select><input name="location" class="form-control" placeholder="location"></div></div>
<div class="form-group"><label class="col-sm-3">Every (days) / rooms per day / est. minutes</label><div class="col-sm-3"><input name="interval_days" class="form-control" value="90"></div><div class="col-sm-3"><input name="rooms_per_run" class="form-control" value="4"></div><div class="col-sm-3"><input name="est_minutes" class="form-control" value="45"></div></div>
<div class="form-group"><label class="col-sm-3">Technician / first due</label><div class="col-sm-5"><select name="assigned_to" class="form-control"><option value="">—</option>{foreach $techs as $t}<option value="{$t.id_employee}">{$t.firstname} {$t.lastname}</option>{/foreach}</select></div><div class="col-sm-4"><input type="date" name="next_due" class="form-control"></div></div></div>
<div class="col-md-6"><div class="form-group"><label class="col-sm-3">Checklist (one per line)</label><div class="col-sm-9"><textarea name="checklist" class="form-control" rows="7"></textarea></div></div><button name="saveSchedule" class="btn btn-default pull-right">Save schedule</button></div></div></form>
<p class="help-block">Rolling schedules spread the work: with 52 rooms, 4 rooms/day and a 90-day interval, every room is serviced once per quarter. Occupied rooms are skipped automatically when Front Desk is installed. Daily cron: <code>{$cron_url}</code></p></div></div>
