CREATE TABLE IF NOT EXISTS `PREFIX_pulse_ch_channel` (
  `id_pulse_ch_channel` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(32) NOT NULL COMMENT 'booking_com, expedia, agoda, airbnb, hotels_ng, jumia, traveloka, generic_json, csv_email',
  `name` VARCHAR(128) NOT NULL,
  `adapter` VARCHAR(64) NOT NULL DEFAULT 'PulseChAdapterGeneric' COMMENT 'PulseChAdapterInterface implementation',
  `endpoint` VARCHAR(255) DEFAULT NULL,
  `pull_endpoint` VARCHAR(255) DEFAULT NULL,
  `ack_endpoint` VARCHAR(255) DEFAULT NULL,
  `auth_type` ENUM('none','basic','bearer','hmac','api_key','soap_ws_security') NOT NULL DEFAULT 'bearer',
  `auth_header` VARCHAR(64) NOT NULL DEFAULT 'Authorization',
  `credentials` TEXT COMMENT 'PulseCoreService::encrypt of a JSON blob (username, password, api_key, secret)',
  `hotel_code` VARCHAR(64) DEFAULT NULL COMMENT 'the OTA hotel/property id',
  `id_hotel` INT UNSIGNED DEFAULT NULL COMMENT 'QloApps htl_branch_information id when multi-property',
  `currency_iso` CHAR(3) NOT NULL DEFAULT 'NGN',
  `commission_pct` DECIMAL(6,3) NOT NULL DEFAULT 0,
  `payload_format` ENUM('json','xml','csv','form') NOT NULL DEFAULT 'json',
  `payload_template` TEXT COMMENT 'optional body template for XML/JSON adapters; {{placeholders}} substituted',
  `sync_mode` ENUM('push','pull','both','off') NOT NULL DEFAULT 'both',
  `push_window_days` SMALLINT UNSIGNED NOT NULL DEFAULT 365,
  `allotment` SMALLINT NOT NULL DEFAULT 0 COMMENT 'rooms this channel may sell per night, 0 = all',
  `oversell_buffer` TINYINT NOT NULL DEFAULT 0,
  `release_days` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `batch_size` SMALLINT UNSIGNED NOT NULL DEFAULT 200,
  `timeout_sec` TINYINT UNSIGNED NOT NULL DEFAULT 20,
  `csv_in_dir` VARCHAR(255) DEFAULT NULL COMMENT 'CSV adapter: drop folder for inbound reservation files',
  `csv_out_dir` VARCHAR(255) DEFAULT NULL COMMENT 'CSV adapter: folder ARI files are written to',
  `enabled` TINYINT(1) NOT NULL DEFAULT 0,
  `test_mode` TINYINT(1) NOT NULL DEFAULT 1,
  `auto_deliver` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'create the QloApps booking automatically',
  `health` ENUM('unknown','ok','degraded','down') NOT NULL DEFAULT 'unknown',
  `last_success` DATETIME DEFAULT NULL,
  `last_failure` DATETIME DEFAULT NULL,
  `fail_since` DATETIME DEFAULT NULL,
  `last_error` VARCHAR(255) DEFAULT NULL,
  `last_pull` DATETIME DEFAULT NULL,
  `alerted_at` DATETIME DEFAULT NULL,
  `notes` TEXT,
  `date_add` DATETIME NOT NULL, `date_upd` DATETIME NOT NULL,
  PRIMARY KEY (`id_pulse_ch_channel`), UNIQUE KEY `code` (`code`), KEY `en` (`enabled`,`sync_mode`)
) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `PREFIX_pulse_ch_rate_plan` (
  `id_pulse_ch_rate_plan` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(32) NOT NULL, `name` VARCHAR(128) NOT NULL,
  `meal_plan` ENUM('room_only','bed_breakfast','half_board','full_board','all_inclusive') NOT NULL DEFAULT 'room_only',
  `derive_from` INT UNSIGNED DEFAULT NULL COMMENT 'parent rate plan; NULL = base/BAR',
  `adjust_type` ENUM('none','percent','amount') NOT NULL DEFAULT 'none',
  `adjust_value` DECIMAL(20,6) NOT NULL DEFAULT 0,
  `refundable` TINYINT(1) NOT NULL DEFAULT 1,
  `min_los` TINYINT UNSIGNED NOT NULL DEFAULT 1, `max_los` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `release_days` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `active` TINYINT(1) NOT NULL DEFAULT 1, `sort` SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_pulse_ch_rate_plan`), UNIQUE KEY `code` (`code`)
) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `PREFIX_pulse_ch_mapping` (
  `id_pulse_ch_mapping` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_pulse_ch_channel` INT UNSIGNED NOT NULL,
  `id_product` INT UNSIGNED NOT NULL COMMENT 'our room type',
  `id_pulse_ch_rate_plan` INT UNSIGNED NOT NULL,
  `channel_room_code` VARCHAR(64) NOT NULL,
  `channel_rate_code` VARCHAR(64) NOT NULL,
  `base_occupancy` TINYINT UNSIGNED NOT NULL DEFAULT 2,
  `max_occupancy` TINYINT UNSIGNED NOT NULL DEFAULT 2,
  `single_adj` DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT 'single = double + this (usually negative, e.g. -5000)',
  `extra_adult_adj` DECIMAL(20,6) NOT NULL DEFAULT 0,
  `child_adj` DECIMAL(20,6) NOT NULL DEFAULT 0,
  `rate_adjust_type` ENUM('none','percent','amount') NOT NULL DEFAULT 'none',
  `rate_adjust_value` DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT 'channel markup/markdown applied after the rate plan',
  `allotment` SMALLINT NOT NULL DEFAULT 0 COMMENT 'per room type cap for this channel, 0 = channel default',
  `min_los` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0 = inherit',
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `date_add` DATETIME NOT NULL, `date_upd` DATETIME NOT NULL,
  PRIMARY KEY (`id_pulse_ch_mapping`), UNIQUE KEY `map` (`id_pulse_ch_channel`,`id_product`,`id_pulse_ch_rate_plan`),
  KEY `chan_code` (`id_pulse_ch_channel`,`channel_room_code`,`channel_rate_code`)
) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `PREFIX_pulse_ch_ari` (
  `id_pulse_ch_ari` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_pulse_ch_channel` INT UNSIGNED NOT NULL,
  `id_product` INT UNSIGNED NOT NULL,
  `id_pulse_ch_rate_plan` INT UNSIGNED NOT NULL,
  `ari_date` DATE NOT NULL COMMENT 'stay date',
  `physical` SMALLINT NOT NULL DEFAULT 0, `booked` SMALLINT NOT NULL DEFAULT 0,
  `blocked` SMALLINT NOT NULL DEFAULT 0, `ooo` SMALLINT NOT NULL DEFAULT 0,
  `available` SMALLINT NOT NULL DEFAULT 0 COMMENT 'what this channel may sell after allotment + buffer',
  `rate` DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT 'double / base occupancy, tax incl, channel currency',
  `rate_single` DECIMAL(20,6) NOT NULL DEFAULT 0,
  `rate_extra_adult` DECIMAL(20,6) NOT NULL DEFAULT 0,
  `rate_child` DECIMAL(20,6) NOT NULL DEFAULT 0,
  `min_los` TINYINT UNSIGNED NOT NULL DEFAULT 1, `max_los` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `cta` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'closed to arrival',
  `ctd` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'closed to departure',
  `stop_sell` TINYINT(1) NOT NULL DEFAULT 0,
  `release_days` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `manual_rate` DECIMAL(20,6) DEFAULT NULL COMMENT 'desk override; wins over the computed rate until cleared',
  `manual_stop_sell` TINYINT(1) DEFAULT NULL,
  `manual_min_los` TINYINT UNSIGNED DEFAULT NULL, `manual_max_los` TINYINT UNSIGNED DEFAULT NULL,
  `cell_hash` CHAR(32) NOT NULL DEFAULT '',
  `pushed_hash` CHAR(32) DEFAULT NULL,
  `pushed_rate` DECIMAL(20,6) DEFAULT NULL, `pushed_available` SMALLINT DEFAULT NULL, `pushed_at` DATETIME DEFAULT NULL,
  `date_upd` DATETIME NOT NULL,
  PRIMARY KEY (`id_pulse_ch_ari`), UNIQUE KEY `cell` (`id_pulse_ch_channel`,`id_product`,`id_pulse_ch_rate_plan`,`ari_date`),
  KEY `d` (`ari_date`), KEY `dirty` (`id_pulse_ch_channel`,`ari_date`,`cell_hash`,`pushed_hash`)
) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `PREFIX_pulse_ch_queue` (
  `id_pulse_ch_queue` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_pulse_ch_channel` INT UNSIGNED NOT NULL,
  `id_product` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0 = every mapped room type',
  `id_pulse_ch_rate_plan` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0 = every mapped rate plan',
  `date_from` DATE NOT NULL, `date_to` DATE NOT NULL,
  `type` ENUM('ari','inventory','rate','restriction','full') NOT NULL DEFAULT 'ari',
  `reason` VARCHAR(64) NOT NULL DEFAULT 'change',
  `status` ENUM('pending','sending','sent','failed','poison','cancelled') NOT NULL DEFAULT 'pending',
  `attempts` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `next_attempt_at` DATETIME NOT NULL,
  `cells` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `last_error` VARCHAR(255) DEFAULT NULL,
  `business_date` DATE NOT NULL,
  `date_add` DATETIME NOT NULL, `date_upd` DATETIME NOT NULL,
  PRIMARY KEY (`id_pulse_ch_queue`), KEY `drain` (`status`,`next_attempt_at`), KEY `chan` (`id_pulse_ch_channel`,`status`)
) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `PREFIX_pulse_ch_reservation` (
  `id_pulse_ch_reservation` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_pulse_ch_channel` INT UNSIGNED NOT NULL,
  `channel_ref` VARCHAR(64) NOT NULL COMMENT 'OTA booking reference — dedupe key',
  `channel_ref_alt` VARCHAR(64) DEFAULT NULL,
  `action` ENUM('new','modify','cancel') NOT NULL DEFAULT 'new',
  `status` ENUM('received','delivered','modified','cancelled','failed','ignored') NOT NULL DEFAULT 'received',
  `id_order` INT UNSIGNED DEFAULT NULL,
  `id_htl_booking` INT UNSIGNED DEFAULT NULL,
  `booking_ids` VARCHAR(255) DEFAULT NULL COMMENT 'CSV of htl_booking_detail ids created',
  `id_customer` INT UNSIGNED DEFAULT NULL,
  `guest_name` VARCHAR(128) NOT NULL DEFAULT '', `email` VARCHAR(128) DEFAULT NULL, `phone` VARCHAR(32) DEFAULT NULL,
  `country_iso` CHAR(3) DEFAULT NULL,
  `id_product` INT UNSIGNED DEFAULT NULL,
  `id_pulse_ch_rate_plan` INT UNSIGNED DEFAULT NULL,
  `channel_room_code` VARCHAR(64) DEFAULT NULL, `channel_rate_code` VARCHAR(64) DEFAULT NULL,
  `date_from` DATE DEFAULT NULL, `date_to` DATE DEFAULT NULL,
  `rooms` TINYINT UNSIGNED NOT NULL DEFAULT 1, `adults` TINYINT UNSIGNED NOT NULL DEFAULT 1, `children` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `currency_iso` CHAR(3) NOT NULL DEFAULT 'NGN',
  `amount_tax_incl` DECIMAL(20,6) NOT NULL DEFAULT 0,
  `tax_amount` DECIMAL(20,6) NOT NULL DEFAULT 0,
  `commission_pct` DECIMAL(6,3) NOT NULL DEFAULT 0, `commission_amount` DECIMAL(20,6) NOT NULL DEFAULT 0,
  `net_amount` DECIMAL(20,6) NOT NULL DEFAULT 0,
  `payment_type` ENUM('hotel_collect','channel_collect','unknown') NOT NULL DEFAULT 'hotel_collect',
  `overbooked` TINYINT(1) NOT NULL DEFAULT 0,
  `acked` TINYINT(1) NOT NULL DEFAULT 0, `acked_at` DATETIME DEFAULT NULL,
  `error` VARCHAR(255) DEFAULT NULL,
  `raw_payload` MEDIUMTEXT,
  `notes` VARCHAR(255) DEFAULT NULL,
  `business_date` DATE NOT NULL,
  `date_add` DATETIME NOT NULL, `date_upd` DATETIME NOT NULL, `delivered_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id_pulse_ch_reservation`), UNIQUE KEY `ref` (`id_pulse_ch_channel`,`channel_ref`),
  KEY `st` (`status`,`date_add`), KEY `bk` (`id_htl_booking`), KEY `bdate` (`business_date`)
) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `PREFIX_pulse_ch_log` (
  `id_pulse_ch_log` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_pulse_ch_channel` INT UNSIGNED NOT NULL DEFAULT 0,
  `direction` ENUM('out','in') NOT NULL DEFAULT 'out',
  `type` VARCHAR(32) NOT NULL COMMENT 'ari_push|reservation_pull|reservation_in|ack|test|api_ari|api_health',
  `reference` VARCHAR(64) DEFAULT NULL,
  `http_status` SMALLINT UNSIGNED DEFAULT NULL,
  `request` MEDIUMTEXT, `response` MEDIUMTEXT,
  `duration_ms` INT UNSIGNED NOT NULL DEFAULT 0,
  `status` ENUM('ok','error') NOT NULL DEFAULT 'ok',
  `error` VARCHAR(255) DEFAULT NULL,
  `business_date` DATE NOT NULL,
  `date_add` DATETIME NOT NULL,
  PRIMARY KEY (`id_pulse_ch_log`), KEY `chan` (`id_pulse_ch_channel`,`date_add`), KEY `st` (`status`,`date_add`)
) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8;

INSERT IGNORE INTO `PREFIX_pulse_ch_rate_plan` (`id_pulse_ch_rate_plan`,`code`,`name`,`meal_plan`,`derive_from`,`adjust_type`,`adjust_value`,`refundable`,`min_los`,`sort`) VALUES
(1,'BAR','Best Available Rate','room_only',NULL,'none',0,1,1,1),
(2,'BB','Bed & Breakfast','bed_breakfast',1,'amount',7500,1,1,2),
(3,'NONREF','Non-refundable','room_only',1,'percent',-10,0,1,3),
(4,'CORP','Corporate negotiated','bed_breakfast',1,'percent',-15,1,1,4),
(5,'LONGSTAY','Long stay (7 nights+)','bed_breakfast',1,'percent',-20,1,7,5);

INSERT IGNORE INTO `PREFIX_pulse_ch_channel` (`code`,`name`,`adapter`,`endpoint`,`pull_endpoint`,`auth_type`,`payload_format`,`sync_mode`,`currency_iso`,`commission_pct`,`enabled`,`test_mode`,`notes`,`date_add`,`date_upd`) VALUES
('booking_com','Booking.com','PulseChAdapterHttp','','','basic','xml','both','NGN',15,0,1,'Booking.com Connectivity APIs require partner certification. Set the endpoint, machine account and property id issued to you, then run Test connection.',NOW(),NOW()),
('expedia','Expedia Group','PulseChAdapterHttp','','','basic','xml','both','NGN',18,0,1,'Expedia QuickConnect / Rapid. Endpoint and credentials are issued after certification.',NOW(),NOW()),
('agoda','Agoda','PulseChAdapterHttp','','','api_key','xml','both','NGN',17,0,1,'Agoda YCS channel connectivity. Endpoint and API key issued after certification.',NOW(),NOW()),
('airbnb','Airbnb','PulseChAdapterHttp','','','bearer','json','both','NGN',3,0,1,'Airbnb API partner programme; OAuth bearer token. Availability is per listing — map one listing code per room type.',NOW(),NOW()),
('hotels_ng','Hotels.ng','PulseChAdapterGeneric','','','bearer','json','both','NGN',12,0,1,'Nigerian OTA. Uses the Pulse generic JSON contract; give your account manager the README contract.',NOW(),NOW()),
('jumia','Jumia Travel','PulseChAdapterGeneric','','','bearer','json','both','NGN',12,0,1,'Nigerian OTA. Generic JSON contract or CSV drop.',NOW(),NOW()),
('traveloka','Traveloka','PulseChAdapterHttp','','','hmac','json','both','NGN',15,0,1,'Traveloka Connectivity. HMAC-signed JSON; endpoint issued after certification.',NOW(),NOW()),
('generic_json','Generic JSON partner','PulseChAdapterGeneric','','','bearer','json','both','NGN',0,0,1,'The documented Pulse JSON contract — use for an intermediary (eZee Centrix, RateTiger, SiteMinder) or any partner that will build to our spec.',NOW(),NOW()),
('csv_email','CSV / e-mail drop','PulseChAdapterCsv','','','none','csv','both','NGN',10,0,1,'For OTAs with no API: ARI is written as CSV to the out folder, reservations are read from CSV files dropped in the in folder.',NOW(),NOW());
